services:
    oek.dao:
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@knp_paginator'
            - '%pagination.items_per_page%'

    OekBundle\Service\DeelnemerDao:
        parent: oek.dao

    OekBundle\Service\GroepDao:
        parent: oek.dao

    OekBundle\Service\TrainingDao:
        parent: oek.dao

    OekBundle\Service\VerwijzingDoorDao:
        parent: oek.dao

    OekBundle\Service\VerwijzingNaarDao:
        parent: oek.dao

    oek.training.entities:
        class: ArrayObject
        arguments:
            -
              - { key: groep, dao: '@OekBundle\Service\GroepDao' }
