odp_annotations:
    resource: "@OekBundle/Controller"
    type: annotation

oek_index:
    path: /oek
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: oek_klanten_index
