imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    OekBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    oek.event.diensten_lookup_subscriber:
        class: OekBundle\Event\DienstenLookupSubscriber
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    oek.repository.deelnemer:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - OekBundle\Entity\Deelnemer

    oek.repository.training:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - OekBundle\Entity\Training

    oek.form.rapportage:
        class: OekBundle\Form\RapportageType
        tags:
            - { name: form.type }

    OekBundle\Report\DeelnemersPerTrainingGroep:
        public: true
        arguments:
            - "@oek.repository.deelnemer"
        tags:
            - { name: oek.rapportage, category: Deelnemers }

    OekBundle\Report\DeelnemersVerwezenDoor:
        public: true
        arguments:
            - "@oek.repository.deelnemer"
        tags:
            - { name: oek.rapportage, category: Deelnemers }

    OekBundle\Report\DeelnemersVerwezenNaar:
        public: true
        arguments:
            - "@oek.repository.deelnemer"
        tags:
            - { name: oek.rapportage, category: Deelnemers }

    OekBundle\Report\TrainingenPerGroepNaam:
        public: true
        arguments:
            - "@oek.repository.training"
        tags:
            - { name: oek.rapportage, category: Trainingen }
