services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    ErOpUitBundle\Service\:
        resource: '%kernel.project_dir%/src/ErOpUitBundle/Service/'

