imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ErOpUitBundle\Command\:
        resource: '%kernel.project_dir%/src/ErOpUitBundle/Command'

    ErOpUitBundle\Controller\:
        resource: '%kernel.project_dir%/src/ErOpUitBundle/Controller'

    ErOpUitBundle\Controller\KlantenController:
        arguments:
            $export: '@eropuit.export.klanten'

    ErOpUitBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@eropuit.export.vrijwilligers'

    ErOpUitBundle\Event\CloseSubscriber:

    ErOpUitBundle\Event\DienstenLookupSubscriber:

    ErOpUitBundle\Event\IzIntakeSubscriber:
        arguments:
            - '@ErOpUitBundle\Service\KlantDao'

    ErOpUitBundle\Event\ScipDeelnemerSubscriber:
        arguments:
            - '@ErOpUitBundle\Service\KlantDao'

    ErOpUitBundle\Event\OekDeelnemerSubscriber:
        arguments:
            - '@ErOpUitBundle\Service\KlantDao'

    eou_klant_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - 'ErOpUitBundle\Entity\Klant'

    ErOpUitBundle\Repository\ErOpUitRepository:
        arguments:
            $class: "@eou_klant_metadata"
        tags:
            - app.doelstelling
    
    ErOpUitBundle\Controller\IncidentenController:
        arguments:
            $entities: '@eropuit.incident.entities'
