imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ErOpUitBundle\Command\:
        resource: '%kernel.project_dir%/src/ErOpUitBundle/Command'
        tags: [ 'console.command' ]

    ErOpUitBundle\Controller\:
        resource: '%kernel.project_dir%/src/ErOpUitBundle/Controller'
        tags: [ 'controller.service_arguments' ]

    ErOpUitBundle\Controller\KlantenController:
        arguments:
            $export: '@eropuit.export.klanten'
        tags: [ 'controller.service_arguments' ]

    ErOpUitBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@eropuit.export.vrijwilligers'
        tags: [ 'controller.service_arguments' ]

    ErOpUitBundle\Event\CloseSubscriber:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    ErOpUitBundle\Event\DienstenLookupSubscriber:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    ErOpUitBundle\Event\IzIntakeSubscriber:
        arguments:
            - '@ErOpUitBundle\Service\KlantDao'
        tags:
            - { name: kernel.event_subscriber }

    ErOpUitBundle\Event\ScipDeelnemerSubscriber:
        arguments:
            - '@ErOpUitBundle\Service\KlantDao'
        tags:
            - { name: kernel.event_subscriber }

    ErOpUitBundle\Event\OekDeelnemerSubscriber:
        arguments:
            - '@ErOpUitBundle\Service\KlantDao'
        tags:
            - { name: kernel.event_subscriber }

    eou_klant_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - 'ErOpUitBundle\Entity\Klant'

    ErOpUitBundle\Repository\ErOpUitRepository:
        class: ErOpUitBundle\Repository\ErOpUitRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@eou_klant_metadata"
        tags:
            - app.doelstelling
        public: true