doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: "utf8"
        default_table_options:
            charset: "utf8"
            collate: "utf8_general_ci"
        types:
            mysql_date: AppBundle\Doctrine\MysqlDateType
            mysql_time: AppBundle\Doctrine\MysqlTimeType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: AppBundle\Doctrine\EcdNamingStrategy #dunno but since flex we need this probably due to bundle stuff.
        auto_mapping: true
        # @todo: because auto_mapping above is true, the mappings below could probably be removed
        mappings:
            AppBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/AppBundle/Entity'
                prefix: 'AppBundle\Entity'
                alias: AppBundle
            BuurtboerderijBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/BuurtboerderijBundle/Entity'
                prefix: 'BuurtboerderijBundle\Entity'
                alias: BuurtboerderijBundle
            ClipBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/ClipBundle/Entity'
                prefix: 'ClipBundle\Entity'
                alias: ClipBundle
            DagbestedingBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/DagbestedingBundle/Entity'
                prefix: 'DagbestedingBundle\Entity'
                alias: DagbestedingBundle
            ErOpUitBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/ErOpUitBundle/Entity'
                prefix: 'ErOpUitBundle\Entity'
                alias: ErOpUitBundle
            GaBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/GaBundle/Entity'
                prefix: 'GaBundle\Entity'
                alias: GaBundle
            HsBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/HsBundle/Entity'
                prefix: 'HsBundle\Entity'
                alias: HsBundle
            InloopBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/InloopBundle/Entity'
                prefix: 'InloopBundle\Entity'
                alias: InloopBundle
            IzBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/IzBundle/Entity'
                prefix: 'IzBundle\Entity'
                alias: IzBundle
            LegacyBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/LegacyBundle/Entity'
                prefix: 'LegacyBundle\Entity'
                alias: LegacyBundle
            MwBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/MwBundle/Entity'
                prefix: 'MwBundle\Entity'
                alias: MwBundle
            OekBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/OekBundle/Entity'
                prefix: 'OekBundle\Entity'
                alias: OekBundle
            OekraineBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/OekraineBundle/Entity'
                prefix: 'OekraineBundle\Entity'
                alias: OekraineBundle
            PfoBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/PfoBundle/Entity'
                prefix: 'PfoBundle\Entity'
                alias: PfoBundle
            ScipBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/ScipBundle/Entity'
                prefix: 'ScipBundle\Entity'
                alias: ScipBundle
            TwBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/TwBundle/Entity'
                prefix: 'TwBundle\Entity'
                alias: TwBundle
            UhkBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/UhkBundle/Entity'
                prefix: 'UhkBundle\Entity'
                alias: UhkBundle
            VillaBundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/VillaBundle/Entity'
                prefix: 'VillaBundle\Entity'
                alias: VillaBundle
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
                is_bundle: false
                alias: GedmoLoggable # (optional) it will default to the name set for the mapping
        dql:
            datetime_functions:
                date: Luxifer\DQL\Datetime\Date
                datediff: DoctrineExtensions\Query\Mysql\DateDiff
                date_format: Luxifer\DQL\Datetime\DateFormat
                hour: DoctrineExtensions\Query\Mysql\Hour
                ifnull: DoctrineExtensions\Query\Mysql\IfNull
                minute: DoctrineExtensions\Query\Mysql\Minute
                now: DoctrineExtensions\Query\Mysql\Now
                time: Luxifer\DQL\Datetime\Time
                time_diff: DoctrineExtensions\Query\Mysql\TimeDiff
                time_to_sec: DoctrineExtensions\Query\Mysql\TimeToSec
                year: Luxifer\DQL\Datetime\Year
            string_functions:
                concat_ws: Luxifer\DQL\String\ConcatWs
                replace: DoctrineExtensions\Query\Mysql\Replace
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
            disabled:
                class: AppBundle\Doctrine\DisabledFilter
                enabled: true
            active:
                class: AppBundle\Doctrine\ActiveFilter
                enabled: false
            zichtbaar:
                class: AppBundle\Doctrine\ZichtbaarFilter
                enabled: true
            foutieve_invoer:
                class: IzBundle\Doctrine\FoutieveInvoerFilter
                enabled: true
            overleden:
                class: AppBundle\Doctrine\OverledenFilter
                enabled: false
