doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: "utf8"
        default_table_options:
            charset: "utf8"
            collate: "utf8_general_ci"
        types:
            mysql_date: AppBundle\Doctrine\MysqlDateType
            mysql_time: AppBundle\Doctrine\MysqlTimeType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: AppBundle\Doctrine\EcdNamingStrategy
        auto_mapping: true
        mappings:
            app:
                type: annotation
                prefix: AppBundle\Entity
                dir: "%kernel.project_dir%/src/AppBundle/Entity"
            buurtboerderij:
                type: annotation
                prefix: BuurtboerderijBundle\Entity
                dir: "%kernel.project_dir%/src/BuurtboerderijBundle/Entity"
            clip:
                type: annotation
                prefix: ClipBundle\Entity
                dir: "%kernel.project_dir%/src/ClipBundle/Entity"
            dagbesteding:
                type: annotation
                prefix: DagbestedingBundle\Entity
                dir: "%kernel.project_dir%/src/DagbestedingBundle/Entity"
            eropuit:
                type: annotation
                prefix: ErOpUitBundle\Entity
                dir: "%kernel.project_dir%/src/ErOpUitBundle/Entity"
            ga:
                type: annotation
                prefix: GaBundle\Entity
                dir: "%kernel.project_dir%/src/GaBundle/Entity"
            hs:
                type: annotation
                prefix: HsBundle\Entity
                dir: "%kernel.project_dir%/src/HsBundle/Entity"
            inloop:
                type: annotation
                prefix: InloopBundle\Entity
                dir: "%kernel.project_dir%/src/InloopBundle/Entity"
            iz:
                type: annotation
                prefix: IzBundle\Entity
                dir: "%kernel.project_dir%/src/IzBundle/Entity"
            mw:
                type: annotation
                prefix: MwBundle\Entity
                dir: "%kernel.project_dir%/src/MwBundle/Entity"
            oek:
                type: annotation
                prefix: OekBundle\Entity
                dir: "%kernel.project_dir%/src/OekBundle/Entity"
            oekraine:
                type: annotation
                prefix: OekraineBundle\Entity
                dir: "%kernel.project_dir%/src/OekraineBundle/Entity"
            pfo:
                type: annotation
                prefix: PfoBundle\Entity
                dir: "%kernel.project_dir%/src/PfoBundle/Entity"
            scip:
                type: annotation
                prefix: ScipBundle\Entity
                dir: "%kernel.project_dir%/src/ScipBundle/Entity"
            tw:
                type: annotation
                prefix: TwBundle\Entity
                dir: "%kernel.project_dir%/src/TwBundle/Entity"
            uhk:
                type: annotation
                prefix: UhkBundle\Entity
                dir: "%kernel.project_dir%/src/UhkBundle/Entity"
            villa:
                type: annotation
                prefix: VillaBundle\Entity
                dir: "%kernel.project_dir%/src/VillaBundle/Entity"
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
        dql:
            datetime_functions:
                date: Luxifer\DQL\Datetime\Date
                datediff: DoctrineExtensions\Query\Mysql\DateDiff
                date_format: Luxifer\DQL\Datetime\DateFormat
                hour: DoctrineExtensions\Query\Mysql\Hour
                ifnull: DoctrineExtensions\Query\Mysql\IfNull
                minute: DoctrineExtensions\Query\Mysql\Minute
                dayofweek: DoctrineExtensions\Query\Mysql\DayOfWeek
                now: DoctrineExtensions\Query\Mysql\Now
                time: Luxifer\DQL\Datetime\Time
                time_diff: DoctrineExtensions\Query\Mysql\TimeDiff
                time_to_sec: DoctrineExtensions\Query\Mysql\TimeToSec
                year: Luxifer\DQL\Datetime\Year
            string_functions:
                concat_ws: Luxifer\DQL\String\ConcatWs
                replace: DoctrineExtensions\Query\Mysql\Replace
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
            disabled:
                class: AppBundle\Doctrine\DisabledFilter
                enabled: true
            active:
                class: AppBundle\Doctrine\ActiveFilter
                enabled: false
            zichtbaar:
                class: AppBundle\Doctrine\ZichtbaarFilter
                enabled: true
            foutieve_invoer:
                class: IzBundle\Doctrine\FoutieveInvoerFilter
                enabled: true
            incidenten:
                class: AppBundle\Doctrine\IncidentenFilter
                enabled: false
            overleden:
                class: AppBundle\Doctrine\OverledenFilter
                enabled: false

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system

when@test:
    doctrine:
        dbal:
            connections:
                default:
                    use_savepoints: '%env(bool:DOCTRINE_USE_SAVEPOINTS)%'
