# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    base_path: "build/ckeditor"
    js_path: "build/ckeditor/ckeditor.js"
    autoload: true
    jquery: false
    default_config: basic
    input_sync: true
    configs:
        basic:
            versionCheck: false
            disableNativeSpellChecker: false
            removePlugins: 'liststyle,tabletools,tableselection,contextmenu'
            enterMode: CKEDITOR.ENTER_BR
            toolbar: [["Bold", "Italic", "Underline"]]
