fos_ck_editor:
  base_path: "build/ckeditor"
  js_path: "build/ckeditor/ckeditor.js"
  autoload: true
  jquery: false
  default_config: basic
  configs:
    basic:
      disableNativeSpellChecker: false
      removePlugins: 'liststyle,tabletools,tableselection,contextmenu'
      enterMode: CKEDITOR.ENTER_BR
      toolbar: [["Bold", "Italic", "Underline"]]
