# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    autoload: false
    jquery: true
    default_config: basic
    configs:
        basic:
            disableNativeSpellChecker: false
            removePlugins: 'liststyle,tabletools,tableselection,contextmenu'
            enterMode: CKEDITOR.ENTER_BR
            toolbar: [["Bold", "Italic", "Underline"]]
