framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        name: ECD
        cookie_lifetime: 0 # until the browser is closed
        gc_maxlifetime: 28800 # 8 hours
        save_path: '%kernel.project_dir%/var/sessions'

    #esi: true
    #fragments: true
    php_errors:
        log: true

    router:
#        resource: "%kernel.project_dir%/config/routes.yaml"
        strict_requirements: ~
    form: ~
    validation: { enable_annotations: true }
