framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    session:
        name: ECD
        cookie_lifetime: 0 # until the browser is closed
        gc_maxlifetime: 28800 # 8 hours
        save_path: '%kernel.root_dir%/../var/sessions'

    #esi: true
    #fragments: true
    php_errors:
        log: true

    router:
#        resource: "%kernel.root_dir%/config/routing.yaml"
        strict_requirements: ~
    form: ~
    validation: { enable_annotations: true }
