# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        name: ECD
        cookie_lifetime: 0 # until the browser is closed
        gc_maxlifetime: 28800 # 8 hours
        save_path: '%kernel.root_dir%/../var/sessions'

    ide: 'phpstorm://open?file=%%f&line=%%l&/var/www/html/>/Users/jtborger/Documents/webprojects/deregenboog/ecd/'
    #esi: true
    #fragments: true
#    templating:
#        engines:
#            - twig
    php_errors:
        log: true

