ldap_tools:
  general:
    cache_type: 'stash'
  domains:
    default:
      domain_name: '%ldap_domain%'
      port: '%ldap_port%'
      username: '%ldap_search_user%'
      password: '%ldap_search_password%'
      base_dn: '%ldap_base_dn%'
      servers: '%ldap_servers%'
      bind_format: '%%username%%'
      use_ssl: true
  security:
    user: AppBundle\Entity\Medewerker
    login_query_attribute: 'sAMAccountName'
    additional_attributes:
      - givenName
      - sn
      - mail
