ldap_tools:
    domains:
        default:
            domain_name: '%env(LDAP_DOMAIN)%'
            port: '%env(LDAP_PORT)%'
            username: '%env(LDAP_SEARCH_USER)%'
            password: '%env(LDAP_SEARCH_PASSWORD)%'
            base_dn: '%env(LDAP_BASE_DN)%'
            servers: '%env(LDAP_SERVERS)%'
            bind_format: '%%username%%'
            use_ssl: true
    security:
        user: AppBundle\Entity\Medewerker
        login_query_attribute: 'sAMAccountName'
        additional_attributes:
            - givenName
            - sn
            - mail
