when@dev: &dev
    nelmio_alice:
        functions_blacklist:
            - 'current'
            - 'shuffle'
            - 'date'
            - 'time'
            - 'file'
            - 'md5'
            - 'sha1'
        #locale: '%kernel.default_locale%'
        seed: 1
        loading_limit: 5
        max_unique_values_retry: 5

when@test: *dev
