when@dev: &dev
    services:
        AppBundle\Security\DevelopmentAuthenticator:
            arguments:
                - '%kernel.environment%'
                - '@router'
    security:
        firewalls:
            main:
                provider: chain_provider
                custom_authenticators:
                    - AppBundle\Security\DevelopmentAuthenticator
                entry_point: AppBundle\Security\DevelopmentAuthenticator

when@test: *dev

#when@prod:
#    security:
#        firewalls:
#            main:
#                authenticators:
#                    - ldap_tools.security.ldap_guard_authenticator

security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        AppBundle\Entity\Medewerker: plaintext
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        chain_provider:
            chain:
                providers: [database,ecd_ldap]
        database:
            entity:
                class: 'AppBundle\Entity\Medewerker'
                property: 'username'
        ecd_ldap:
            ldap:
                service: Symfony\Component\Ldap\Ldap
                base_dn: '%ldap_base_dn%'
                search_dn: "%ldap_search_user%"
                search_password: '%ldap_search_password%'
                default_roles: ROLE_USER
#                uid_key: 'username'
                extra_fields:
                    - givenName
                    - sn
                    - mail
                    - memberOf
                    - objectguid
                    - UserAccountControl
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
           #anonymous: ~
            # Here we use the chained provider defined previously...
            provider: chain_provider
            pattern: ^/
            logout: ~
            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user: { role: ROLE_ADMIN }
            form_login_ldap:
                service: Symfony\Component\Ldap\Ldap
#                provider: chain_provider
                dn_string: 'DEREGENBOOG\{username}'
                login_path: login
                check_path: login
        login:
           # anonymous: ~
            pattern: ^/login$

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/fc-load-events, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/klanten, roles: ROLE_TEAMLEIDERS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/incidenten, roles: ROLE_ADMIN }
        - { path: ^/medewerkers, roles: ROLE_USERADMIN }
        - { path: ^/download, roles: ROLE_GLOBALDOWNLOAD }
        - { path: ^/buurtboerderij, roles: ROLE_BUURTBOERDERIJ }
        - { path: ^/clip/admin, roles: ROLE_CLIP_BEHEER }
        - { path: ^/clip/vrijwilligers, roles: ROLE_CLIP_VRIJWILLIGERS }
        - { path: ^/clip/clienten, roles: ROLE_CLIP_ALLEEN_CLIENTEN }
        - { path: ^/clip, roles: ROLE_CLIP }
        - { path: ^/dagbesteding/admin, roles: ROLE_DAGBESTEDING_BEHEER }
        - { path: ^/dagbesteding, roles: ROLE_DAGBESTEDING }
        - { path: ^/eropuit/admin, roles: ROLE_EROPUIT_BEHEER }
        - { path: ^/eropuit, roles: ROLE_EROPUIT }
        - { path: ^/ga/admin, roles: ROLE_GA_BEHEER }
        - { path: ^/ga, roles: ROLE_GA }
        - { path: ^/hs/admin, roles: ROLE_HOMESERVICE_BEHEER }
        - { path: ^/hs, roles: ROLE_HOMESERVICE }
        - { path: ^/inloop/admin, roles: ROLE_INLOOP_BEHEER }
        - { path: ^/inloop/documenten, roles: ROLE_INLOOP_VRIJWILLIGERS }
        - { path: ^/inloop/intakes, roles: ROLE_INLOOP_INTAKES }
        - { path: ^/inloop/klanten, roles: ROLE_INLOOP_KLANTEN }
        - { path: ^/inloop/memos, roles: ROLE_INLOOP_KLANTEN }
        - { path: ^/inloop/opmerkingen, roles: ROLE_INLOOP_OPMERKINGEN }
        - { path: ^/inloop/rapportages, roles: ROLE_INLOOP_REPORTS }
        - { path: ^/inloop/registraties, roles: ROLE_INLOOP_REGISTRATIES }
        - { path: ^/inloop/schorsingen, roles: ROLE_INLOOP_SCHORSINGEN }
        - { path: ^/inloop/vrijwilligers, roles: ROLE_INLOOP_VRIJWILLIGERS }
        - { path: ^/inloop, roles: ROLE_INLOOP }
        - { path: ^/oekraine, roles: [ROLE_OEKRAINE] }
        - { path: ^/iz/admin, roles: ROLE_IZ_BEHEER }
        - { path: ^/iz, roles: ROLE_IZ }
        - { path: ^/mw/admin, roles: ROLE_MW_BEHEER }
        - { path: ^/mw, roles: ROLE_MW }
        - { path: ^/odp/admin, roles: ROLE_ODP_BEHEER }
        - { path: ^/odp, roles: ROLE_ODP }
        - { path: ^/tw/admin, roles: ROLE_TW_BEHEER }
        - { path: ^/tw, roles: ROLE_TW }
        - { path: ^/oek/admin, roles: ROLE_OEK_BEHEER }
        - { path: ^/oek, roles: ROLE_OEK }
        - { path: ^/pfo/admin, roles: ROLE_PFO_BEHEER }
        - { path: ^/pfo, roles: [ROLE_PFO, ROLE_PFO_BEPERKT] }
        - { path: ^/scip/admin, roles: ROLE_SCIP_BEHEER }
        - { path: ^/scip, roles: ROLE_SCIP }
        - { path: ^/uhk/admin, roles: ROLE_UHK_BEHEER }
        - { path: ^/uhk, roles: ROLE_UHK }
        - { path: ^/villa, roles: ROLE_VILLA }
        - { path: ^/, roles: CONTROLLER_ACCESS_VOTER }
