twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'templates/app': 'App'
        'templates/buurtboerderij': 'Buurtboerderij'
        'templates/clip': 'Clip'
        'templates/dagbesteding': 'Dagbesteding'
        'templates/eropuit': 'ErOpUit'
        'templates/ga': 'Ga'
        'templates/hs': 'Hs'
        'templates/inloop': 'Inloop'
        'templates/iz': 'Iz'
        'templates/mw': 'Mw'
        'templates/oek': 'Oek'
        'templates/oekraine': 'Oekraine'
        'templates/pfo': 'Pfo'
        'templates/scip': 'Scip'
        'templates/tw': 'Tw'
        'templates/uhk': 'Uhk'
        'templates/villa': 'Villa'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        # - form_div_layout.html.twig
        # - bootstrap_3_horizontal_layout.html.twig
        - form/app.html.twig
        - form/zrm.html.twig
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    cache: '%kernel.cache_dir%/twig'
    globals:
        app_version: '%application_version%'

when@test:
    twig:
        strict_variables: true
