twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes:
        #        - form_div_layout.html.twig
        #        - bootstrap_3_horizontal_layout.html.twig
        - form/app.html.twig
        - form/zrm.html.twig
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    cache: '%kernel.cache_dir%/twig'
    globals:
        app_version: '%application_version%'
