when@dev:
    web_profiler:
        toolbar: "%env(bool:ENABLE_PROFILER)%" #zie .env.dist
        intercept_redirects: false

    framework:
        profiler:
            only_exceptions: false
            collect: "%env(bool:ENABLE_PROFILER)%" #zie .env.dist
            enabled: true