services:
    MwBundle\Service\DossierStatusDao:
        parent: app.dao.abstract

    MwBundle\Service\AanmeldingDao:
        parent: app.dao.abstract

    MwBundle\Service\AfsluitingDao:
        parent: app.dao.abstract

    MwBundle\Service\DocumentDao:
        parent: app.dao.abstract

    MwBundle\Service\DoorverwijzingDao:
        parent: app.dao.abstract

    MwBundle\Service\InventarisatieDao:
        parent: app.dao.abstract

    MwBundle\Service\KlantDao:
        parent: app.dao.abstract

    MwBundle\Service\ProjectDao:
        parent: app.dao.abstract

    MwBundle\Service\TrajecthouderDao:
        parent: app.dao.abstract

    MwBundle\Service\VerslagDao:
        parent: app.dao.abstract

    MwBundle\Service\VrijwilligerDao:
        parent: app.dao.abstract

    MwBundle\Service\AfsluitredenKlantDao:
        parent: app.dao.abstract

    MwBundle\Service\AfsluitredenVrijwilligerDao:
        parent: app.dao.abstract

    MwBundle\Service\BinnenViaVrijwilligerDao:
        parent: app.dao.abstract

    MwBundle\Service\BinnenViaKlantDao:
        parent: app.dao.abstract

    MwBundle\Service\DeelnameDao:
        parent: app.dao.abstract

    MwBundle\Service\IntakeDao:
        parent: app.dao.abstract
        arguments:
            - '@event_dispatcher'
            - '@InloopBundle\Service\LocatieDao'

    mw.dossierstatus.entities:
        public: true
        class: ArrayObject
        arguments:
            -
                - { key: klant, dao: '@MwBundle\Service\KlantDao' }

    mw.memo.entities:
        public: true
        class: ArrayObject
        arguments:
            -
                - { key: vrijwilliger, dao: '@MwBundle\Service\VrijwilligerDao' }

    mw.deelname.entities:
        public: true
        class: ArrayObject
        arguments:
            -
                - { key: vrijwilliger, dao: '@MwBundle\Service\VrijwilligerDao' }

    mw.document.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: klant, dao: '@MwBundle\Service\KlantDao' }
              - { key: vrijwilliger, dao: '@MwBundle\Service\VrijwilligerDao' }
