services:
    mw.export.klanten:
        class: AppBundle\Export\GenericExport
        arguments:
            - array
            -
                Nummer: { expression: 'entity[0].getId()' }
                Geslacht: { expression: 'entity[0].getGeslacht()' }
                Voornaam: { expression: 'entity[0].getVoornaam()' }
                Tussenvoegsel: { expression: 'entity[0].getTussenvoegsel()' }
                Achternaam: { expression: 'entity[0].getAchternaam()' }
                Geboortedatum: { expression: 'entity[0].getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity[0].getEmail()' }
                Adres: { expression: 'entity[0].getAdres()' }
                Postcode: { expression: 'entity[0].getPostcode()' }
                Woonplaats: { expression: 'entity[0].getPlaats()' }
                Mobiel: { expression: 'entity[0].getMobiel()' }
                Telefoon: { expression: 'entity[0].getTelefoon()' }
                Werkgebied: { expression: 'entity[0].getWerkgebied()' }
                Geen post: { expression: 'entity[0].getGeenPost() ? "ja" : "nee"' }
                Geen e-mail: { expression: 'entity[0].getGeenEmail() ? "ja" : "nee"' }

    mw.export.report:
        class: AppBundle\Export\ReportExport
