services:
    MwBundle\Form\RapportageType:
        tags:
            - { name: form.type }

    MwBundle\Report\Inventarisaties:
        public: true
        arguments:
            - '@MwBundle\Service\InventarisatieDao'
        tags:
            - { name: mw.rapportage, category: Inventarisaties }

    MwBundle\Report\RepatrieringenPerLand:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: mw.rapportage, category: Repatriëring }

    MwBundle\Report\RepatrieringenPerKlant:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.root_dir%/config/repatrieringen_per_klant.sql"
        tags:
            - { name: mw.rapportage, category: Repatriëring }