services:
    MwBundle\Form\RapportageType:
        tags:
            - { name: form.type }

    MwBundle\Report\Inventarisaties:
        public: true
        arguments:
            - '@MwBundle\Service\InventarisatieDao'
        tags:
            - { name: mw.rapportage, category: Inventarisaties }

    MwBundle\Report\EconomischDaklozen:
        public: true
        arguments:
            - '@MwBundle\Service\VerslagDao'
            - '%economisch_daklozen_locaties%'
        tags:
            - { name: mw.rapportage, category: Klanten }

    MwBundle\Report\ZonderZorg:
        public: true
        arguments:
            - '@MwBundle\Service\VerslagDao'
            - '%zonderzorg_locaties%'
        tags:
            - { name: mw.rapportage, category: Klanten }

    MwBundle\Report\AMW:
        public: true
        arguments:
            $dao: '@MwBundle\Service\VerslagDao'
            $locatieDao: '@InloopBundle\Service\LocatieDao'
            $klantDao: '@MwBundle\Service\KlantDao'
            $amw_locaties: '%amw_locaties%'
        tags:
            - { name: mw.rapportage, category: Klanten }

#    MwBundle\Report\Resultaten:
#        public: true
#        arguments:
#            - '@MwBundle\Service\KlantDao'
#        tags:
#            - { name: mw.rapportage, category: Klanten }

    MwBundle\Report\RepatrieringenPerLand:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: mw.rapportage, category: Repatriëring }

    MwBundle\Report\RepatrieringenPerKlant:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.project_dir%/config/sql_reports/repatrieringen_per_klant.sql"
        tags:
            - { name: mw.rapportage, category: Repatriëring }

    MwBundle\Report\RepatrieringenPerInloopKlant:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.project_dir%/config/sql_reports/repatrieringen_per_inloopklant.sql"
        tags:
            - { name: mw.rapportage, category: Repatriëring }