imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    MwBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    MwBundle\Event\DienstenLookupSubscriber:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }
