imports:
    - { resource: daos.yml }
    - { resource: exports.yml }
    - { resource: reports.yml }

services:
    #tbv controller DI named arguments die dan niet eerst hoeven;
    _defaults:
        autowire: true
        autoconfigure: true

    MwBundle\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    MwBundle\Controller\IntakesController:
        arguments:
            $tbc_countries: '%tbc_countries%'
        tags: [ 'controller.service_arguments' ]

    MwBundle\Controller\DeelnamesController:
        arguments:
            $entities: '@mw.deelname.entities'
        tags: [ 'controller.service_arguments' ]

    MwBundle\Controller\DocumentenController:
        arguments:
            $entities: '@mw.document.entities'
        tags: [ 'controller.service_arguments' ]

    MwBundle\Controller\KlantenController:
        arguments:
            $export: '@mw.export.klanten'
        tags: [ 'controller.service_arguments' ]

    MwBundle\Controller\MemosController:
        arguments:
            $entities: '@mw.memo.entities'
        tags: [ 'controller.service_arguments' ]

    MwBundle\Controller\RapportagesController:
        arguments:
            $export: '@mw.export.report'
        tags: [ 'controller.service_arguments' ]

    MwBundle\Controller\VerslagenController:
        arguments:
            $export: '@mw.export.klanten'
        tags: [ 'controller.service_arguments' ]

    MwBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@mw.export.vrijwilliger'
        tags: [ 'controller.service_arguments' ]

    MwBundle\Event\DienstenLookupSubscriber:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    verslag_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - MwBundle\Entity\Verslag

    MwBundle\Repository\VerslagRepository:
        class: MwBundle\Repository\VerslagRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@verslag_metadata"
        calls:
            - method: setGezinNoodopvangLocaties
              arguments:
                  - "%gezin_noodopvang_locaties%"
        tags:
            - app.doelstelling
        public: true

    MwBundle\Form\IntakeFilterType:
        class: MwBundle\Form\IntakeFilterType
        arguments:
            - '@InloopBundle\Service\LocatieDao'
        tags:
            - { name: form.type, alias: 'container_aware' }

    klant_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - AppBundle\Entity\Klant

    klantinfo_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - MwBundle\Entity\Info

    MwBundle\Repository\KlantRepository:
        class: MwBundle\Repository\KlantRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@klant_metadata"
        calls:
            - method: setEconomischDaklozenLocaties
              arguments:
                  - "%economisch_daklozen_locaties%"
        tags:
            - app.doelstelling
        public: true

    MwBundle\Repository\KlantInfoRepository:
        class: MwBundle\Repository\KlantInfoRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@klantinfo_metadata"
        calls:
            - method: setEconomischDaklozenLocaties
              arguments:
                  - "%economisch_daklozen_locaties%"
        tags:
            - app.doelstelling
        public: true
