services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    TwBundle\Service\:
        resource: '%kernel.project_dir%/src/TwBundle/Service/'

    tw.memo.entities:
        class: ArrayObject
        arguments:
            - - { key: vrijwilliger, dao: '@TwBundle\Service\VrijwilligerDao' }

    tw.deelname.entities:
        class: ArrayObject
        arguments:
            - - { key: vrijwilliger, dao: '@TwBundle\Service\VrijwilligerDao' }
