services:
    _defaults:
        autowire: true
        autoconfigure: true

    tw.export.klanten:
        class: AppBundle\Export\GenericExport
        arguments:
            - TwBundle\Entity\Klant
            -
                Nummer: { expression: 'entity.getAppKlant().getId()' }
                Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Geslacht: { expression: 'entity.getAppKlant().getGeslacht()' }
                Voornaam: { expression: 'entity.getAppKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getAppKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getAppKlant().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getAppKlant().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getAppKlant().getEmail()' }
                Adres: { expression: 'entity.getAppKlant().getAdres()' }
                Postcode: { expression: 'entity.getAppKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getAppKlant().getPlaats()' }
                Mobiel: { expression: 'entity.getAppKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getAppKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getAppKlant().getWerkgebied()' }
                Project(en): { expression: 'entity.getProjecten()' }
#                WPI: { expression: 'entity.isWpi() ? "ja" : "nee"' }
#                Automatische incasso: { expression: 'entity.isAutomatischeIncasso() ? "ja" : "nee"' }
#                Inschrijving Woningnet: { expression: 'entity.isInschrijvingWoningnet() ? "ja" : "nee"' }
                WA-polis: { expression: 'entity.isWaPolis() ? "ja" : "nee"' }
                Postvoorkeur: { expression: 'entity.getAppKlant().getGeenPost() ? "Geen post" : "Wel post"' }
                E-mailvoorkeur: { expression: 'entity.getAppKlant().getGeenEmail() ? "Geen e-mail" : "Wel e-mail"' }
                Is gekoppeld: { expression: 'entity.isGekoppeld() ? "Ja" : "Nee"' }

    tw.export.verhuurders:
        class: AppBundle\Export\GenericExport
        arguments:
            - TwBundle\Entity\Verhuurder
            -
                Nummer: { expression: 'entity.getAppKlant().getId()' }
                Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Geslacht: { expression: 'entity.getAppKlant().getGeslacht()' }
                Voornaam: { expression: 'entity.getAppKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getAppKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getAppKlant().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getAppKlant().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getAppKlant().getEmail()' }
                Adres: { expression: 'entity.getAppKlant().getAdres()' }
                Postcode: { expression: 'entity.getAppKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getAppKlant().getPlaats()' }
                Mobiel: { expression: 'entity.getAppKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getAppKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getAppKlant().getWerkgebied()' }
                Project: { expression: 'entity.getProject()' }
                WPI: { expression: 'entity.isWpi() ? "ja" : "nee"' }
                Postvoorkeur: { expression: 'entity.getAppKlant().getGeenPost() ? "Geen post" : "Wel post"' }
                E-mailvoorkeur: { expression: 'entity.getAppKlant().getGeenEmail() ? "Geen e-mail" : "Wel e-mail"' }
                Is gekoppeld: { expression: 'entity.isGekoppeld() ? "Ja" : "Nee"' }

    tw.export.huurverzoeken:
        class: AppBundle\Export\GenericExport
        arguments:
            - TwBundle\Entity\Huurverzoek
            -
                Nummer: { expression: 'entity.getId()' }
                Klant: { expression: 'entity.getKlant()' }
                Stadsdeel: { expression: 'entity.getKlant().getAppKlant().getWerkgebied()' }
                Project(en): { expression: 'entity.getProjecten()' }
                Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }

    tw.export.huuraanbiedingen:
        class: AppBundle\Export\GenericExport
        arguments:
            - TwBundle\Entity\Huuraanbod
            -
                Nummer: { expression: 'entity.getId()' }
                Verhuurder: { expression: 'entity.getVerhuurder()' }
                Stadsdeel: { expression: 'entity.getVerhuurder().getAppKlant().getWerkgebied()' }
                Project: { expression: 'entity.getProject()' }
                Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }

    tw.export.koppelingen:
        class: AppBundle\Export\GenericExport
        arguments:
            - TwBundle\Entity\Huurovereenkomst
            -
                Nummer: { expression: 'entity.getId()' }
                Klant: { expression: 'entity.getKlant()' }
                Emailadres Klant: { expression: 'entity.getKlant().getAppKlant().getEmail()' }
                Voornaam: { expression: 'entity.getKlant().getAppKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getKlant().getAppKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getKlant().getAppKlant().getAchternaam()' }
                Project: { expression: 'entity.getHuuraanbod().getProject()' }
                Medewerker: { expression: 'entity.getMedewerker()' }
                Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
                Opzegdatum: { expression: 'entity.getOpzegdatum()', type: 'date' }
                Einddatum: { expression: 'entity.getEinddatum()', type: 'date' }
                Plaats: { expression: 'entity.getVerhuurder().getAppKlant().getPlaats()' }
                Vorm: { expression: 'entity.getVormVanOvereenkomst()' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Afsluitreden: { expression: 'entity.getAfsluiting()' }
                Automatische incasso: { expression: 'entity.getKlant().isAutomatischeIncasso() ? "ja" : "nee"' }
#                Inschrijving Woningnet: { expression: 'entity.getKlant().isInschrijvingWoningnet() ? "ja" : "nee"' }
                WA-polis: { expression: 'entity.getKlant().isWaPolis() ? "ja" : "nee"' }

    tw.export.vrijwilliger:
        class: AppBundle\Export\GenericExport
        arguments:
            - TwBundle\Entity\Vrijwilliger
            -
                Rubriek: { expression: '"TwVrijwilliger"' }
                Nummer: { expression: 'entity.getVrijwilliger().getId()' }
                Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
                Startdatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Geslacht: { expression: 'entity.getVrijwilliger().getGeslacht()' }
                Voornaam: { expression: 'entity.getVrijwilliger().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getVrijwilliger().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getVrijwilliger().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getVrijwilliger().getGeboortedatum()', type: 'date' }
                Adres: { expression: 'entity.getVrijwilliger().getAdres()' }
                Postcode: { expression: 'entity.getVrijwilliger().getPostcode()' }
                Woonplaats: { expression: 'entity.getVrijwilliger().getPlaats()' }
                E-mail: { expression: 'entity.getVrijwilliger().getEmail()' }
                Mobiel: { expression: 'entity.getVrijwilliger().getMobiel()' }
                Telefoon: { expression: 'entity.getVrijwilliger().getTelefoon()' }
                Werkgebied: { expression: 'entity.getVrijwilliger().getWerkgebied()' }
                GGW-gebied: { expression: 'entity.getVrijwilliger().getPostcodegebied()' }
                Stagiair: { expression: 'entity.isStagiair()' }
                Postvoorkeur: { expression: 'entity.getVrijwilliger().getGeenPost()==false?"Post":"Geen Post"' }
                Emailvoorkeur: { expression: 'entity.getVrijwilliger().getGeenEmail()==false?"Email":"Geen Email"' }
                Medewerker Intake: { expression: 'entity.getMedewerker()' }
                Medewerker Locatie: { expression: 'entity.getMedewerkerLocatie()' }
                Binnengekomen via: { expression: 'entity.getBinnenVia()' }
                Locaties: { expression: 'entity.getLocaties()' }
                VOG aangevraagd: { expression: 'entity.getVrijwilliger().getVogAangevraagd()' }
                VOG aanwezig: { expression: 'entity.getVrijwilliger().getVogAanwezig()' }
                Overeenkomst aanwezig: { expression: 'entity.getVrijwilliger().getOvereenkomstAanwezig()' }

    tw.export.vrijwilligersdownload:
        class: AppBundle\Export\GenericExport
        arguments:
            - TwBundle\Entity\Vrijwilliger
            -
                Rubriek: { expression: '"TijdelijkWonenVrijwilliger"'}
                Nummer: { expression: 'entity.getVrijwilliger().getId()' }
                Startdatum: { expression: 'entity.getAanmelddatum()', condition: 'entity.getAanmelddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Geslacht: { expression: 'entity.getVrijwilliger().getGeslacht()' }
                Voornaam: { expression: 'entity.getVrijwilliger().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getVrijwilliger().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getVrijwilliger().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getVrijwilliger().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getVrijwilliger().getEmail()' }
                Adres: { expression: 'entity.getVrijwilliger().getAdres()' }
                Postcode: { expression: 'entity.getVrijwilliger().getPostcode()' }
                Woonplaats: { expression: 'entity.getVrijwilliger().getPlaats()' }
                Werkgebied: { expression: 'entity.getVrijwilliger().getWerkgebied()' }
                Postvoorkeur: { expression: 'entity.getVrijwilliger().getGeenPost()==false?"Post":"Geen Post"' }
                Emailvoorkeur: { expression: 'entity.getVrijwilliger().getGeenEmail()==false?"Email":"Geen Email"' }
            - 'Vrijwilligers TW'
            - '@TwBundle\Service\VrijwilligerDao'
        tags:
            - { name: app.downloads }

    tw.export.report:
        class: AppBundle\Export\ReportExport
