services:
    _defaults:
        autowire: true
        autoconfigure: true

    TwBundle\Form\RapportageType:

    TwBundle\Report\Afsluitingen:
        arguments:
            - '@TwBundle\Service\HuurovereenkomstAfsluitingDao'
        tags:
            - { name: tw.rapportage }

    TwBundle\Report\Huurders:
        arguments:
            - '@TwBundle\Service\KlantDao'
        tags:
            - { name: tw.rapportage }

    TwBundle\Report\Koppelingen:
        arguments:
            - '@TwBundle\Service\HuurovereenkomstDao'
            - '@TwBundle\Service\ProjectDao'
        tags:
            - { name: tw.rapportage }

    TwBundle\Report\Verhuurders:
        arguments:
            - '@TwBundle\Service\VerhuurderDao'
        tags:
            - { name: tw.rapportage }

    TwBundle\Report\Incidenten:
        tags:
            - { name: tw.rapportage }
