imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    TwBundle\Controller\:
        resource: '%kernel.project_dir%/src/TwBundle/Controller'

    TwBundle\Controller\DeelnamesController:
        arguments:
            $entities: '@tw.deelname.entities'

    TwBundle\Controller\HuurovereenkomstenController:
        arguments:
            $export: '@tw.export.koppelingen'

    TwBundle\Controller\HuuraanbiedingenController:
        arguments:
            $export: '@tw.export.huuraanbiedingen'

    TwBundle\Controller\KlantenController:
        arguments:
            $export: '@tw.export.klanten'

    TwBundle\Controller\MemosController:
        arguments:
            $entities: '@tw.memo.entities'

    TwBundle\Controller\RapportagesController:
        arguments:
            $export: '@tw.export.report'
            $reports: !tagged_iterator tw.rapportage

    TwBundle\Controller\VerhuurdersController:
        arguments:
            $export: '@tw.export.verhuurders'

    TwBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@tw.export.vrijwilliger'

    TwBundle\Event\DienstenLookupSubscriber:

    TwBundle\Form\KlantFilterType:

    TwBundle\Security\DocumentVoter:
        arguments:
            - "@security.access.decision_manager"

when@dev: &dev
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        TwBundle\DataFixtures\TwFakerProvider:

when@test: *dev
