services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    DagbestedingBundle\Service\:
        resource: '%kernel.project_dir%/src/DagbestedingBundle/Service/'
