services:
    _defaults:
        autowire: true
        autoconfigure: true

    DagbestedingBundle\Form\RapportageType:

    DagbestedingBundle\Report\Activering:
        arguments:
            $sqlFile: "%kernel.project_dir%/config/sql_reports/activering_reports.sql"
        tags:
            - { name: dagbesteding.rapportage, category: Activering }

    DagbestedingBundle\Report\DagdelenPerDeelnemer:
        arguments:
            - '@DagbestedingBundle\Service\DagdeelDao'
        tags:
            - { name: dagbesteding.rapportage, category: Dagdelen }

    DagbestedingBundle\Report\VerlengingenPerTrajectcoach:
        arguments:
            - '@DagbestedingBundle\Service\TrajectDao'
        tags:
            - { name: dagbesteding.rapportage, category: Trajecten }

    DagbestedingBundle\Report\DeelnemersPerBegeleider:
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    DagbestedingBundle\Report\DeelnemersPerLocatie:
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    DagbestedingBundle\Report\DeelnemersPerProject:
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    DagbestedingBundle\Report\DeelnemersPerResultaatgebiedsoort:
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    DagbestedingBundle\Report\DeelnemersZonderVOG:
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    DagbestedingBundle\Report\DeelnemersZonderToestemmingsformulier:
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    DagbestedingBundle\Report\TrajectenPerAfsluiting:
        arguments:
            - '@DagbestedingBundle\Service\TrajectDao'
        tags:
            - { name: dagbesteding.rapportage, category: Trajecten }
