imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    DagbestedingBundle\Command\:
        resource: '%kernel.project_dir%/src/DagbestedingBundle/Command'
        exclude:
            - '%kernel.project_dir%/src/DagbestedingBundle/Command/MigrateCommand.php'

    DagbestedingBundle\Controller\:
        resource: '%kernel.project_dir%/src/DagbestedingBundle/Controller'

    DagbestedingBundle\Controller\ContactpersonenController:
        arguments:
            $entities: '@dagbesteding.contactpersoon.entities'

    DagbestedingBundle\Controller\DagdelenController:
        arguments:
            $export: '@dagbesteding.export.dagdelen'

    DagbestedingBundle\Controller\DashboardController:
        arguments:
            $trajectenExport: '@dagbesteding.export.trajecten'

    DagbestedingBundle\Controller\DeelnamesController:
        arguments:
            $entities: '@dagbesteding.deelname.entities'
            $export: '@dagbesteding.export.deelnames'

    DagbestedingBundle\Controller\DeelnemersController:
        arguments:
            $export: '@dagbesteding.export.deelnemers'

    DagbestedingBundle\Controller\DocumentenController:
        arguments:
            $entities: '@dagbesteding.document.entities'

    DagbestedingBundle\Controller\RapportagesController:
        arguments:
            $entities: '@dagbesteding.rapportage.entities'

    DagbestedingBundle\Controller\ReportingController:
        arguments:
            $export: '@dagbesteding.export.report'
            $reports: !tagged_iterator dagbesteding.rapportage

    DagbestedingBundle\Controller\TrajectenController:
        arguments:
            $entities: '@dagbesteding.traject.entities'
            $export: '@dagbesteding.export.trajecten'

    DagbestedingBundle\Controller\VerslagenController:
        arguments:
            $entities: '@dagbesteding.verslag.entities'

    DagbestedingBundle\Controller\IntakeverslagenController:
        arguments:
            $entities: '@dagbesteding.verslag.entities'

    DagbestedingBundle\Controller\EvaluatieverslagenController:
        arguments:
            $entities: '@dagbesteding.verslag.entities'

    DagbestedingBundle\Controller\WerkdoelenController:
        arguments:
            $entities: '@dagbesteding.werkdoel.entities'

    dagbesteding.contactpersoon.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }

    dagbesteding.dagdeel.entities:
        class: ArrayObject
        arguments:
            -
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }

    dagbesteding.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }
              - { key: rapportage, dao: '@DagbestedingBundle\Service\RapportageDao' }

    dagbesteding.traject.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }

    dagbesteding.deelname.entities:
        class: ArrayObject
        arguments:
            - - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }
              - { key: project, dao: '@DagbestedingBundle\Service\ProjectDao' }

    dagbesteding.werkdoel.entities:
        class: ArrayObject
        arguments:
            - - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }


    dagbesteding.rapportage.entities:
        class: ArrayObject
        arguments:
            -
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }

    dagbesteding.verslag.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }

    DagbestedingBundle\Event\DienstenLookupSubscriber:

    DagbestedingBundle\Event\GeenActiveringSubscriber:
