language: php

php:
  - 7.1

env:
  - DB=sqlite

before_script:
  - sudo locale-gen nl_NL.UTF-8 && sudo update-locale
  - echo 'memory_limit=2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --no-scripts
  - cp app/config/parameters.yml.dist app/config/parameters.yml

script: travis_wait 30 ant
