language: php

php:
  - 7.2.25

env:
  - DB=sqlite

before_script:
  - sudo locale-gen nl_NL.UTF-8 && sudo update-locale
  - echo 'memory_limit=4G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer update
  - composer install --no-scripts
  - if find src/ -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
  - if find tests/ -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi

script:
  - php bin/console lint:twig src/
  - php bin/console lint:yaml src/
  - vendor/bin/phpcpd --min-lines=75 src/ || true
  - vendor/bin/simple-phpunit
