language: php

php:
  - 7.2.25

env:
  - DB=sqlite

before_install:
#  - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.6-bin.tar.gz
#  - tar -xzvf apache-ant-1.10.6-bin.tar.gz
#  - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH
#  - echo $(ant -version)


before_script:
  - sudo locale-gen nl_NL.UTF-8 && sudo update-locale
#  - sudo apt-get install ant
  - echo 'memory_limit=4G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer update
  - composer install --no-scripts
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - if find src/ -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
  - if find tests/ -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
  - phpunit --version

script:
  - php bin/console lint:twig src/
  - php bin/console lint:yaml src/
  - vendor/bin/phpcpd --quiet --min-lines=75 src/ || true
  - vendor/bin/phpunit --configuration phpunit.xml.dist tests/
#  - travis_wait 40 ant
