#Docker image for container to run tests on.
FROM php:7.4

ENV APP_ENV=test

COPY docker/php.ini /usr/local/etc/php/

COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer
COPY composer.json composer.lock ./

RUN apt-get update && apt-get install -y \
    default-mysql-client \
    g++ \
    libfreetype6-dev \
    libicu-dev \
    libldap2-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libzip-dev \
    locales \
    zlib1g-dev \

&& docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu \
    && docker-php-ext-configure gd --with-freetype=/usr/include/ --with-jpeg=/usr/include/ \
    && docker-php-ext-install gd intl ldap mysqli pdo_mysql zip \

# set timezone
&& echo "Europe/Amsterdam" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata \

# install locale
&& echo "nl_NL.UTF-8 UTF-8" > /etc/locale.gen \
&& locale-gen

WORKDIR /app
#first do composer so we can prevent compser installing each time we modify sourcecode.... adds extra layer.
COPY ./composer.json composer.json
COPY ./composer.lock composer.lock

COPY docker/.env.test .env
RUN COMPOSER_ALLOW_SUPERUSER=1 composer install --no-autoloader --no-scripts
COPY . .

RUN  composer install

ENTRYPOINT [ "php" ]
