version: '3.9'

services:
  test-database:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ${PWD}/build:/app/build
      - ${PWD}/src:/app/src:ro
      - ${PWD}/tests:/app/tests:ro
      - ${PWD}/templates:/app/templates:ro
