version: '2'

services:
  database:
    image: ecd_database:latest
  web:
    build: .
    links:
      - database
    ports:
      - "80:80"
    volumes:
      - "ecd-sync:/var/www/html:nocopy"
    environment:
      MYSQL_DATABASE: ecd
      MYSQL_USER: ecd
      MYSQL_PASSWORD: ecd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "81:80"
    links:
      - database
    environment:
      PMA_HOST: database
volumes:
  ecd-sync:
    external: true
