version: '3.9'

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - ${PWD}/public:/var/www/html/public
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - ${PWD}/.env.local:/var/www/html/.env.local #mount so you can adapt .env variables w/o rebuilding.
      - ${PWD}/app:/var/www/html/app
      - ${PWD}/config:/var/www/html/config
      - ${PWD}/public:/var/www/html/public
      - ${PWD}/src:/var/www/html/src
      - ${PWD}/bin:/var/www/html/bin
      - ${PWD}/templates:/var/www/html/templates
      - ${PWD}/translations:/var/www/html/translations
  node:
    image: node
    volumes:
      - ${PWD}/public:/var/www/html/public
    working_dir: /var/www/html/public
    command: npm install && yarn encode dev watch
  database:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 81:80
    environment:
      PMA_HOST: database
