version: '3.9'

services:
  test-database:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      MYSQL_DATABASE: ecd
      MYSQL_USER: ecd
      MYSQL_PASSWORD: ecd
