version: '3.9'

services:
  database:
    build:
      context: docker/mysql
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ${PWD}/docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/public:/var/www/html/public

  fpm:
    build: .
#    image: php:fpm
#    ports:
#      - 8081:80
    volumes:
      - ${PWD}/app:/var/www/html/app
      - ${PWD}/archive:/var/www/html/archive
#      - ${PWD}/docker:/var/www/html/docker
      - ${PWD}/config:/var/www/html/config
      - ${PWD}/src:/var/www/html/src
      - ${PWD}/templates:/var/www/html/templates
  #      - ${PWD}/tests:/var/www/html/tests
  #      - ${PWD}:/var/www/html #alles, handig ovor testen of debuggen maar hoeft niet.

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 81:80
    environment:
      PMA_HOST: database
