version: '2'

services:
  database:
    image: ecd_database:latest
  web:
    build: .
    links:
      - database
    ports:
      - "80:80"
    volumes:
      - "ecd-sync:/var/www/html:nocopy"
    environment:
      MYSQL_DATABASE: ecd
      MYSQL_USER: ecd
      MYSQL_PASSWORD: ecd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "81:80"
    links:
      - database
    environment:
      PMA_HOST: database

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
volumes:
  ecd-sync:
    external: true

###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
