version: '2'

services:
  web:
    container_name: ecd-web
    build: .
    links:
      - database
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html"
  database:
    container_name: ecd-database
    image: mysql:5.5
    ports:
      - "3306:3306"
    volumes:
      - "./app/sql:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: ecd
      MYSQL_DATABASE: ecd
      MYSQL_USER: ecd
      MYSQL_PASSWORD: ecd
  phpmyadmin:
    container_name: ecd-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "81:80"
    links:
      - database
    environment:
      PMA_HOST: database
