version: '3.9'

services:
  database:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - ${PWD}:/var/www/html
    environment:
      MYSQL_DATABASE: ecd
      MYSQL_USER: ecd
      MYSQL_PASSWORD: ecd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 81:80
    environment:
      PMA_HOST: database

