version: '3.9'

services:
  test-database:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ${PWD}/build:/app/build
      - ${PWD}/src:/var/www/html/src:ro
      - ${PWD}/tests:/var/www/html/tests:ro
