services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ${PWD}/public:/var/www/html/public
    depends_on:
      - php
  php:
    build:
      dockerfile: docker/php/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tmpfs:
      - /var/www/html/var/cache:noexec,nosuid,size=250M,uid=33,gid=33
      - /var/www/html/var/log:noexec,nosuid,size=500M,uid=33,gid=33
    volumes: #op macos alles via mutagen ivm snelheid.
      - ${PWD}/.env.local:/var/www/html/.env.local #mount so you can adapt .env variables w/o rebuilding.
      # See .env.dist for platform specific volume mounts
      - ${DOCKER_VOLUME_MOUNT:-/dev/null:/tmp/dummy}
    ports:
      - "9000:9000"  # Fast pool dmv d chrome xdebug helper.
      - "9001:9001"  # Debug pool met xdebug geladen
  node:
    image: node
    volumes:
      - ${PWD}:/var/www/html
    working_dir: /var/www/html
    command:
      - /bin/sh
      - -c
      - |
        npm install
        yarn encore dev --watch
  database:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    ports:
      - 3307:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 81:80
    environment:
      PMA_HOST: database