services:
  test-database:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      PANTHER_ERROR_SCREENSHOT_DIR: ./.panther/screenshots
    volumes:
      - ${PWD}/.panther/screenshots:/app/.panther/screenshots
      - ${PWD}/build:/app/build
      - ${PWD}/src:/app/src:ro
      - ${PWD}/templates:/app/templates:ro
      - ${PWD}/tests:/app/tests:ro
