services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    VillaBundle\Service\:
        resource: '%kernel.project_dir%/src/VillaBundle/Service/'

    villa.deelname.entities:
        class: ArrayObject
        arguments:
            - - { key: vrijwilliger, dao: '@VillaBundle\Service\VrijwilligerDao' }
