services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    VillaBundle\Service\:
        resource: '%kernel.project_dir%/src/VillaBundle/Service/'


