services:
    VillaBundle\Service\DocumentDao:
        parent: app.dao.abstract

    VillaBundle\Service\AfsluitredenDao:
        parent: app.dao.abstract

    VillaBundle\Service\BinnenViaDao:
        parent: app.dao.abstract

    VillaBundle\Service\DeelnameDao:
        parent: app.dao.abstract

    VillaBundle\Service\VrijwilligerDao:
        parent: app.dao.abstract

    VillaBundle\Service\KlantDao:
        parent: app.dao.abstract

    villa.memo.entities:
        public: true
        class: ArrayObject
        arguments:
            - - { key: vrijwilliger, dao: '@VillaBundle\Service\VrijwilligerDao' }
              -
    villa.deelname.entities:
        public: true
        class: ArrayObject
        arguments:
            - - { key: vrijwilliger, dao: '@VillaBundle\Service\VrijwilligerDao' }
