services:
    _defaults:
        autowire: true
        autoconfigure: true

    villa.export.vrijwilliger:
        class: AppBundle\Export\GenericExport
        arguments:
            - VillaBundle\Entity\Vrijwilliger
            - Nummer: { expression: 'entity.getVrijwilliger().getId()' }
              Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
              Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
              Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
              Geslacht: { expression: 'entity.getVrijwilliger().getGeslacht()' }
              Voornaam: { expression: 'entity.getVrijwilliger().getVoornaam()' }
              Tussenvoegsel: { expression: 'entity.getVrijwilliger().getTussenvoegsel()' }
              Achternaam: { expression: 'entity.getVrijwilliger().getAchternaam()' }
              Geboortedatum: { expression: 'entity.getVrijwilliger().getGeboortedatum()', type: 'date' }
              Adres: { expression: 'entity.getVrijwilliger().getAdres()' }
              Postcode: { expression: 'entity.getVrijwilliger().getPostcode()' }
              Woonplaats: { expression: 'entity.getVrijwilliger().getPlaats()' }
              E-mail: { expression: 'entity.getVrijwilliger().getEmail()' }
              Mobiel: { expression: 'entity.getVrijwilliger().getMobiel()' }
              Telefoon: { expression: 'entity.getVrijwilliger().getTelefoon()' }
              Werkgebied: { expression: 'entity.getVrijwilliger().getWerkgebied()' }
              GGW-gebied: { expression: 'entity.getVrijwilliger().getPostcodegebied()' }
              Stagiair: { expression: 'entity.isStagiair()' }
              Postvoorkeur: { expression: 'entity.getVrijwilliger().getGeenPost()==false?"Post":"Geen Post"' }
              Emailvoorkeur: { expression: 'entity.getVrijwilliger().getGeenEmail()==false?"Email":"Geen Email"' }
              Medewerker Intake: { expression: 'entity.getMedewerker()' }
              Medewerker Locatie: { expression: 'entity.getMedewerkerLocatie()' }
              Binnengekomen via: { expression: 'entity.getBinnenVia()' }
              VOG aangevraagd: { expression: 'entity.getVrijwilliger().getVogAangevraagd()' }
              VOG aanwezig: { expression: 'entity.getVrijwilliger().getVogAanwezig()' }
              Overeenkomst aanwezig: { expression: 'entity.getVrijwilliger().getOvereenkomstAanwezig()' }

    villa.export.slaper:
      class: AppBundle\Export\GenericExport
      arguments:
        - VillaBundle\Entity\Slaper
        - Nummer: { expression: 'entity.getAppKlant().getId()' }


    villa.export.report:
        class: AppBundle\Export\ReportExport
