imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    VillaBundle\Controller\:
        resource: '%kernel.project_dir%/src/VillaBundle/Controller'

    VillaBundle\Controller\DeelnamesController:
        arguments:
            $entities: '@villa.deelname.entities'

    VillaBundle\Controller\DocumentenController:
        arguments:
            $entities: '@villa.document.entities'

    VillaBundle\Controller\OvernachtingenController:
        arguments:
            $entities: '@villa.overnachting.entities'

    VillaBundle\Controller\MemosController:
        arguments:
            $entities: '@villa.memo.entities'

    VillaBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@villa.export.vrijwilliger'

    VillaBundle\Controller\SlapersController:
        arguments:
            $export: '@villa.export.slaper'


    villa.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: vrijwilliger, dao: '@VillaBundle\Service\VrijwilligerDao' }

    villa.overnachting.entities:
        class: ArrayObject
        arguments:
            -
                - { key: slaper, dao: '@VillaBundle\Service\SlaperDao' }

    villa.deelname.entities:
        class: ArrayObject
        arguments:
            - - { key: vrijwilliger, dao: '@VillaBundle\Service\VrijwilligerDao' }

    villa.memo.entities:
        class: ArrayObject
        arguments:
            - - { key: vrijwilliger, dao: '@VillaBundle\Service\VrijwilligerDao' }

    VillaBundle\Event\CalendarSubscriber: