services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    MwBundle\Service\:
        resource: '%kernel.project_dir%/src/MwBundle/Service/*'

    mw.memo.entities:
        class: ArrayObject
        arguments:
            -
                - { key: vrijwilliger, dao: '@MwBundle\Service\VrijwilligerDao' }

    mw.deelname.entities:
        class: ArrayObject
        arguments:
            -
                - { key: vrijwilliger, dao: '@MwBundle\Service\VrijwilligerDao' }

    mw.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: klant, dao: '@MwBundle\Service\KlantDao' }
              - { key: vrijwilliger, dao: '@MwBundle\Service\VrijwilligerDao' }

    mw.incident.entities:
        class: ArrayObject
        arguments:
            - - { key: klant, dao: '@MwBundle\Service\KlantDao' }
