services:
    _defaults:
        autowire: true
        autoconfigure: true

    MwBundle\Form\RapportageType:

    MwBundle\Report\CaseloadMedewerkers:
        tags:
            - { name: mw.rapportage, category: Algemeen }

    MwBundle\Report\AMW:
        arguments:
            $locaties: '%amw_locaties%'
        tags:
            - { name: mw.rapportage, category: Klanten }

    MwBundle\Report\STED:
        arguments:
            $locaties: '%economisch_daklozen_locaties%'
        tags:
            - { name: mw.rapportage, category: Klanten }

    MwBundle\Report\BegeleidThuis:
        arguments:
            $locaties: '%zonderzorg_locaties%'
        tags:
            - { name: mw.rapportage, category: Klanten }

    MwBundle\Report\Dobre:
        tags:
            - { name: mw.rapportage, category: Klanten }

    MwBundle\Report\T6:
        tags:
            - { name: mw.rapportage, category: Klanten }

    MwBundle\Report\Amstelland:
        tags:
            - { name: mw.rapportage, category: Klanten }

#    MwBundle\Report\Resultaten:
#        arguments:
#            - '@MwBundle\Service\KlantDao'
#        tags:
#            - { name: mw.rapportage, category: Klanten }

    MwBundle\Report\RepatrieringenPerLand:
        tags:
            - { name: mw.rapportage, category: Repatriëring }

    MwBundle\Report\RepatrieringenPerKlant:
        arguments:
            $sqlFile: "%kernel.project_dir%/config/sql_reports/repatrieringen_per_klant.sql"
        tags:
            - { name: mw.rapportage, category: Repatriëring }

    MwBundle\Report\EconomischDaklozen:
        arguments:
            - '@MwBundle\Service\VerslagDao'
            - '%economisch_daklozen_locaties%'
        tags:
            - { name: mw.rapportage, category: Archief }

    MwBundle\Report\ZonderZorg:
        arguments:
            - '@MwBundle\Service\VerslagDao'
            - '%zonderzorg_locaties%'
        tags:
            - { name: mw.rapportage, category: Archief }
    
    MwBundle\Report\Incidenten:
        tags:
            - { name: mw.rapportage }
