imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    MwBundle\Form\:
        resource: '%kernel.project_dir%/src/MwBundle/Form'

    MwBundle\Command\:
        resource: '%kernel.project_dir%/src/MwBundle/Command'

    MwBundle\Controller\:
        resource: '%kernel.project_dir%/src/MwBundle/Controller'

    MwBundle\Controller\BinnenViaKlantController:
        arguments:
            $dao: '@MwBundle\Service\BinnenViaKlantDao'

    MwBundle\Controller\BinnenViaVWController:
        arguments:
            $dao: '@MwBundle\Service\BinnenViaDao'

    MwBundle\Controller\DeelnamesController:
        arguments:
            $entities: '@mw.deelname.entities'

    MwBundle\Controller\DocumentenController:
        arguments:
            $entities: '@mw.document.entities'

    MwBundle\Controller\KlantenController:
        arguments:
            $export: '@mw.export.klanten'

    MwBundle\Controller\MemosController:
        arguments:
            $entities: '@mw.memo.entities'

    MwBundle\Controller\RapportagesController:
        arguments:
            $export: '@mw.export.report'
            $reports: !tagged_iterator mw.rapportage

    MwBundle\Controller\VerslagenController:
        arguments:
            $export: '@mw.export.klanten'

    MwBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@mw.export.vrijwilliger'

    MwBundle\Event\DienstenLookupSubscriber:

    verslag_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - MwBundle\Entity\Verslag

    MwBundle\Repository\VerslagRepository:
        arguments:
            $class: "@verslag_metadata"
        calls:
            - method: setGezinNoodopvangLocaties
              arguments:
                  - "%gezin_noodopvang_locaties%"
        tags:
            - app.doelstelling

    MwBundle\Form\WachtlijstFilterType:
        arguments:
            - '@InloopBundle\Service\LocatieDao'
        tags:
            - { name: form.type, alias: 'container_aware' }

    klant_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - AppBundle\Entity\Klant

    klantinfo_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - MwBundle\Entity\Info

    MwBundle\Repository\KlantRepository:
        arguments:
            $class: "@klant_metadata"
        calls:
            - method: setEconomischDaklozenLocaties
              arguments:
                  - "%economisch_daklozen_locaties%"
        tags:
            - app.doelstelling

    MwBundle\Repository\KlantInfoRepository:
        arguments:
            $class: "@klantinfo_metadata"
        calls:
            - method: setEconomischDaklozenLocaties
              arguments:
                  - "%economisch_daklozen_locaties%"
        tags:
            - app.doelstelling
