buurtboerderij_annotations:
    prefix: /buurtboerderij
    resource: "@BuurtboerderijBundle/Controller"
    type: annotation

buurtboerderij_index:
    path: /buurtboerderij/
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: buurtboerderij_vrijwilligers_index
