ga_annotations:
    prefix: /ga
    resource: "../../src/GaBundle/Controller"
    type: annotation

ga_index:
    path: /ga/
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: ga_klantdossiers_index
