inloop_annotations:
    prefix: /inloop
    resource: "../../src/InloopBundle/Controller"
    type: annotation

# inloop_index:
#    path: /inloop/
#    defaults:
#        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
#        route: inloop_index
