login:
  path: /login
  defaults:
    _controller: AppBundle\Controller\SecurityController::loginAction

login_check:
  path: /login_check

logout:
  path: /logout
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    route: login
