tw_annotations:
    prefix: /tw
    resource: "../../src/TwBundle/Controller"
    type: annotation

tw_index:
    path: /tw/
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: tw_klanten_index
