services:

    oekraine.export.registraties:
        public: true
        class: OekraineBundle\Export\RegistratiesExport
        arguments:
            - OekraineBundle\Entity\Registratie
            -
                Nummer: { expression: 'entity.getKlant().getId()' }
                Voornaam: { expression: 'entity.getKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getKlant().getAchternaam()' }
                Geslacht: { expression: 'entity.getKlant().getGeslacht()' }
                Adres: { expression: 'entity.getKlant().getAdres()' }
                Postcode: { expression: 'entity.getKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getKlant().getPlaats()' }
                E-mail: { expression: 'entity.getKlant().getEmail()' }
                Mobiel: { expression: 'entity.getKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getKlant().getWerkgebied()' }
                GGW-gebied: { expression: 'entity.getKlant().getPostcodegebied()' }
                Geboorteland: { expression: 'entity.getKlant().getGeboorteland()' }
                Nationaliteit: { expression: 'entity.getKlant().getNationaliteit()' }
                Locatie: { expression: 'entity.getLocatie()' }
                Binnen: { expression: 'entity.getBinnen()', type: 'datetime' }
                Buiten: { expression: 'entity.getBuiten()', type: 'datetime' }
                Maaltijd: { expression: 'entity.isMaaltijd()' }
                Activering: { expression: 'entity.isActivering()' }
                Kleding: { expression: 'entity.isKleding()' }
                Veegploeg: { expression: 'entity.isVeegploeg()' }
                Inkomens: { expression: 'export.getInkomens(entity.getKlant())' }
                Verblijf in Nederland sinds: { expression: 'entity.getKlant().getLaatsteIntake().getVerblijfInNederlandSinds()', condition: 'entity.getKlant().getLaatsteIntake()', type: 'date' }
                Verblijf in Amsterdam sinds: { expression: 'entity.getKlant().getLaatsteIntake().getVerblijfInAmsterdamSinds()', condition: 'entity.getKlant().getLaatsteIntake()', type: 'date' }
                Verblijfsstatus: { expression: 'entity.getKlant().getLaatsteIntake().getVerblijfsstatus()', condition: 'entity.getKlant().getLaatsteIntake()' }
                Woonsituatie: { expression: 'entity.getKlant().getLaatsteIntake().getWoonsituatie()', condition: 'entity.getKlant().getLaatsteIntake()' }

    oekraine.export.report:
        public: true
        class: AppBundle\Export\ReportExport
