services:
    _defaults:
        autowire: true
        autoconfigure: true

    HsBundle\Report\ArbeidersPerStadsdeel:
        arguments:
            - '@HsBundle\Service\DienstverlenerDao'
            - '@HsBundle\Service\VrijwilligerDao'
        tags:
            - { name: hs.rapportage, category: Dienstverleners en vrijwilligers }

    HsBundle\Report\ArbeidersPerGgwGebied:
        arguments:
            - '@HsBundle\Service\DienstverlenerDao'
            - '@HsBundle\Service\VrijwilligerDao'
        tags:
            - { name: hs.rapportage, category: Dienstverleners en vrijwilligers }

    HsBundle\Report\NieuweArbeidersPerStadsdeel:
        arguments:
            - '@HsBundle\Service\DienstverlenerDao'
            - '@HsBundle\Service\VrijwilligerDao'
        tags:
            - { name: hs.rapportage, category: Dienstverleners en vrijwilligers }

    HsBundle\Report\NieuweArbeidersPerGgwGebied:
        arguments:
            - '@HsBundle\Service\DienstverlenerDao'
            - '@HsBundle\Service\VrijwilligerDao'
        tags:
            - { name: hs.rapportage, category: Dienstverleners en vrijwilligers }

    HsBundle\Report\KlantenPerStadsdeel:
        arguments:
            - '@HsBundle\Service\KlantDao'
        tags:
            - { name: hs.rapportage, category: Klanten }

    HsBundle\Report\KlantenPerGgwGebied:
        arguments:
            - '@HsBundle\Service\KlantDao'
        tags:
            - { name: hs.rapportage, category: Klanten }

    HsBundle\Report\NieuweKlantenPerStadsdeel:
        arguments:
            - '@HsBundle\Service\KlantDao'
        tags:
            - { name: hs.rapportage, category: Klanten }

    HsBundle\Report\NieuweKlantenPerGgwGebied:
        arguments:
            - '@HsBundle\Service\KlantDao'
        tags:
            - { name: hs.rapportage, category: Klanten }

    HsBundle\Report\KlussenPerStadsdeel:
        arguments:
            - '@HsBundle\Service\KlusDao'
        tags:
            - { name: hs.rapportage, category: Klussen }

    HsBundle\Report\KlussenPerGgwGebied:
        arguments:
            - '@HsBundle\Service\KlusDao'
        tags:
            - { name: hs.rapportage, category: Klussen }

    HsBundle\Report\KoppelingenPerStadsdeel:
        arguments:
            - '@HsBundle\Service\KlusDao'
        tags:
            - { name: hs.rapportage, category: Koppelingen }

    HsBundle\Report\KoppelingenPerGgwGebied:
        arguments:
            - '@HsBundle\Service\KlusDao'
        tags:
            - { name: hs.rapportage, category: Koppelingen }

    HsBundle\Report\Uren:
        arguments:
            - '@HsBundle\Service\RegistratieDao'
        tags:
            - { name: hs.rapportage, category: Uren }
