imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    #tbv controller DI named arguments die dan niet eerst hoeven;
    _defaults:
        autowire: true
        autoconfigure: true

    HsBundle\Command\:
        resource: '%kernel.project_dir%/src/HsBundle/Command'
        tags: [ 'console.command' ]

    HsBundle\Controller\:
        resource: '%kernel.project_dir%/src/HsBundle/Controller'
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\BetalingenController:
        arguments:
            $export: '@hs.export.betaling'
            $entities: '@hs.betaling.entities'
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\DeclaratiesController:
        arguments:
            $entities: '@hs.declaratie.entities'
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\DienstverlenersController:
        arguments:
            $export: '@hs.export.dienstverlener'
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\DocumentenController:
        arguments:
            $entities: '@hs.document.entities'
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\FacturenController:
        arguments:
            $entities: '@hs.factuur.entities'
            $export: '@hs.export.factuur'
            $factory: '@hs.factory.factuur'
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\HerinneringenController:
        arguments:
            $entities: '@hs.herinnering.entities'
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\KlantenController:
        arguments:
            $export: '@hs.export.klant'
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\KlussenController:
        arguments:
            $entities: '@hs.klus.entities'
            $export: '@hs.export.klus'
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\MemosController:
        arguments:
            $entities: '@hs.memo.entities'
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\RapportagesController:
        arguments:
            $export: '@hs.export.report'
            $reports: !tagged_iterator hs.rapportage
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\RegistratiesController:
        arguments:
            $entities: '@hs.registratie.entities'
            $export: '@hs.export.registratie'
        tags: [ 'controller.service_arguments' ]

    HsBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@hs.export.vrijwilliger'
        tags: [ 'controller.service_arguments' ]

    # Twig extensions
    hs.twig.hs_extension:
        class: HsBundle\Twig\HsExtension
        public: false
        tags:
            - { name: twig.extension }

    # Form types
    hs.form.type.klant:
        class: HsBundle\Form\KlantType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }

    hs.form.rapportage:
        class: HsBundle\Form\RapportageType
        tags:
            - { name: form.type }

    # Event subscribers
    hs.event.diensten_lookup_subscriber:
        class: HsBundle\Event\DienstenLookupSubscriber
        arguments:
            - '@HsBundle\Service\DienstverlenerDao'
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    hs.event_subscriber.factuur:
        class: HsBundle\Event\FactuurSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    hs.event_subscriber.klant:
        class: HsBundle\Event\KlantUpdater
        tags:
            - { name: doctrine.event_subscriber }

    # Other services
    hs.factory.factuur:
        public: true
        class: HsBundle\Service\FactuurFactory
        arguments:
            - '@HsBundle\Service\FactuurDao'

    HsBundle\Repository\KlusRepository:
        class: HsBundle\Repository\KlusRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@klus_metadata"
        tags:
            - app.doelstelling
        public: true

    klus_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - 'HsBundle\Entity\Klus'