imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    HsBundle\Command\:
        resource: '%kernel.project_dir%/src/HsBundle/Command'

    HsBundle\Controller\:
        resource: '%kernel.project_dir%/src/HsBundle/Controller'

    HsBundle\Controller\BetalingenController:
        arguments:
            $export: '@hs.export.betaling'
            $entities: '@hs.betaling.entities'

    HsBundle\Controller\DeclaratiesController:
        arguments:
            $entities: '@hs.declaratie.entities'

    HsBundle\Controller\DienstverlenersController:
        arguments:
            $export: '@hs.export.dienstverlener'

    HsBundle\Controller\DocumentenController:
        arguments:
            $entities: '@hs.document.entities'

    HsBundle\Controller\FacturenController:
        arguments:
            $entities: '@hs.factuur.entities'
            $export: '@hs.export.factuur'
            $factory: '@HsBundle\Service\FactuurFactory'

    HsBundle\Controller\HerinneringenController:
        arguments:
            $entities: '@hs.herinnering.entities'

    HsBundle\Controller\KlantenController:
        arguments:
            $export: '@hs.export.klant'

    HsBundle\Controller\KlussenController:
        arguments:
            $entities: '@hs.klus.entities'
            $export: '@hs.export.klus'

    HsBundle\Controller\MemosController:
        arguments:
            $entities: '@hs.memo.entities'

    HsBundle\Controller\RapportagesController:
        arguments:
            $export: '@hs.export.report'
            $reports: !tagged_iterator hs.rapportage

    HsBundle\Controller\RegistratiesController:
        arguments:
            $entities: '@hs.registratie.entities'
            $export: '@hs.export.registratie'

    HsBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@hs.export.vrijwilliger'

    # Twig extensions
    HsBundle\Twig\HsExtension:

    # Form types
    HsBundle\Form\KlantType:

    HsBundle\Form\RapportageType:

    # Event subscribers
    HsBundle\Event\DienstenLookupSubscriber:

    HsBundle\Event\FactuurSubscriber:

    HsBundle\Event\KlantUpdater:

    # Other services
    HsBundle\Service\FactuurFactory:
        arguments:
            - '@HsBundle\Service\FactuurDao'

    HsBundle\Repository\KlusRepository:
        arguments:
            $class: "@klus_metadata"
        tags:
            - app.doelstelling

    klus_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - 'HsBundle\Entity\Klus'

when@dev: &dev
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        HsBundle\DataFixtures\HsFakerProvider:

        HsBundle\DataFixtures\HsProcessor:

when@test: *dev
