<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Medewerker;
use AppBundle\Form\MedewerkerFilterType;
use AppBundle\Service\MedewerkerDaoInterface;
use JMS\DiExtraBundle\Annotation as DI;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/medewerkers")
 * @Template
 * @Security("has_role('ROLE_USERADMIN')")
 */
class MedewerkersController extends AbstractController
{
    protected $title = 'Medewerkers';
    protected $entityName = 'medewerker';
    protected $entityClass = Medewerker::class;
    protected $filterFormClass = MedewerkerFilterType::class;
    protected $baseRouteName = 'app_medewerkers_';
    protected $diablesActions = ['add', 'edit', 'delete'];

    /**
     * @var MedewerkerDaoInterface
     *
     * @DI\Inject("AppBundle\Service\MedewerkerDao")
     */
    protected $dao;

    /**
     * @var MedewerkerDaoInterface
     *
     * @DI\Inject("%security.role_hierarchy.roles%")
     */
    protected $roleHierarchy;

    /**
     * @Route("/{id}/view")
     * @Template
     */
    public function viewAction(Request $request, $id)
    {

        $entity = $this->dao->find($id);


        return [
            'entity' => $entity,
            'role_hierarchy' => $this->roleHierarchy,
        ];
    }

    /**
     * @Route("/{id}/delete")
     * @param Request $request
     * @param int $id
     * @return array|\Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction(Request $request, $id)
    {
        $this->forceRedirect = true;
        return parent::deleteAction($request, $id); // TODO: Change the autogenerated stub
    }
}
