<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Medewerker;
use AppBundle\Export\AbstractExport;
use AppBundle\Form\MedewerkerFilterType;
use AppBundle\Service\MedewerkerDao;
use AppBundle\Service\MedewerkerDaoInterface;
use Doctrine\Common\Collections\ArrayCollection;
use JMS\DiExtraBundle\Annotation as DI;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;

/**
 * @Route("/medewerkers")
 * @Template
 * @IsGranted("ROLE_USERADMIN")
 */
class MedewerkersController extends AbstractController
{
    protected $entityName = 'medewerker';
    protected $entityClass = Medewerker::class;
    protected $filterFormClass = MedewerkerFilterType::class;
    protected $baseRouteName = 'app_medewerkers_';
    protected $diablesActions = ['add', 'edit', 'delete'];

    /**
     * @var MedewerkerDao
     */
    protected $dao;

    /**
     * @var MedewerkerDao
     */
    protected $roleHierarchy;

    /**
     * @var AbstractExport
     */
    protected $export;

    /**
     * @param MedewerkerDao $dao
     * @param MedewerkerDao $roleHierarchy
     */
    public function __construct(MedewerkerDao $dao, array $roleHierarchy, AbstractExport  $export)
    {
        $this->dao = $dao;
        $this->roleHierarchy = $roleHierarchy;
        $this->export = $export;
    }


    /**
     * @Route("/{id}/view")
     * @Template
     */
    public function viewAction(Request $request, $id)
    {

        $entity = $this->dao->find($id);


        return [
            'entity' => $entity,
            'role_hierarchy' => $this->roleHierarchy,
        ];
    }

    /**
     * @Route("/{id}/delete")
     * @param Request $request
     * @param int $id
     * @return array|\Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction(Request $request, $id)
    {
        $this->forceRedirect = true;
        return parent::deleteAction($request, $id); // TODO: Change the autogenerated stub
    }
}
