services:
    PfoBundle\Service\AardRelatieDao:
        parent: app.dao.abstract

    PfoBundle\Service\ClientDao:
        parent: app.dao.abstract

    PfoBundle\Service\DocumentDao:
        parent: app.dao.abstract

    PfoBundle\Service\GroepDao:
        parent: app.dao.abstract

    PfoBundle\Service\VerslagDao:
        parent: app.dao.abstract

    pfo.document.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@PfoBundle\Service\ClientDao' }

    pfo.verslag.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@PfoBundle\Service\ClientDao' }
