services:
    PfoBundle\Report\VerslagenPerGroepContacttype:
        public: true
        arguments:
            - "@pfo.repository.verslag"
        tags:
            - { name: pfo.rapportage, category: Contactmomenten }

    PfoBundle\Report\ClientenPerGroep:
        public: true
        arguments:
            - "@pfo.repository.client"
        tags:
            - { name: pfo.rapportage, category: Personen }

    PfoBundle\Report\ClientenPerStadsdeel:
        public: true
        arguments:
            - "@pfo.repository.client"
        tags:
            - { name: pfo.rapportage, category: Personen }