imports:
    - { resource: daos.yml }
    - { resource: exports.yml }
    - { resource: reports.yml }

services:
    PfoBundle\Form\ClientType:
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    pfo.repository.client:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - PfoBundle\Entity\Client

    pfo.repository.verslag:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - PfoBundle\Entity\Verslag

    pfo.form.rapportage:
        class: PfoBundle\Form\RapportageType
        tags:
            - { name: form.type }

    PfoBundle\DataFixtures\PfoProcessor:
        tags: [ { name: fidry_alice_data_fixtures.processor } ]

