services:
    dagbesteding.dao:
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@knp_paginator'
            - '%pagination.items_per_page%'

    DagbestedingBundle\Service\ContactpersoonDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\DagdeelDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\DeelnemerDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\DeelnemerafsluitingDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\DocumentDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\LocatieDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\ProjectDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\RapportageDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\ResultaatgebiedsoortDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\TrajectDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\TrajectafsluitingDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\TrajectbegeleiderDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\TrajectsoortDao:
        parent: dagbesteding.dao

    DagbestedingBundle\Service\VerslagDao:
        parent: dagbesteding.dao
