services:
    dagbesteding.export.dagdelen:
        class: AppBundle\Export\GenericExport
        arguments:
            - DagbestedingBundle\Entity\Dagdeel
            -
                Nummer: { expression: 'entity.getTraject().getDeelnemer().getKlant().getId()' }
                Ris-dossiernummer: { expression: 'entity.getTraject().getDeelnemer().getRisDossiernummer()' }
                Geslacht: { expression: 'entity.getTraject().getDeelnemer().getKlant().getGeslacht()' }
                Voornaam: { expression: 'entity.getTraject().getDeelnemer().getKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getTraject().getDeelnemer().getKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getTraject().getDeelnemer().getKlant().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getTraject().getDeelnemer().getKlant().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getTraject().getDeelnemer().getKlant().getEmail()' }
                Adres: { expression: 'entity.getTraject().getDeelnemer().getKlant().getAdres()' }
                Postcode: { expression: 'entity.getTraject().getDeelnemer().getKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getTraject().getDeelnemer().getKlant().getPlaats()' }
                Mobiel: { expression: 'entity.getTraject().getDeelnemer().getKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getTraject().getDeelnemer().getKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getTraject().getDeelnemer().getKlant().getWerkgebied()' }
                Aanmelddatum: { expression: 'entity.getTraject().getDeelnemer().getAanmelddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getTraject().getDeelnemer().getAfsluitDatum()', type: 'date' }
                Reden afsluiting: { expression: 'entity.getTraject().getDeelnemer().getAfsluiting()' }
                Startdatum: { expression: 'entity.getTraject().getStartdatum()', type: 'date' }
                Einddatum: { expression: 'entity.getTraject().getEinddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getTraject().getAfsluitdatum()', type: 'date' }
                Project: { expression: 'entity.getProject()' }
                Datum: { expression: 'entity.getDatum()', type: 'date' }
                Dagdeel: { expression: 'entity.getDagdeel()' }

    dagbesteding.export.deelnemers:
        class: AppBundle\Export\GenericExport
        arguments:
            - DagbestedingBundle\Entity\Deelnemer
            -
                Nummer: { expression: 'entity.getKlant().getId()' }
                Ris-dossiernummer: { expression: 'entity.getRisDossiernummer()' }
                Geslacht: { expression: 'entity.getKlant().getGeslacht()' }
                Voornaam: { expression: 'entity.getKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getKlant().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getKlant().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getKlant().getEmail()' }
                Adres: { expression: 'entity.getKlant().getAdres()' }
                Postcode: { expression: 'entity.getKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getKlant().getPlaats()' }
                Mobiel: { expression: 'entity.getKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getKlant().getWerkgebied()' }
                Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitDatum()', type: 'date' }
                Reden afsluiting: { expression: 'entity.getAfsluiting()' }

    dagbesteding.export.trajecten:
        class: DagbestedingBundle\Export\TrajectenExport
        arguments:
            - DagbestedingBundle\Entity\Traject
            -
                Nummer: { expression: 'entity.getId()' }
                Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
                Rapportagedata: { expression: 'export.getRapportagedata(entity)' }
                Einddatum: { expression: 'entity.getEinddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Ris-dossiernummer: { expression: 'entity.getDeelnemer().getRisDossiernummer()' }
                Geslacht: { expression: 'entity.getDeelnemer().getKlant().getGeslacht()' }
                Voornaam: { expression: 'entity.getDeelnemer().getKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getDeelnemer().getKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getDeelnemer().getKlant().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getDeelnemer().getKlant().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getDeelnemer().getKlant().getEmail()' }
                Adres: { expression: 'entity.getDeelnemer().getKlant().getAdres()' }
                Postcode: { expression: 'entity.getDeelnemer().getKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getDeelnemer().getKlant().getPlaats()' }
                Mobiel: { expression: 'entity.getDeelnemer().getKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getDeelnemer().getKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getDeelnemer().getKlant().getWerkgebied()' }
                Aanmelddatum: { expression: 'entity.getDeelnemer().getAanmelddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getDeelnemer().getAfsluitDatum()', type: 'date' }
                Reden afsluiting: { expression: 'entity.getDeelnemer().getAfsluiting()' }

    dagbesteding.export.report:
        class: DagbestedingBundle\Export\ReportExport
