services:
    dagbesteding.export.dagdelen:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - DagbestedingBundle\Entity\Dagdeel
            -
                Nummer: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getId()' }
                Ris-dossiernummer: { expression: 'entity.getTraject().getDeelnemer().getRisDossiernummer()' }
                BSN: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getBsn()' }
                Geslacht: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getGeslacht()' }
                Voornaam: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getEmail()' }
                Adres: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getAdres()' }
                Postcode: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getPlaats()' }
                Mobiel: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getTraject().getDeelnemer().getAppKlant().getWerkgebied()' }
                Aanmelddatum deelnemer: { expression: 'entity.getTraject().getDeelnemer().getAanmelddatum()', type: 'date' }
                Afsluitdatum deelnemer: { expression: 'entity.getTraject().getDeelnemer().getAfsluitDatum()', type: 'date' }
                Reden afsluiting deelnemer: { expression: 'entity.getTraject().getDeelnemer().getAfsluiting()' }
                Startdatum traject: { expression: 'entity.getTraject().getStartdatum()', type: 'date' }
                Einddatum traject: { expression: 'entity.getTraject().getEinddatum()', type: 'date' }
                Afsluitdatum traject: { expression: 'entity.getTraject().getAfsluitdatum()', type: 'date' }
                Project: { expression: 'entity.getProject()' }
                Datum: { expression: 'entity.getDatum()', type: 'date' }
                Dagdeel: { expression: 'entity.getDagdeel()' }
                Aanwezigheid:  { expression: 'entity.getAanwezigheid()' }

    dagbesteding.export.deelnemers:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - DagbestedingBundle\Entity\Deelnemer
            -
                Nummer: { expression: 'entity.getAppKlant().getId()' }
                Ris-dossiernummer: { expression: 'entity.getRisDossiernummer()' }
                BSN: { expression: 'entity.getAppKlant().getBsn()' }
                Geslacht: { expression: 'entity.getAppKlant().getGeslacht()' }
                Voornaam: { expression: 'entity.getAppKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getAppKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getAppKlant().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getAppKlant().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getAppKlant().getEmail()' }
                Adres: { expression: 'entity.getAppKlant().getAdres()' }
                Postcode: { expression: 'entity.getAppKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getAppKlant().getPlaats()' }
                Mobiel: { expression: 'entity.getAppKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getAppKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getAppKlant().getWerkgebied()' }
                Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitDatum()', type: 'date' }
                Reden afsluiting: { expression: 'entity.getAfsluiting()' }

    dagbesteding.export.trajecten:
        public: true
        class: DagbestedingBundle\Export\TrajectenExport
        arguments:
            - DagbestedingBundle\Entity\Traject
            -
                Nummer: { expression: 'entity.getId()' }
                Startdatum traject: { expression: 'entity.getStartdatum()', type: 'date' }
                Rapportagedata traject: { expression: 'export.getRapportagedata(entity)' }
                Einddatum traject: { expression: 'entity.getEinddatum()', type: 'date' }
                Afsluitdatum traject: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Ris-dossiernummer: { expression: 'entity.getDeelnemer().getRisDossiernummer()' }
                BSN: { expression: 'entity.getDeelnemer().getAppKlant().getBsn()' }
                Geslacht: { expression: 'entity.getDeelnemer().getAppKlant().getGeslacht()' }
                Voornaam: { expression: 'entity.getDeelnemer().getAppKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getDeelnemer().getAppKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getDeelnemer().getAppKlant().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getDeelnemer().getAppKlant().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getDeelnemer().getAppKlant().getEmail()' }
                Adres: { expression: 'entity.getDeelnemer().getAppKlant().getAdres()' }
                Postcode: { expression: 'entity.getDeelnemer().getAppKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getDeelnemer().getAppKlant().getPlaats()' }
                Mobiel: { expression: 'entity.getDeelnemer().getAppKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getDeelnemer().getAppKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getDeelnemer().getAppKlant().getWerkgebied()' }
                Aanmelddatum deelnemer: { expression: 'entity.getDeelnemer().getAanmelddatum()', type: 'date' }
                Afsluitdatum deelnemer: { expression: 'entity.getDeelnemer().getAfsluitDatum()', type: 'date' }
                Reden afsluiting deelnemer: { expression: 'entity.getDeelnemer().getAfsluiting()' }

    dagbesteding.export.report:
        public: true
        class: AppBundle\Export\ReportExport
