services:
    dagbesteding.form.rapportage:
        class: DagbestedingBundle\Form\ReportingType
        tags:
            - { name: form.type }

    dagbesteding.report.dagdelen_per_deelnemer:
        class: DagbestedingBundle\Report\DagdelenPerDeelnemer
        public: true
        arguments:
            - '@DagbestedingBundle\Service\DagdeelDao'
        tags:
            - { name: dagbesteding.rapportage, category: Dagdelen }

    dagbesteding.report.deelnemers_per_begeleider:
        class: DagbestedingBundle\Report\DeelnemersPerBegeleider
        public: true
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    dagbesteding.report.deelnemers_per_locatie:
        class: DagbestedingBundle\Report\DeelnemersPerLocatie
        public: true
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    dagbesteding.report.deelnemers_per_project:
        class: DagbestedingBundle\Report\DeelnemersPerProject
        public: true
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    dagbesteding.report.deelnemers_per_resultaatgebiedsoort:
        class: DagbestedingBundle\Report\DeelnemersPerResultaatgebiedsoort
        public: true
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    dagbesteding.report.trajecten_per_afsluiting:
        class: DagbestedingBundle\Report\TrajectenPerAfsluiting
        public: true
        arguments:
            - '@DagbestedingBundle\Service\TrajectDao'
        tags:
            - { name: dagbesteding.rapportage, category: Trajecten }
