services:
    dagbesteding.form.rapportage:
        class: DagbestedingBundle\Form\ReportingType
        tags:
            - { name: form.type }

    dagbesteding.report.activering:
        class: DagbestedingBundle\Report\Activering
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.root_dir%/config/activering_reports.sql"
        tags:
            - { name: dagbesteding.rapportage, category: Activering }

    dagbesteding.report.dagdelen_per_deelnemer:
        class: DagbestedingBundle\Report\DagdelenPerDeelnemer
        arguments:
            - '@DagbestedingBundle\Service\DagdeelDao'
        tags:
            - { name: dagbesteding.rapportage, category: Dagdelen }

    dagbesteding.report.deelnemers_per_begeleider:
        class: DagbestedingBundle\Report\DeelnemersPerBegeleider
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    dagbesteding.report.deelnemers_per_locatie:
        class: DagbestedingBundle\Report\DeelnemersPerLocatie
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    dagbesteding.report.deelnemers_per_project:
        class: DagbestedingBundle\Report\DeelnemersPerProject
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    dagbesteding.report.deelnemers_per_resultaatgebiedsoort:
        class: DagbestedingBundle\Report\DeelnemersPerResultaatgebiedsoort
        arguments:
            - '@DagbestedingBundle\Service\DeelnemerDao'
        tags:
            - { name: dagbesteding.rapportage, category: Deelnemers }

    dagbesteding.report.trajecten_per_afsluiting:
        class: DagbestedingBundle\Report\TrajectenPerAfsluiting
        arguments:
            - '@DagbestedingBundle\Service\TrajectDao'
        tags:
            - { name: dagbesteding.rapportage, category: Trajecten }
