imports:
    - { resource: daos.yml }
    - { resource: exports.yml }
    - { resource: reports.yml }

services:
    dagbesteding.contactpersoon.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }

    dagbesteding.dagdeel.entities:
        class: ArrayObject
        arguments:
            -
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }

    dagbesteding.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }
              - { key: rapportage, dao: '@DagbestedingBundle\Service\RapportageDao' }

    dagbesteding.traject.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }

    dagbesteding.rapportage.entities:
        class: ArrayObject
        arguments:
            -
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }

    dagbesteding.verslag.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }

    dagbesteding.event.diensten_lookup_subscriber:
        class: DagbestedingBundle\Event\DienstenLookupSubscriber
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }
