imports:
    - { resource: daos.yml }
    - { resource: exports.yml }
    - { resource: reports.yml }

services:
    dagbesteding.contactpersoon.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }

    dagbesteding.dagdeel.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }

    dagbesteding.document.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }
              - { key: rapportage, dao: '@DagbestedingBundle\Service\RapportageDao' }

    dagbesteding.traject.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }

    dagbesteding.deelname.entities:
        public: true
        class: ArrayObject
        arguments:
            - - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }
              - { key: project, dao: '@DagbestedingBundle\Service\ProjectDao' }

    dagbesteding.werkdoel.entities:
        public: true
        class: ArrayObject
        arguments:
            - - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }


    dagbesteding.rapportage.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }

    dagbesteding.verslag.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@DagbestedingBundle\Service\DeelnemerDao' }
              - { key: traject, dao: '@DagbestedingBundle\Service\TrajectDao' }

    DagbestedingBundle\Event\DienstenLookupSubscriber:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    DagbestedingBundle\Event\GeenActiveringSubscriber:
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_subscriber }
