<?php
/*
 * This file is loaded automatically by the app/webroot/index.php file after the core bootstrap.php
 *
 * This is an application wide file to load any function that is not used within a class
 * define. You can also use this to include or require any files in your application.
 *
 * PHP versions 4 and 5
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright 2005-2012, Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright 2005-2012, Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @package       cake
 * @subpackage    cake.app.config
 * @since         CakePHP(tm) v 0.10.8.2117
 * @license       MIT License (http://www.opensource.org/licenses/mit-license.php)
 */

/*
 * The settings below can be used to set additional paths to models, views and controllers.
 * This is related to Ticket #470 (https://trac.cakephp.org/ticket/470)
 *
 * App::build(array(
 *     'plugins' => array('/full/path/to/plugins/', '/next/full/path/to/plugins/'),
 *     'models' =>  array('/full/path/to/models/', '/next/full/path/to/models/'),
 *     'views' => array('/full/path/to/views/', '/next/full/path/to/views/'),
 *     'controllers' => array('/full/path/to/controllers/', '/next/full/path/to/controllers/'),
 *     'datasources' => array('/full/path/to/datasources/', '/next/full/path/to/datasources/'),
 *     'behaviors' => array('/full/path/to/behaviors/', '/next/full/path/to/behaviors/'),
 *     'components' => array('/full/path/to/components/', '/next/full/path/to/components/'),
 *     'helpers' => array('/full/path/to/helpers/', '/next/full/path/to/helpers/'),
 *     'vendors' => array('/full/path/to/vendors/', '/next/full/path/to/vendors/'),
 *     'shells' => array('/full/path/to/shells/', '/next/full/path/to/shells/'),
 *     'locales' => array('/full/path/to/locale/', '/next/full/path/to/locale/')
 * ));
 *
 */

/*
 * As of 1.3, additional rules for the inflector are added below
 *
 * Inflector::rules('singular', array('rules' => array(), 'irregular' => array(), 'uninflected' => array()));
 * Inflector::rules('plural', array('rules' => array(), 'irregular' => array(), 'uninflected' => array()));
 *
 */
$pluralizations = [
    'iz_deelnemers_iz_intervisiegroep' => 'iz_deelnemers_iz_intervisiegroepen',
    'iz_via_persoon' => 'iz_via_personen',
    'izviapersoon' => 'IzViaPersonen',
    'iz_ontstaan_contact' => 'iz_ontstaan_contacten',
    'izontstaancontact' => 'IzOntstaanContacten',
    'iz_vraagaanbod' => 'iz_vraagaanboden',
    'izvraagaanbod' => 'IzVraagaanboden',
    'iz_koppeling' => 'iz_koppelingen',
    'izkoppeling' => 'IzKoppelingen',
    'iz_verslag' => 'iz_verslagen',
    'izverslag' => 'IzVerslagen',
    'iz_deelnemers_iz_project' => 'iz_deelnemers_iz_projecten',
    'iz_afsluiting' => 'iz_afsluitingen',
    'izafsluiting' => 'IzAfsluitingen',
    'iz_eindekoppeling' => 'iz_eindekoppelingen',
    'izeindekoppeling' => 'IzEindekoppelingen',
    'iz_project' => 'iz_projecten',
    'izproject' => 'IzProjecten',
    'project' => 'Projecten',
    'iz_intervisiegroep' => 'iz_intervisiegroepen',
    'izintervisiegroep' => 'IzIntervisiegroepen',
    'awbz_hoofdaannemers' => 'awbz_hoofdaannemer',
    'awbz_indicatie' => 'awbz_indicaties',
    'awbz_intake' => 'awbz_intakes',
    'awbz_intake_verslaving' => 'awbz_intakes_verslavingen',
    'awbz_intakes_primaireproblematieksgebruikswijze' => 'awbz_intakes_primaireproblematieksgebruikswijzen',
    'awbz_intakes_verslavingsgebruikswijze' => 'awbz_intakes_verslavingsgebruikswijzen',
    'bot_verslag' => 'bot_verslagen',
    'botverslag' => 'BotVerslagen',
    'bot_koppeling' => 'bot_koppelingen',
    'botkoppeling' => 'BotKoppelingen',
    'categorie' => 'categorieen',
    'doelgroep' => 'doelgroepen',
    'doorverwijzer' => 'doorverwijzers',
    'geslacht' => 'geslachten',
    'hoofdaannemer' => 'hoofdaannemers',
    'infobaliedoelgroep' => 'infobaliedoelgroepen',
    'inkomen' => 'inkomens',
    'instantie' => 'instanties',
    'intake' => 'intakes',
    'intake_verslaving' => 'intakes_verslavingen',
    'intakes_primaireproblematieksgebruikswijze' => 'intakes_primaireproblematieksgebruikswijzen',
    'intakes_verslavingsgebruikswijze' => 'intakes_verslavingsgebruikswijzen',
    'inventarisatie' => 'inventarisaties',
    'inventarisaties_verslag' => 'inventarisaties_verslagen',
    'klant' => 'klanten',
    'klantinventarisatie' => 'klantinventarisaties',
    'land' => 'landen',
    'legitimatie' => 'legitimaties',
    'locatie' => 'locaties',
    'medewerker' => 'medewerkers',
    'nationaliteit' => 'nationaliteiten',
    'notitie' => 'notities',
    'opmerking' => 'opmerkingen',
    'pfo_aard_relatie' => 'pfo_aard_relaties',
    'pfoaardrelatie' => 'PfoAardRelaties',
    'pfo_client' => 'pfo_clienten',
    'pfogroep' => 'PfoGroepen',
    'pfo_groep' => 'pfo_groepen',
    'pfoclient' => 'PfoClienten',
    'pfo_clienten_verslag' => 'pfo_clienten_verslagen',
    'pfoclientenverslag' => 'PfoClientenVerslagen',
    'pfo_verslag' => 'pfo_verslagen',
    'pfoverslag' => 'PfoVerslagen',
    'persoon' => 'personen',
    'groepsactiviteiten_groep' => 'groepsactiviteiten_groepen',
    'groepsactiviteitengroep' => 'GroepsactiviteitenGroepen',
    'groepsactiviteiten_afsluiting' => 'groepsactiviteiten_afsluitingen',
    'groepsactiviteitenafsluiting' => 'GroepsactiviteitenAfsluitingen',
    'groepsactiviteiten_reden' => 'groepsactiviteiten_redenen',
    'groepsactiviteitenreden' => 'GroepsactiviteitenRedenen',
    'groepsactiviteiten_groepen_klant' => 'groepsactiviteiten_groepen_klanten',
    'groepsactiviteitengroepenklant' => 'GroepsactiviteitenGroepenKlanten',
    'groepsactiviteiten_klant' => 'groepsactiviteiten_klanten',
    'groepsactiviteitenklant' => 'GroepsactiviteitenKlanten',
    'groepsactiviteit' => 'groepsactiviteiten',
    'groepsactiviteiten_verslag' => 'groepsactiviteiten_verslagen',
    'groepsactiviteitenverslag' => 'GroepsactiviteitenVerslagen',
    'primaireproblematieksgebruikswijze' => 'primaireproblematieksgebruikswijzen',
    'reden' => 'redenen',
    'registratie' => 'registraties',
    'schorsing' => 'schorsingen',
    'schorsingen_reden' => 'schorsingen_redenen',
    'test_naam' => 'test_namen',
    'traject' => 'trajecten',
    'verblijfstatus' => 'verblijfstatussen',
    'verslag' => 'verslagen',
    'verslaving' => 'verslavingen',
    'verslavingsfrequentie' => 'verslavingsfrequenties',
    'verslavingsgebruikswijze' => 'verslavingsgebruikswijzen',
    'verslavingsperiode' => 'verslavingsperiodes',
    'woonsituatie' => 'woonsituaties',
    'bedrijfsector' => 'bedrijfsectoren',
    'hi5_evaluatie' => 'hi5_evaluaties',
    'locatie_tijd' => 'locatie_tijden',
    'stadsdeel' => 'stadsdelen',
    'postcodegebied' => 'postcodegebieden',
];

$singularizations = [
    'iz_deelnemers_iz_intervisiegroepen' => 'iz_deelnemers_iz_intervisiegroep',
    'iz_via_personen' => 'iz_via_persoon',
    'izviapersonen' => 'IzViaPersoon',
    'iz_ontstaan_contacten' => 'iz_ontstaan_contact',
    'izontstaancontacten' => 'IzOntstaanContact',
    'iz_vraagaanboden' => 'iz_vraagaanbod',
    'izvraagaanboden' => 'iz_vraagaanbod',
    'iz_koppelingen' => 'iz_koppeling',
    'izkoppelingen' => 'IzKoppeling',
    'iz_verslagen' => 'iz_verslag',
    'izverslagen' => 'IzVerslag',
    'iz_deelnemers_iz_projecten' => 'iz_deelnemers_iz_project',
    'iz_afsluitingen' => 'iz_afsluiting',
    'izafsluitingen' => 'IzAfsluiting',
    'iz_eindekoppelingen' => 'iz_eindekoppeling',
    'izeindekoppelingen' => 'IzEindekoppeling',
    'iz_projecten' => 'iz_project',
    'izprojecten' => 'IzProject',
    'iz_intervisiegroepen' => 'iz_intervisiegroep',
    'izintervisiegroepen' => 'IzIntervisiegroep',
    'awbz_hoofdaannemer' => 'awbz_hoofdaannemers',
    'awbz_indicaties' => 'awbz_indicatie',
    'awbz_intakes' => 'awbz_intake',
    'awbz_intakes_primaireproblematieksgebruikswijzen' => 'awbz_intakes_primaireproblematieksgebruikswijze',
    'awbz_intakes_verslavingsgebruikswijzen' => 'awbz_intakes_verslavingsgebruikswijze',
    'bot_koppelingen' => 'bot_koppeling',
    'botkoppelingen' => 'BotKoppeling',
    'bot_verslagen' => 'bot_verslag',
    'botverslagen' => 'BotVerslag',
    'categorieen' => 'categorie',
    'doelgroepen' => 'doelgroep',
    'doorverwijzers' => 'doorverwijzer',
    'geslachten' => 'geslacht',
    'hoofdaannemers' => 'hoofdaannemer',
    'infobaliedoelgroepen' => 'infobaliedoelgroep',
    'inkomens' => 'inkomen',
    'instanties' => 'instantie',
    'intakes' => 'intake',
    'intakes_primaireproblematieksgebruikswijzen' => 'intakes_primaireproblematieksgebruikswijze',
    'intakes_verslavingsgebruikswijzen' => 'intakes_verslavingsgebruikswijze',
    'inventarisaties' => 'inventarisatie',
    'inventarisaties_verslagen' => 'inventarisaties_verslag',
    'klanten' => 'klant',
    'klantinventarisaties' => 'klantinventarisatie',
    'landen' => 'land',
    'legitimaties' => 'legitimatie',
    'iz_deelnemers' => 'iz_deelnemer',
    'izdeelnemers' => 'IzDeelnemer',
    'locaties' => 'locatie',
    'medewerkers' => 'medewerker',
    'nationaliteiten' => 'nationaliteit',
    'notities' => 'notitie',
    'opmerkingen' => 'opmerking',
    'pfo_aard_relaties' => 'pfo_aard_relatie',
    'pfoaardrelaties' => 'PfoAardRelatie',
    'pfo_groepen' => 'pfo_groep',
    'pfogroepen' => 'PfoGroep',
    'pfo_clienten' => 'pfo_client',
    'pfoclienten' => 'PfoClient',
    'pfo_verslagen' => 'pfo_verslag',
    'pfoverslagen' => 'PfoVerslag',
    'personen' => 'persoon',
    'groepsactiviteiten_groepen' => 'groepsactiviteiten_groep',
    'groepsactiviteitengroepen' => 'GroepsactiviteitenGroep',
    'groepsactiviteiten_afsluitingen' => 'groepsactiviteiten_afsluiting',
    'groepsactiviteitenafsluitingen' => 'GroepsactiviteitenAfsluiting',
    'groepsactiviteiten_redenen' => 'groepsactiviteiten_reden',
    'groepsactiviteitenredenen' => 'GroepsactiviteitenReden',
    'groepsactiviteiten_redenen' => 'groepsactiviteiten_reden',
    'groepsactiviteitenredenen' => 'GroepsactiviteitenReden',
    'groepsactiviteiten_groepen_klanten' => 'groepsactiviteiten_groepen_klant',
    'groepsactiviteitengroepenklanten' => 'GroepsactiviteitenGroepenKlant',
    'groepsactiviteiten_klanten' => 'groepsactiviteiten_klant',
    'groepsactiviteitenklanten' => 'GroepsactiviteitenKlant',
    'groepsactiviteiten' => 'Groepsactiviteit',
    'groepsactiviteiten_verslagen' => 'groepsactiviteiten_verslag',
    'groepsactiviteitenverslagen' => 'GroepsactiviteitenVerslag',
    'pfo_clienten_verslagen' => 'pfo_clienten_verslag',
    'pfoclientenverslagen' => 'PfoClientenVerslag',
    'PfoClientenVerslagen' => 'PfoClientenVerslag',
    'primaireproblematieksgebruikswijzen' => 'primaireproblematieksgebruikswijze',
    'redenen' => 'reden',
    'registraties' => 'registratie',
    'schorsingen' => 'schorsing',
    'schorsingen_redenen' => 'schorsingen_reden',
    'test_namen' => 'test_naam',
    'trajecten' => 'traject',
    'verblijfstatussen' => 'verblijfstatus',
    'verslagen' => 'verslag',
    'verslavingen' => 'verslaving',
    'verslavingsfrequenties' => 'verslavingsfrequentie',
    'verslavingsgebruikswijzen' => 'verslavingsgebruikswijze',
    'verslavingsperiodes' => 'verslavingsperiode',
    'woonsituaties' => 'woonsituatie',
    'bedrijfsectoren' => 'bedrijfsector',
    'hi5_evaluaties' => 'hi5_evaluatie',
    'locatie_tijden' => 'locatie_tijd',
    'postcodegebieden' => 'postcodegebied',
];

Inflector::rules('singular', [
    'rules' => [],
    'irregular' => $singularizations,
    'uninflected' => [],
]);
Inflector::rules('plural', [
    'rules' => [],
    'irregular' => $pluralizations,
    'uninflected' => [],
]);
