imports:
    - { resource: config_dev.yml }

parameters:
    acl_disabled: false
    doctrine.dbal.connection_factory.class: Liip\FunctionalTestBundle\Factory\ConnectionFactory
    
services:
    app.fixtures:
        class: AppBundle\DataFixtures\AppFixtures
        tags:
            - { name: doctrine.fixture.orm }
    hs.fixtures:
        class: HsBundle\DataFixtures\HsFixtures
        tags:
            - { name: doctrine.fixture.orm }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: MOCKSESSID
    profiler:
        only_exceptions: false
        enabled: true
        collect: true

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        driver: pdo_sqlite
        path: '%kernel.cache_dir%/__DBNAME__.db'

swiftmailer:
    disable_delivery: true

liip_functional_test:
    cache_sqlite_db: true
    query:
        max_query_count: 10
    paratest:
        process: 8
        phpunit: 'vendor/bin/phpunit'
