imports:
    - { resource: config.yml }
    - { resource: security_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
        name: MOCKSESSID
    profiler:
        enabled: true
        collect: true

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        driver: pdo_sqlite
        path: '%kernel.cache_dir%/test.db'
#        memory: true
    orm:
        dql:
            datetime_functions:
                hour: DoctrineExtensions\Query\Sqlite\Hour
                minute: DoctrineExtensions\Query\Sqlite\Minute
            string_functions:
                concat_ws: DoctrineExtensions\Query\Sqlite\ConcatWs

swiftmailer:
    disable_delivery: true

liip_functional_test: ~

liip_test_fixtures:
    cache_db:
        sqlite: liip_functional_test.services_database_backup.sqlite

#    cache_sqlite_db: true
#    query:
#        max_query_count: 10

#hautelook_alice:
#    #    db_drivers:
#    #        orm: ~
#    #    locale: "nl_NL"
#    #    seed: 1
#    #    persist_once: false # Only persist objects once if multiple files are passed
#    #    loading_limit: 5    # Maximum number of time the loader will try to load the files passed
#    fixtures_path: ['DataFixtures','fixtures'] # Path to which to look for fixtures relative to the project directory or the bundle path. May be a string or an array of strings.
#    root_dirs:
#        - '%kernel.root_dir%'
#        - '%kernel.project_dir%'
nelmio_alice:
    #    db_drivers:
    #        orm: ~
    locale: 'nl_NL' # Default locale for the Faker Generator
    seed: 1 # Value used to make sure Faker generates data consistently across
    # runs, set to null to disable.
    functions_blacklist: # Some Faker formatter may have the same name as PHP
        - 'current'      # native functions. PHP functions have the priority,
        # so if you want to use a Faker formatter instead,
        # blacklist this function here
    loading_limit: 5 # Alice may do some recursion to resolve certain values.
    # This parameter defines a limit which will stop the
    # resolution once reached.
    max_unique_values_retry: 150 # Maximum number of time Alice can try to
    # generate a unique value before stopping and
    # failing.


fidry_alice_data_fixtures:
    default_purge_mode: delete # default is "delete" but you can change it to "truncate" or "no_purge"
    db_drivers:
        doctrine_orm: ~