#imports:
#    - { resource: config.yml }
#    - { resource: security_test.yml }
#
#framework:
#    test: ~
#    session:
#        storage_id: session.storage.mock_file
#        name: MOCKSESSID
#    profiler:
#        enabled: true
#        collect: true
#
#web_profiler:
#    toolbar: false
#    intercept_redirects: false
#
#
#
#
#liip_functional_test: ~
#
##liip_test_fixtures:
##    cache_db:
##        sqlite: liip_functional_test.services_database_backup.sqlite
##    cache_sqlite_db: true
##    query:
##        max_query_count: 10
#
#nelmio_alice:
#    #    db_drivers:
#    #        orm: ~
#    locale: 'nl_NL' # Default locale for the Faker Generator
#    seed: 1 # Value used to make sure Faker generates data consistently across
#    # runs, set to null to disable.
#    functions_blacklist: # Some Faker formatter may have the same name as PHP
#        - 'current'      # native functions. PHP functions have the priority,
#        # so if you want to use a Faker formatter instead,
#        # blacklist this function here
#    loading_limit: 5 # Alice may do some recursion to resolve certain values.
#    # This parameter defines a limit which will stop the
#    # resolution once reached.
#    max_unique_values_retry: 150 # Maximum number of time Alice can try to
#    # generate a unique value before stopping and
#    # failing.
#
#
#fidry_alice_data_fixtures:
#    default_purge_mode: truncate # default is "delete" but you can change it to "truncate" or "no_purge"
#    db_drivers:
##        doctrine_orm: ~
#
##dama_doctrine_test:
##    enable_static_connection: true
##    enable_static_meta_data_cache: true
##    enable_static_query_cache: true
#
#parameters:
#    prevent_save_enabled: '2031-12-24 09:00:00'