security:
    encoders:
        AppBundle\Entity\Medewerker: plaintext

    providers:
        chain_provider:
            chain:
                providers: [database, ldap]
        database:
            entity: { class: AppBundle\Entity\Medewerker, property: username }
        ldap:
            id: ldap_tools.security.user.ldap_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # Here we use the chained provider defined previously...
            provider: chain_provider
            pattern: ^/
            logout: ~
            # Here we tell it to use the LDAP Guard for authentication...
            guard:
                authenticators:
                    - ldap_tools.security.ldap_guard_authenticator

        login:
            anonymous: ~
            pattern: ^/login$

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/clip/admin, roles: ROLE_CLIP_BEHEER }
        - { path: ^/clip, roles: ROLE_CLIP }
        - { path: ^/dagbesteding/admin, roles: ROLE_DAGBESTEDING_BEHEER }
        - { path: ^/dagbesteding, roles: ROLE_DAGBESTEDING }
        - { path: ^/ga/admin, roles: ROLE_GA_BEHEER }
        - { path: ^/ga, roles: ROLE_GA }
        - { path: ^/hs/admin, roles: ROLE_HOMESERVICE_BEHEER }
        - { path: ^/hs, roles: ROLE_HOMESERVICE }
        - { path: ^/inloop/admin, roles: ROLE_INLOOP_BEHEER }
        - { path: ^/inloop, roles: ROLE_INLOOP }
        - { path: ^/iz/admin, roles: ROLE_IZ_BEHEER }
        - { path: ^/iz, roles: ROLE_IZ }
        - { path: ^/mw/admin, roles: ROLE_MW_BEHEER }
        - { path: ^/mw, roles: ROLE_MW }
        - { path: ^/odp/admin, roles: ROLE_ODP_BEHEER }
        - { path: ^/odp, roles: ROLE_ODP }
        - { path: ^/oek/admin, roles: ROLE_OEK_BEHEER }
        - { path: ^/oek, roles: ROLE_OEK }
        - { path: ^/pfo/admin, roles: ROLE_PFO_BEHEER }
        - { path: ^/pfo, roles: ROLE_PFO }
        - { path: ^/, roles: CONTROLLER_ACCESS_VOTER }
