services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    BuurtboerderijBundle\Service\:
        resource: '%kernel.project_dir%/src/BuurtboerderijBundle/Service/'
