imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    BuurtboerderijBundle\Controller\:
        resource: '%kernel.project_dir%/src/BuurtboerderijBundle/Controller'

    BuurtboerderijBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@buurtboerderij.export.vrijwilligers'
