hautelook_alice:
  #    db_drivers:
  #        orm: ~
  #    locale: "nl_NL"
  #    seed: 1
  #    persist_once: false # Only persist objects once if multiple files are passed
  #    loading_limit: 5    # Maximum number of time the loader will try to load the files passed
  fixtures_path: ['fixtures','DataFixtures/ORM'] # Path to which to look for fixtures relative to the project directory or the bundle path. May be a string or an array of strings.
  root_dirs:
    - '%kernel.root_dir%'
    - '%kernel.project_dir%'