#security:
#    firewalls:
#        main:
#            # Here we tell it to use the LDAP Guard for authentication...
#            guard:
#                authenticators:
#                    - security.development_guard_authenticator
#                entry_point: security.development_guard_authenticator
#
#services:
#    security.development_guard_authenticator:
#        class: AppBundle\Security\DevelopmentAuthenticator
#        arguments:
#            - '@security.authentication.guard_handler'