services:
    security.development_guard_authenticator:
        class: AppBundle\Security\DevelopmentAuthenticator
        arguments:
            - '@security.authentication.guard_handler'

security:
    firewalls:
        main:
            guard:
                authenticators:
                    - security.development_guard_authenticator
                    - ldap_tools.security.ldap_guard_authenticator
                entry_point: ldap_tools.security.ldap_guard_authenticator
