services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    OekraineBundle\Service\:
        resource: '%kernel.project_dir%/src/OekraineBundle/Service/'

    oekraine.document.entities:
        class: ArrayObject
        arguments:
            -
                - { key: bezoeker, dao: '@OekraineBundle\Service\BezoekerDao' }

    oekraine.memo.entities:
        class: ArrayObject
        arguments:
            - []

    oekraine.incident.entities:
        class: ArrayObject
        arguments:
            -
                - { key: bezoeker, dao: '@OekraineBundle\Service\BezoekerDao' }

    oekraine.verslag.entities:
        class: ArrayObject
        arguments:
            -
                - { key: bezoeker, dao: '@OekraineBundle\Service\BezoekerDao' }
