services:
    _defaults:
        autowire: true
        autoconfigure: true

    oekraine.export.registraties:
        class: OekraineBundle\Export\RegistratiesExport
        arguments:
            - OekraineBundle\Entity\Registratie
            -
                Nummer: { expression: 'entity.getAppKlant().getId()' }
                Voornaam: { expression: 'entity.getAppKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getAppKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getAppKlant().getAchternaam()' }
                Geslacht: { expression: 'entity.getAppKlant().getGeslacht()' }
                Adres: { expression: 'entity.getAppKlant().getAdres()' }
                Postcode: { expression: 'entity.getAppKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getAppKlant().getPlaats()' }
                E-mail: { expression: 'entity.getAppKlant().getEmail()' }
                Mobiel: { expression: 'entity.getAppKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getAppKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getAppKlant().getWerkgebied()' }
                GGW-gebied: { expression: 'entity.getAppKlant().getPostcodegebied()' }
                Geboorteland: { expression: 'entity.getAppKlant().getGeboorteland()' }
                Nationaliteit: { expression: 'entity.getAppKlant().getNationaliteit()' }
                Locatie: { expression: 'entity.getLocatie()' }
                Binnen: { expression: 'entity.getBinnen()', type: 'datetime' }
                Buiten: { expression: 'entity.getBuiten()', type: 'datetime' }
                Maaltijd: { expression: 'entity.isMaaltijd()' }
                Activering: { expression: 'entity.isActivering()' }
                Kleding: { expression: 'entity.isKleding()' }
                Veegploeg: { expression: 'entity.isVeegploeg()' }
                Inkomens: { expression: 'export.getInkomens(entity.getAppKlant())' }
                Verblijf in Nederland sinds: { expression: 'entity.getAppKlant().getLaatsteIntake().getVerblijfInNederlandSinds()', condition: 'entity.getAppKlant().getLaatsteIntake()', type: 'date' }
                Verblijf in Amsterdam sinds: { expression: 'entity.getAppKlant().getLaatsteIntake().getVerblijfInAmsterdamSinds()', condition: 'entity.getAppKlant().getLaatsteIntake()', type: 'date' }
                Verblijfsstatus: { expression: 'entity.getAppKlant().getLaatsteIntake().getVerblijfsstatus()', condition: 'entity.getAppKlant().getLaatsteIntake()' }
                Woonsituatie: { expression: 'entity.getAppKlant().getLaatsteIntake().getWoonsituatie()', condition: 'entity.getAppKlant().getLaatsteIntake()' }

    oekraine.export.bezoekers:
        class: OekraineBundle\Export\BezoekerExport
        arguments:
            - OekraineBundle\Entity\Bezoeker
            -
                Nummer: { expression: 'entity.getAppKlant().getId()' }
                Voornaam: { expression: 'entity.getAppKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getAppKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getAppKlant().getAchternaam()' }
                Geslacht: { expression: 'entity.getAppKlant().getGeslacht()' }
                Geboortedatum: { expression: 'entity.getAppKlant().getGeboortedatum()', type: 'date' }
                Adres: { expression: 'entity.getAppKlant().getAdres()' }
                Postcode: { expression: 'entity.getAppKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getAppKlant().getPlaats()' }
                E-mail: { expression: 'entity.getAppKlant().getEmail()' }
                Mobiel: { expression: 'entity.getAppKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getAppKlant().getTelefoon()' }
                Bsn: { expression: 'entity.getAppKlant().getBsn()' }
                Werkgebied: { expression: 'entity.getAppKlant().getWerkgebied()' }
                GGW-gebied: { expression: 'entity.getAppKlant().getPostcodegebied()' }
#                Geboorteland: { expression: 'entity.getAppKlant().getGeboorteland()' }
                Nationaliteit: { expression: 'entity.getAppKlant().getNationaliteit()' }
                Intake medewerker: { expression: 'entity.getLaatsteIntake().getMedewerker()', condition: 'entity.getLaatsteIntake()' }
                Intake datum: { expression: 'entity.getLaatsteIntake().getIntakedatum()', condition: 'entity.getLaatsteIntake()', type: 'date' }
                Intake woonlocatie: { expression: 'entity.getLaatsteIntake().getWoonlocatie()', condition: 'entity.getLaatsteIntake()' }
                Intake kamernummer: { expression: 'entity.getLaatsteIntake().getKamernummer()', condition: 'entity.getLaatsteIntake()' }
                Intake legitimatie: { expression: 'entity.getLaatsteIntake().getLegitimatie()', condition: 'entity.getLaatsteIntake()' }
                Intake inkomen: { expression: 'entity.getLaatsteIntake().getInkomens()', condition: 'entity.getLaatsteIntake()' }
                Dossierstatus: { expression: 'entity.getDossierStatus()'}
                Mental coach: { expression: 'entity.getMentalCoach()'}
#                Binnen: { expression: 'entity.getBinnen()', type: 'datetime' }
#                Buiten: { expression: 'entity.getBuiten()', type: 'datetime' }
#                Maaltijd: { expression: 'entity.isMaaltijd()' }
#                Activering: { expression: 'entity.isActivering()' }
#                Kleding: { expression: 'entity.isKleding()' }
#                Veegploeg: { expression: 'entity.isVeegploeg()' }
#                Inkomens: { expression: 'export.getInkomens(entity.getAppKlant())' }
#                Verblijf in Nederland sinds: { expression: 'entity.getAppKlant().getLaatsteIntake().getVerblijfInNederlandSinds()', condition: 'entity.getAppKlant().getLaatsteIntake()', type: 'date' }
#                Verblijf in Amsterdam sinds: { expression: 'entity.getAppKlant().getLaatsteIntake().getVerblijfInAmsterdamSinds()', condition: 'entity.getAppKlant().getLaatsteIntake()', type: 'date' }
#                Verblijfsstatus: { expression: 'entity.getAppKlant().getLaatsteIntake().getVerblijfsstatus()', condition: 'entity.getAppKlant().getLaatsteIntake()' }
#                Woonsituatie: { expression: 'entity.getAppKlant().getLaatsteIntake().getWoonsituatie()', condition: 'entity.getAppKlant().getLaatsteIntake()' }

    oekraine.export.report:
        class: AppBundle\Export\ReportExport
