services:
    _defaults:
        autowire: true
        autoconfigure: true

    OekraineBundle\Form\RapportageType:

    OekraineBundle\Report\Klanten:
        tags:
            - { name: oekraine.rapportage }

    OekraineBundle\Report\Klantenoverzicht:
        tags:
            - { name: oekraine.rapportage }