services:
    _defaults:
        autowire: true
        autoconfigure: true
    OekraineBundle\Form\RapportageType:
        tags:
            - { name: form.type }

    OekraineBundle\Report\Klanten:
        public: true
        tags:
            - { name: oekraine.rapportage }

    OekraineBundle\Report\Klantenoverzicht:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: oekraine.rapportage }