imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

parameters:
    oekraine.vrijwilligers_locaties:
        vrijwilliger_oud_west: 14
        vrijwilliger_eik: 9
        vrijwilliger_de_kloof: 10
        vrijwilliger_macom: 11
        vrijwilliger_macom_nacht: 12
        vwspreekbuis: 15

services:
    _defaults:
        autowire: true
        autoconfigure: true

    OekraineBundle\Controller\:
        resource: '%kernel.project_dir%/src/OekraineBundle/Controller'

    OekraineBundle\Controller\BezoekersController:
        arguments:
            $export: '@oekraine.export.bezoekers'


    OekraineBundle\Controller\DocumentenController:
        arguments:
            $entities: '@oekraine.document.entities'

    OekraineBundle\Controller\IncidentenController:
        arguments:
            $entities: '@oekraine.incident.entities'

    OekraineBundle\Controller\MemosController:
        arguments:
            $entities: '@oekraine.memo.entities'

    OekraineBundle\Controller\RapportagesController:
        arguments:
            $export: '@oekraine.export.report'
            $reports: !tagged_iterator oekraine.rapportage

    OekraineBundle\Controller\RegistratiesController:
        arguments:
            $export: '@oekraine.export.registraties'

    OekraineBundle\Controller\VerslagenController:
        arguments:
            $entities: '@oekraine.verslag.entities'

    OekraineBundle\Service\AccessUpdater:

    OekraineBundle\Service\BezoekerDaoInterface: '@OekraineBundle\Service\BezoekerDao'

    OekraineBundle\Service\LocatieDaoInterface: '@OekraineBundle\Service\LocatieDao'

    OekraineBundle\Event\IntakeSubscriber:
        arguments:
            - '@OekraineBundle\Service\BezoekerDao'
            - "@logger"
            - "@templating"
            - "@mailer"
            - '@OekraineBundle\Service\AccessUpdater'
            - "%informele_zorg_mail%"
            - "%dagbesteding_mail%"
            - "%hulpverlening_mail%"

    OekraineBundle\Event\DossierSubscriber:
        arguments:
            - '@OekraineBundle\Service\BezoekerDao'
            - '@OekraineBundle\Service\AccessUpdater'

    OekraineBundle\Event\LocatieSubscriber:
        arguments:
            - '@OekraineBundle\Service\AccessUpdater'

    OekraineBundle\Event\DienstenLookupSubscriber:

    OekraineBundle\Event\RegistratieSubscriber:

    OekraineBundle\Security\IntakeVoter:
        arguments:
            - "@security.access.decision_manager"

    OekraineBundle\Security\RegistratieVoter:
        arguments:
            - "%oekraine.vrijwilligers_locaties%"

    registratie_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - OekraineBundle\Entity\Registratie

    OekraineBundle\Repository\RegistratieRepository:
        class: OekraineBundle\Repository\RegistratieRepository
        arguments:
            $class: "@registratie_metadata"
        calls:
            - method: setSpuitomruilLocaties
              arguments:
                  - '%spuitomruil_locaties%'
        tags:
            - app.doelstelling

    OekraineBundle\Controller\VrijwilligersController:
        arguments:
            $dao: '@OekraineBundle\Service\VrijwilligerDao'
            $export: '@oekraine.export.vrijwilliger'
    
    OekraineBundle\Controller\DeelnamesController:
        arguments:
            $entities: '@oekraine.deelname.entities'