services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    OekBundle\Service\:
        resource: '%kernel.project_dir%/src/OekBundle/Service/'

    oek.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: vrijwilliger, dao: '@OekBundle\Service\VrijwilligerDao' }

    oek.memo.entities:
        class: ArrayObject
        arguments:
            -
              - { key: vrijwilliger, dao: '@OekBundle\Service\VrijwilligerDao' }

    oek.training.entities:
        class: ArrayObject
        arguments:
            -
              - { key: null }
              - { key: groep, dao: '@OekBundle\Service\GroepDao' }
