imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    OekBundle\Controller\:
        resource: '%kernel.project_dir%/src/OekBundle/Controller'

    OekBundle\Controller\DeelnemersController:
        arguments:
            $export: '@oek.export.deelnemer'

    OekBundle\Controller\DocumentenController:
        arguments:
            $entities: '@oek.document.entities'

    OekBundle\Controller\MemosController:
        arguments:
            $entities: '@oek.memo.entities'

    OekBundle\Controller\RapportagesController:
        arguments:
            $export: '@oek.export.report'
            $reports: !tagged_iterator oek.rapportage

    OekBundle\Controller\TrainingenController:
        arguments:
            $entities: '@oek.training.entities'
            $exportPresentielijst: '@oek.export.presentielijst'
            $exportDeelnemerslijst: '@oek.export.deelnemerslijst'

    OekBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@oek.export.vrijwilliger'

    OekBundle\Controller\WachtlijstController:
        arguments:
            $export: '@oek.export.wachtlijst'

    OekBundle\Event\DienstenLookupSubscriber:

    OekBundle\Event\DienstenVrijwilligerLookupSubscriber:

    deelnemer_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - 'OekBundle\Entity\Deelnemer'

    deelname_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - 'OekBundle\Entity\Deelname'

    OekBundle\Repository\DeelnemerRepository:
        arguments:
            $class: "@deelnemer_metadata"
        tags:
            - app.doelstelling

    OekBundle\Repository\DeelnameRepository:
        arguments:
            $class: "@deelname_metadata"

    oek.repository.training:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - OekBundle\Entity\Training

    OekBundle\Form\RapportageType:

    OekBundle\Report\DeelnemersPerTrainingGroep:
        arguments:
            - '@OekBundle\Repository\DeelnemerRepository'
        tags:
            - { name: oek.rapportage, category: Deelnemers }

    OekBundle\Report\DeelnemersVerwezenDoor:
        arguments:
            - '@OekBundle\Repository\DeelnemerRepository'
        tags:
            - { name: oek.rapportage, category: Deelnemers }

    OekBundle\Report\DeelnemersVerwezenNaar:
        arguments:
            - '@OekBundle\Repository\DeelnemerRepository'
        tags:
            - { name: oek.rapportage, category: Deelnemers }

    OekBundle\Report\TrainingenPerGroepNaam:
        arguments:
            - "@oek.repository.training"
        tags:
            - { name: oek.rapportage, category: Trainingen }

    OekBundle\Report\DeelnamesPerStadsdeel:
        arguments:
            - '@OekBundle\Repository\DeelnameRepository'
        tags:
            - { name: oek.rapportage, category: Deelnemers }

    OekBundle\Event\DeelnemerEventSubscriber:
        arguments:
            - '@event_dispatcher'
        tags:
            - doctrine.event_subscriber

when@dev: &dev
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        OekBundle\DataFixtures\OekFakerProvider:

when@test: *dev
