services:
    UhkBundle\Service\VerslagDao:
        parent: app.dao.abstract

    UhkBundle\Service\DeelnemerDao:
        parent: app.dao.abstract

    UhkBundle\Service\DocumentDao:
        parent: app.dao.abstract

    uhk.document.entities:
        public: true
        class: ArrayObject
        arguments:
            -
                - { key: deelnemer, dao: '@UhkBundle\Service\DeelnemerDao' }