imports:
    - { resource: daos.yml }
    - { resource: exports.yml }

services:
    #tbv controller DI named arguments die dan niet eerst hoeven;
    _defaults:
        autowire: true
        autoconfigure: true

    UhkBundle\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    UhkBundle\Controller\DocumentenController:
        arguments:
            $entities: '@uhk.document.entities'
        tags: [ 'controller.service_arguments' ]

    UhkBundle\Controller\VerslagenController:
        arguments:
            $entities: '@uhk.verslag.entities'
        tags: [ 'controller.service_arguments' ]

    uhk.verslag.entities:
        public: true
        class: ArrayObject
        arguments:
            -
                - { key: deelnemer, dao: '@UhkBundle\Service\DeelnemerDao' }
