imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    UhkBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    uhk.verslag.entities:
        public: true
        class: ArrayObject
        arguments:
            -
                - { key: deelnemer, dao: '@UhkBundle\Service\DeelnemerDao' }
