imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    uhk.verslag.entities:
        public: true
        class: ArrayObject
        arguments:
            -
                - { key: deelnemer, dao: '@UhkBundle\Service\DeelnemerDao' }
