imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    ScipBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    ScipBundle\Event\DienstenLookupSubscriber:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@router'
        tags:
            - { name: kernel.event_subscriber }

    ScipBundle\Security\DeelnameVoter:
        arguments:
            - '@security.access.decision_manager'
            - '@ScipBundle\Service\ToegangsrechtDao'
        tags:
            - { name: security.voter }

    ScipBundle\Security\DeelnemerVoter:
        arguments:
            - '@security.access.decision_manager'
            - '@ScipBundle\Service\ToegangsrechtDao'
        tags:
            - { name: security.voter }

    ScipBundle\Security\DocumentVoter:
        arguments:
            - '@security.access.decision_manager'
            - '@ScipBundle\Service\ToegangsrechtDao'
            - '@ScipBundle\Service\DeelnemerDao'
        tags:
            - { name: security.voter }

    ScipBundle\Security\ProjectVoter:
        arguments:
            - '@security.access.decision_manager'
            - '@ScipBundle\Service\ToegangsrechtDao'
        tags:
            - { name: security.voter }

    ScipBundle\Event\DeelnemerEventSubscriber:
        arguments:
            - '@event_dispatcher'
        tags:
            - { name: doctrine.event_subscriber }