services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    PfoBundle\Service\:
        resource: '%kernel.project_dir%/src/PfoBundle/Service/'

    pfo.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@PfoBundle\Service\ClientDao' }

    pfo.verslag.entities:
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@PfoBundle\Service\ClientDao' }

    pfo.incident.entities:
        class: ArrayObject
        arguments:
            - - { key: client, dao: '@PfoBundle\Service\ClientDao' }
