imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    PfoBundle\Command\:
        resource: '%kernel.project_dir%/src/PfoBundle/Command'

    PfoBundle\Controller\:
        resource: '%kernel.project_dir%/src/PfoBundle/Controller'

    PfoBundle\Controller\ClientenController:
        arguments:
            $export: '@pfo.export.client'

    PfoBundle\Controller\DocumentenController:
        arguments:
            $entities: '@pfo.document.entities'

    PfoBundle\Controller\RapportagesController:
        arguments:
            $export: '@pfo.export.report'
            $reports: !tagged_iterator pfo.rapportage

    PfoBundle\Controller\VerslagenController:
        arguments:
            $entities: '@pfo.verslag.entities'

    PfoBundle\Form\ClientType:

    pfo.repository.client:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - PfoBundle\Entity\Client

    client_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - 'PfoBundle\Entity\Client'

    PfoBundle\Repository\ClientRepository:
        arguments:
            $class: "@client_metadata"
        tags:
            - app.doelstelling

    pfo.repository.verslag:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - PfoBundle\Entity\Verslag

    PfoBundle\Form\RapportageType:
