parameters:
    cake:
        email:
            prod:
                informele_zorg: "bhuttinga@deregenboog.org"
                dagbesteding: "bhuttinga@deregenboog.org"
                inloophuis: "bhuttinga@deregenboog.org"
                hulpverlening: "bhuttinga@deregenboog.org"
                agressie: "bhuttinga@deregenboog.org"
                administratiebedrijf: "bhuttinga@deregenboog.org"
            beta:
                informele_zorg: "bhuttinga@deregenboog.org"
                dagbesteding: "bhuttinga@deregenboog.org"
                inloophuis: "bhuttinga@deregenboog.org"
                hulpverlening: "bhuttinga@deregenboog.org"
                agressie: "bhuttinga@deregenboog.org"
                administratiebedrijf: "bhuttinga@deregenboog.org"
            test:
                informele_zorg: "bhuttinga@deregenboog.org"
                dagbesteding: "bhuttinga@deregenboog.org"
                inloophuis: "bhuttinga@deregenboog.org"
                hulpverlening: "bhuttinga@deregenboog.org"
                agressie: "bhuttinga@deregenboog.org"
                administratiebedrijf: "bhuttinga@deregenboog.org"

        ACL.groups:
            GROUP_USER: "CN=ECD Bureau Straatjurist,CN=Users,DC=cluster,DC=deregenboog"
            GROUP_ADMIN: "CN=ECD Bureau Straatjurist Beheer,CN=Users,DC=cluster,DC=deregenboog"

        # group: [controllers]
        ACL.permissions:
            GROUP_USER:
                - Attachments
                - Intakes
                - Klanten
                - MaatschappelijkWerk
                - Medewerkers
                - MwInventarisaties
                - Opmerkingen
                - Rapportages
                - Verslagen
            GROUP_ADMIN:
                - Admin
                - Attachments
                - Intakes
                - Klanten
                - MaatschappelijkWerk
                - Medewerkers
                - MwInventarisaties
                - Opmerkingen
                - Rapportages
                - Verslagen
