parameters:
    cake:
        email:
            prod:
                informele_zorg: "bhuttinga@deregenboog.org"
                dagbesteding: "bhuttinga@deregenboog.org"
                inloophuis: "bhuttinga@deregenboog.org"
                hulpverlening: "bhuttinga@deregenboog.org"
                agressie: "bhuttinga@deregenboog.org"
                administratiebedrijf: "bhuttinga@deregenboog.org"
            beta:
                informele_zorg: "bhuttinga@deregenboog.org"
                dagbesteding: "bhuttinga@deregenboog.org"
                inloophuis: "bhuttinga@deregenboog.org"
                hulpverlening: "bhuttinga@deregenboog.org"
                agressie: "bhuttinga@deregenboog.org"
                administratiebedrijf: "bhuttinga@deregenboog.org"
            test:
                informele_zorg: "bhuttinga@deregenboog.org"
                dagbesteding: "bhuttinga@deregenboog.org"
                inloophuis: "bhuttinga@deregenboog.org"
                hulpverlening: "bhuttinga@deregenboog.org"
                agressie: "bhuttinga@deregenboog.org"
                administratiebedrijf: "bhuttinga@deregenboog.org"

        ACL.groups:
            GROUP_USER: "CN=ECD Bureau Straatjurist,CN=Users,DC=cluster,DC=deregenboog"
            GROUP_ADMIN: "CN=ECD Bureau Straatjurist Beheer,CN=Users,DC=cluster,DC=deregenboog"

        # group: [controllers]
        ACL.permissions:
            GROUP_USER:
                - Attachments
                - Intakes
                - Klanten
                - MaatschappelijkWerk
                - Medewerkers
                - MwInventarisaties
                - Opmerkingen
                - Rapportages
                - Verslagen
            GROUP_ADMIN:
                - Admin
                - Attachments
                - Intakes
                - Klanten
                - MaatschappelijkWerk
                - Medewerkers
                - MwInventarisaties
                - Opmerkingen
                - Rapportages
                - Verslagen

        # controller: {label, url}
        all_menu_items:
            Klanten:
                label: Klanten
                url: Klanten
            Vrijwilligers:
                label: Vrijwilligers
                url: Vrijwilligers
            Registraties:
                label: Registratie
                url: Registraties
            inloop:
                label: Inloophuizen
                url: inloop
            MaatschappelijkWerk:
                label: Maatschappelijk werk
                url: MaatschappelijkWerk
            Rapportages:
                label: Rapportages
                url: Rapportages
#            Awbz:
#                label: AWBZ
#                url: Awbz
            clip:
                label: Clip
                url: clip
            dagbesteding:
                label: Dagbesteding
                url: dagbesteding
            groepsactiviteiten_klanten:
                label: Groepsactiviteiten
                url: groepsactiviteiten_klanten
#            Hi5:
#                label: Hi5
#                url: Hi5
            hs:
                label: Homeservice
                url: hs
            iz:
                label: Informele Zorg
                url: iz
            odp:
                label: Onder de Pannen
                url: odp
            oek:
                label: Op Eigen Kracht
                url: oek
            pfo:
                label: PFO
                url: pfo
            Admin:
                label: Admin
                url: Admin
