<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true,'test'=>true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    Fidry\AliceDataFixtures\Bridge\Symfony\FidryAliceDataFixturesBundle::class => ['dev' => true, 'test' => true],
    FOS\CKEditorBundle\FOSCKEditorBundle::class => ['all' => true],
    Hautelook\AliceBundle\HautelookAliceBundle::class => ['dev' => true, 'test' => true],
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class => ['all' => true],
    Liip\FunctionalTestBundle\LiipFunctionalTestBundle::class => ['test' => true],
    Liip\TestFixturesBundle\LiipTestFixturesBundle::class => ['dev' => false, 'test' => true],
    Nelmio\Alice\Bridge\Symfony\NelmioAliceBundle::class => ['dev' => true, 'test' => true],
    Shivas\VersioningBundle\ShivasVersioningBundle::class => ['all' => true],
    Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Vich\UploaderBundle\VichUploaderBundle::class => ['all' => true],
    AppBundle\AppBundle::class => ['all' => true],
    BuurtboerderijBundle\BuurtboerderijBundle::class => ['all' => true],
    ClipBundle\ClipBundle::class => ['all' => true],
    DagbestedingBundle\DagbestedingBundle::class => ['all' => true],
    ErOpUitBundle\ErOpUitBundle::class => ['all' => true],
    GaBundle\GaBundle::class => ['all' => true],
    HsBundle\HsBundle::class => ['all' => true],
    InloopBundle\InloopBundle::class => ['all' => true],
    IzBundle\IzBundle::class => ['all' => true],
    MwBundle\MwBundle::class => ['all' => true],
    OekBundle\OekBundle::class => ['all' => true],
    OekraineBundle\OekraineBundle::class => ['all' => true],
    PfoBundle\PfoBundle::class => ['all' => true],
    TwBundle\TwBundle::class => ['all' => true],
    UhkBundle\UhkBundle::class => ['all' => true],
    VillaBundle\VillaBundle::class => ['all' => true],
];
