services:
    inloop.dao:
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@knp_paginator'
            - '%pagination.items_per_page%'

    inloop.dao.klant:
        parent: inloop.dao
        class: InloopBundle\Service\KlantDao

    inloop.dao.registratie:
        parent: inloop.dao
        class: InloopBundle\Service\RegistratieDao

    inloop.dao.schorsing:
        parent: inloop.dao
        class: InloopBundle\Service\SchorsingDao
        