services:
    inloop.dao:
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@knp_paginator'
            - '%pagination.items_per_page%'

    inloop.dao.klant:
        parent: inloop.dao
        class: InloopBundle\Service\KlantDao
