services:
    inloop.dao:
        abstract: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@knp_paginator'
            - '%pagination.items_per_page%'

    InloopBundle\Service\BinnenViaDao:
        parent: inloop.dao

    InloopBundle\Service\DocumentDao:
        parent: inloop.dao

    InloopBundle\Service\KlantDao:
        parent: inloop.dao

    InloopBundle\Service\MemoDao:
        parent: inloop.dao

    InloopBundle\Service\RegistratieDao:
        parent: inloop.dao

    InloopBundle\Service\SchorsingDao:
        parent: inloop.dao
        
    InloopBundle\Service\VrijwilligerDao:
        parent: inloop.dao

    inloop.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: vrijwilliger, dao: '@InloopBundle\Service\VrijwilligerDao' }

    inloop.memo.entities:
        class: ArrayObject
        arguments:
            -
              - { key: vrijwilliger, dao: '@InloopBundle\Service\VrijwilligerDao' }
