inloop_annotations:
    resource: "@InloopBundle/Controller"
    type: annotation
    prefix: /inloop

inloop_index:
    path: /inloop/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: inloop_klanten_index
