inloop_annotations:
    resource: "@InloopBundle/Controller"
    type: annotation

inloop_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: inloop_registraties_locationselect
