imports:
    - { resource: daos.yml }
    - { resource: exports.yml }
    - { resource: reports.yml }

parameters:
    inloop.vrijwilligers_locaties:
        vrijwilliger_oud_west: 14
        vrijwilliger_eik: 9
        vrijwilliger_de_kloof: 10
        vrijwilliger_macom: 11
        vrijwilliger_macom_nacht: 12
        vwspreekbuis: 15

services:
    #tbv controller DI named arguments die dan niet eerst hoeven;
    _defaults:
        autowire: true
        autoconfigure: true

    InloopBundle\Command\:
        resource: '../../Command'
        tags: [ 'console.command' ]

    InloopBundle\Form\:
        resource: '../../Form'

    InloopBundle\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\KlantenController:
        arguments:
            $tbc_countries: '%tbc_countries%'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\LocatiesController:
        arguments:
            $accessStrategies: '%access_strategies%'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\IntakesController:
        arguments:
            $dao: '@InloopBundle\Service\IntakeDao'
            $tbc_countries: '%tbc_countries%'
            $accessStrategies: '%access_strategies%'
            $amocVerblijfsstatus: '%amocverblijfsstatus%'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\DeelnamesController:
        arguments:
            $entities: '@inloop.deelname.entities'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\DocumentenController:
        arguments:
            $entities: '@inloop.document.entities'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\IncidentenController:
        arguments:
            $entities: '@inloop.incident.entities'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\LocatietijdenController:
        arguments:
            $entities: '@inloop.locatietijd.entities'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\MemosController:
        arguments:
            $entities: '@inloop.memo.entities'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\RapportagesController:
        arguments:
            $export: '@inloop.export.report'
            $reports: !tagged_iterator inloop.rapportage
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\RegistratiesController:
        arguments:
            $export: '@inloop.export.registraties'
            $tbc_countries: '%tbc_countries%'
            $tbc_months_period: '%tbc_months_period%'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\SchorsingenController:
        arguments:
            $export: '@inloop.export.schorsing'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\VerslagenController:
        arguments:
            $export: '@mw.export.klanten'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@inloop.export.vrijwilliger'
        tags: [ 'controller.service_arguments' ]

    InloopBundle\Service\AccessUpdater:
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@InloopBundle\Service\KlantDao'
            - '@InloopBundle\Service\LocatieDao'
            - "%access_strategies%"
            - "%amocverblijfsstatus%"

    InloopBundle\Event\IntakeSubscriber:
        arguments:
            - '@InloopBundle\Service\KlantDao'
            - "@logger"
            - "@twig"
            - "@mailer"
            - '@InloopBundle\Service\AccessUpdater'
            - "%env(INFORMELE_ZORG_MAIL)%"
            - "%env(DAGBESTEDING_MAIL)%"
            - "%env(HULPVERLENING_MAIL)%"
        tags:
            - { name: kernel.event_subscriber }

    InloopBundle\Event\DossierSubscriber:
        arguments:
            - '@InloopBundle\Service\KlantDao'
            - '@InloopBundle\Service\AccessUpdater'
        tags:
            - { name: kernel.event_subscriber }

    InloopBundle\Event\LocatieSubscriber:
        arguments:
            - '@InloopBundle\Service\AccessUpdater'
        tags:
            - { name: kernel.event_subscriber }

    InloopBundle\Event\DienstenLookupSubscriber:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    InloopBundle\Event\RegistratieSubscriber:
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_subscriber }

    InloopBundle\Security\IntakeVoter:
        arguments:
            - "@security.access.decision_manager"
        tags:
            - { name: security.voter }

    InloopBundle\Security\RegistratieVoter:
        arguments:
            - "%inloop.vrijwilligers_locaties%"
        tags:
            - { name: security.voter }


    registratie_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - InloopBundle\Entity\Registratie

    InloopBundle\Repository\RegistratieRepository:
        class: InloopBundle\Repository\RegistratieRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@registratie_metadata"
        calls:
            - method: setSpuitomruilLocaties
              arguments:
                  - '%spuitomruil_locaties%'
        tags:
            - app.doelstelling
        public: true

    InloopBundle\Form\LocatieTypeSelectType:
        class: InloopBundle\Form\LocatieTypeSelectType
        arguments:
            - "@doctrine.orm.default_entity_manager"