imports:
    - { resource: daos.yml }
    - { resource: exports.yml }
    - { resource: reports.yml }

services:
    InloopBundle\Event\DienstenLookupSubscriber:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

