imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    UhkBundle\Controller\:
        resource: '%kernel.project_dir%/src/UhkBundle/Controller'

    UhkBundle\Controller\DocumentenController:
        arguments:
            $entities: '@uhk.document.entities'

    UhkBundle\Controller\VerslagenController:
        arguments:
            $entities: '@uhk.verslag.entities'

    uhk.verslag.entities:
        class: ArrayObject
        arguments:
            -
                - { key: deelnemer, dao: '@UhkBundle\Service\DeelnemerDao' }

    UhkBundle\Controller\IncidentenController:
        arguments:
            $entities: '@app.incident.entities'
