services:
    AppBundle\Export\Klanten:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - AppBundle\Entity\Klant
            -
                Nummer: { expression: 'entity.getId()' }
                Geslacht: { expression: 'entity.getGeslacht()' }
                Voornaam: { expression: 'entity.getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getAchternaam()' }
                Geboortedatum: { expression: 'entity.getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getEmail()' }
                Adres: { expression: 'entity.getAdres()' }
                Postcode: { expression: 'entity.getPostcode()' }
                Woonplaats: { expression: 'entity.getPlaats()' }
                Mobiel: { expression: 'entity.getMobiel()' }
                Telefoon: { expression: 'entity.getTelefoon()' }
                Werkgebied: { expression: 'entity.getWerkgebied()' }
                Postvoorkeur: { expression: 'entity.getGeenPost() ? "Geen post" : "Wel post"' }
                E-mailvoorkeur: { expression: 'entity.getGeenEmail() ? "Geen e-mail" : "Wel e-mail"' }

    AppBundle\Export\Vrijwilligers:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - AppBundle\Entity\Vrijwilliger
            -
                Nummer: { expression: 'entity.getId()' }
                Geslacht: { expression: 'entity.getGeslacht()' }
                Voornaam: { expression: 'entity.getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getAchternaam()' }
                Geboortedatum: { expression: 'entity.getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getEmail()' }
                Adres: { expression: 'entity.getAdres()' }
                Postcode: { expression: 'entity.getPostcode()' }
                Woonplaats: { expression: 'entity.getPlaats()' }
                Mobiel: { expression: 'entity.getMobiel()' }
                Telefoon: { expression: 'entity.getTelefoon()' }
                Werkgebied: { expression: 'entity.getWerkgebied()' }
                Postvoorkeur: { expression: 'entity.getGeenPost() ? "Geen post" : "Wel post"' }
                E-mailvoorkeur: { expression: 'entity.getGeenEmail() ? "Geen e-mail" : "Wel e-mail"' }
                Geinformeerd opslaan gegevens: { expression: 'entity.isGeinformeerdOpslaanGegevens() ? "Ja" : "Nee"' }

    AppBundle\Export\Doelstellingen:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - AppBundle\Entity\Doelstelling
            - Kostenplaats: { expression: 'entity.getKostenplaats()' }
              Label: { expression: 'entity.getRepositoryLabel()' }
              Jaar: { expression: 'entity.getJaar()' }
              Doelstelling: { expression: 'entity.getAantal()' }
              Prestatie: { expression: 'entity.getActueel()' }
              Percentage: { expression: 'entity.getActueel() / entity.getAantal()', type: 'percentage' }

    AppBundle\Export\ReportExport:
        public: true
#        class: AppBundle\Export\ReportExport
