imports:
    - { resource: daos.yml }
    - { resource: exports.yml }

services:
    app.form.rapportage:
        class: AppBundle\Form\RapportageType
        tags:
            - { name: form.type }

    AppBundle\Report\Activering:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.project_dir%/config/sql_reports/activering_reports.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\GeenHulpverlenerscontact:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.project_dir%/config/sql_reports/geen_hulpverlenerscontact.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\Ladis:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.project_dir%/config/sql_reports/ladis_report.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\ManagementInloop:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.project_dir%/config/sql_reports/management_reports_inloop.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\ManagementMW:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.project_dir%/config/sql_reports/management_reports_mw.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\Veegploeg:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.project_dir%/config/sql_reports/veegploeg_reports.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\ZrmScorePerPostcodegebied:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: app.rapportage, category: ZRM }

    AppBundle\Report\ZrmV2ScorePerPostcodegebied:
        public: true
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: app.rapportage, category: ZRM }
