imports:
    - { resource: daos.yml }
    - { resource: exports.yml }
    - { resource: reports.yml }

services:
    tw.event.diensten_lookup_subscriber:
        class: TwBundle\Event\DienstenLookupSubscriber
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    TwBundle\Form\KlantFilterType:
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    TwBundle\Security\DocumentVoter:
        arguments:
            - "@security.access.decision_manager"
        tags:
            - { name: security.voter }