services:
    HsBundle\Service\ActiviteitDao:
        parent: app.dao.abstract

    HsBundle\Service\ArbeiderDao:
        parent: app.dao.abstract

    HsBundle\Service\BetalingDao:
        parent: app.dao.abstract

    HsBundle\Service\DeclaratieCategorieDao:
        parent: app.dao.abstract

    HsBundle\Service\DeclaratieDao:
        parent: app.dao.abstract

    HsBundle\Service\DienstverlenerDao:
        parent: app.dao.abstract

    HsBundle\Service\DocumentDao:
        parent: app.dao.abstract

    HsBundle\Service\FactuurDao:
        parent: app.dao.abstract

    HsBundle\Service\HerinneringDao:
        parent: app.dao.abstract

    HsBundle\Service\KlantDao:
        parent: app.dao.abstract

    HsBundle\Service\KlusDao:
        parent: app.dao.abstract

    HsBundle\Service\MemoDao:
        parent: app.dao.abstract

    HsBundle\Service\RegistratieDao:
        parent: app.dao.abstract

    HsBundle\Service\VrijwilligerDao:
        parent: app.dao.abstract

    hs.betaling.entities:
        class: ArrayObject
        arguments:
            -
              - { key: factuur, dao: '@HsBundle\Service\FactuurDao' }

    hs.declaratie.entities:
        class: ArrayObject
        arguments:
            -
              - { key: klus, dao: '@HsBundle\Service\KlusDao' }

    hs.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: dienstverlener, dao: '@HsBundle\Service\DienstverlenerDao' }
              - { key: klant, dao: '@HsBundle\Service\KlantDao' }
              - { key: vrijwilliger, dao: '@HsBundle\Service\VrijwilligerDao' }
              - { key: klus, dao: '@HsBundle\Service\KlusDao' }

    hs.factuur.entities:
        class: ArrayObject
        arguments:
            -
              - { key: klant, dao: '@HsBundle\Service\KlantDao' }

    hs.herinnering.entities:
        class: ArrayObject
        arguments:
            -
              - { key: factuur, dao: '@HsBundle\Service\FactuurDao' }

    hs.klus.entities:
        class: ArrayObject
        arguments:
            -
              - { key: null }
              - { key: klant, dao: '@HsBundle\Service\KlantDao' }

    hs.memo.entities:
        class: ArrayObject
        arguments:
            -
              - { key: dienstverlener, dao: '@HsBundle\Service\DienstverlenerDao' }
              - { key: klant, dao: '@HsBundle\Service\KlantDao' }
              - { key: klus, dao: '@HsBundle\Service\KlusDao' }
              - { key: vrijwilliger, dao: '@HsBundle\Service\VrijwilligerDao' }

    hs.registratie.entities:
        class: ArrayObject
        arguments:
            -
              - { key: arbeider, dao: '@HsBundle\Service\ArbeiderDao' }
              - { key: klus, dao: '@HsBundle\Service\KlusDao' }
