services:
    hs.export.klant:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - HsBundle\Entity\Klant
            -
                Nummer: { expression: 'entity.getId()' }
                Geslacht: { expression: 'entity.getGeslacht()' }
                Voornaam: { expression: 'entity.getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getAchternaam()' }
                E-mail: { expression: 'entity.getEmail()' }
                Adres: { expression: 'entity.getAdres()' }
                Postcode: { expression: 'entity.getPostcode()' }
                Woonplaats: { expression: 'entity.getPlaats()' }
                Mobiel: { expression: 'entity.getMobiel()' }
                Telefoon: { expression: 'entity.getTelefoon()' }
                Werkgebied: { expression: 'entity.getWerkgebied()' }
                Actief: { expression: 'entity.isActief()' }
                Saldo: { expression: 'entity.getSaldo()' }

    hs.export.dienstverlener:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - HsBundle\Entity\Dienstverlener
            -
                Nummer: { expression: 'entity.getAppKlant().getId()' }
                Geslacht: { expression: 'entity.getAppKlant().getGeslacht()' }
                Voornaam: { expression: 'entity.getAppKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getAppKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getAppKlant().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getAppKlant().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getAppKlant().getEmail()' }
                Adres: { expression: 'entity.getAppKlant().getAdres()' }
                Postcode: { expression: 'entity.getAppKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getAppKlant().getPlaats()' }
                Mobiel: { expression: 'entity.getAppKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getAppKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getAppKlant().getWerkgebied()' }

    hs.export.vrijwilliger:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - HsBundle\Entity\Vrijwilliger
            -
                Nummer: { expression: 'entity.getVrijwilliger().getId()' }
                Geslacht: { expression: 'entity.getVrijwilliger().getGeslacht()' }
                Voornaam: { expression: 'entity.getVrijwilliger().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getVrijwilliger().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getVrijwilliger().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getVrijwilliger().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getVrijwilliger().getEmail()' }
                Adres: { expression: 'entity.getVrijwilliger().getAdres()' }
                Postcode: { expression: 'entity.getVrijwilliger().getPostcode()' }
                Woonplaats: { expression: 'entity.getVrijwilliger().getPlaats()' }
                Mobiel: { expression: 'entity.getVrijwilliger().getMobiel()' }
                Telefoon: { expression: 'entity.getVrijwilliger().getTelefoon()' }
                Werkgebied: { expression: 'entity.getVrijwilliger().getWerkgebied()' }

    hs.export.registratie:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - HsBundle\Entity\Registratie
            -
#                Nummer: { expression: 'entity.getArbeider().getAppKlant() ? entity.getArbeider().getAppKlant().getId() : entity.getArbeider().getVrijwilliger().getId()' }
                'Dienstverlener/vrijwilliger': { expression: 'entity.getArbeider()' } 
                Activiteit: { expression: 'entity.getActiviteit()' } 
                Klant: { expression: 'entity.getKlus().getAppKlant()' }
                Stadsdeel: { expression: 'entity.getKlus().getAppKlant().getWerkgebied()' }
                Datum: { expression: 'entity.getDatum()', type: 'date' } 
                Starttijd: { expression: 'entity.getStart()', type: 'time' } 
                Eindtijd: { expression: 'entity.getEind()', type: 'time' }
                Uren: { expression: 'entity.getUren()' }
                Dagdelen: { expression: 'entity.getDagdelen()' }
#                Reiskosten:  { expression: 'entity.getReiskosten()' }

    hs.export.klus:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - HsBundle\Entity\Klus
            -
                Status: { expression: 'entity.getStatus()' }
                Startdatum: { expression: 'entity.getStartdatum()', type: 'date' } 
                Einddatum: { expression: 'entity.getEinddatum()', type: 'date' }
                Klant: { expression: 'entity.getAppKlant()' }
                Stadsdeel: { expression: 'entity.getAppKlant().getWerkgebied()' }
                Activiteiten: { expression: 'entity.getActiviteitenAsString()' } 

    hs.export.factuur:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - HsBundle\Entity\Factuur
            -
                Nummer: { expression: 'entity.getNummer()' }
                Datum: { expression: 'entity.getDatum()' }
                Betreft: { expression: 'entity.getBetreft()' }
                Bedrag: { expression: 'entity.getBedrag()', type: 'money' }
                Klant: { expression: 'entity.getAppKlant()' }
                Saldo: { expression: 'entity.getSaldo()', type: 'money' }

    hs.export.betaling:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - HsBundle\Entity\Betaling
            -
                Datum: { expression: 'entity.getDatum()', type: 'date' }
                Referentie: { expression: 'entity.getReferentie()' }
                Factuur: { expression: 'entity.getFactuur()' }
                Klant: { expression: 'entity.getFactuur().getAppKlant()' }
                Bedrag: { expression: 'entity.getBedrag()', type: 'money' }

    hs.export.report:
        public: true
        class: AppBundle\Export\ReportExport
