imports:
    - { resource: daos.yml }
    - { resource: exports.yml }
    - { resource: reports.yml }

services:
    hs.twig.hs_extension:
        class: HsBundle\Twig\HsExtension
        public: false
        tags:
            - { name: twig.extension }

    hs.form.type.klant:
        class: HsBundle\Form\KlantType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    hs.event_subscriber.klant:
        class: HsBundle\Event\KlantUpdater
        tags:
            - { name: doctrine.event_subscriber }
    
    hs.event_subscriber.factuur:
        class: HsBundle\Event\FactuurSubscriber
#        arguments:
#            - "@hs.dao.factuur"
        tags:
            - { name: doctrine.event_subscriber }

    hs.factory.factuur:
        class: HsBundle\Service\FactuurFactory
        arguments:
            - "@hs.dao.factuur"

    hs.form.rapportage:
        class: HsBundle\Form\RapportageType
        tags:
            - { name: form.type }

    hs.data_fixtures.faker_provider:
        class: HsBundle\DataFixtures\HsFakerProvider
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@hs.factory.factuur'
        tags:
            - { name: hautelook_alice.faker.provider }

    hs.data_fixtures.processor:
        class: HsBundle\DataFixtures\HsProcessor
        tags:
            - { name: hautelook_alice.alice.processor }

    hs.event.diensten_lookup_subscriber:
        class: HsBundle\Event\DienstenLookupSubscriber
        arguments:
            - "@hs.dao.dienstverlener"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }
