imports:
    - { resource: daos.yml }
    - { resource: exports.yml }
    - { resource: reports.yml }

services:
    hs.twig.hs_extension:
        class: HsBundle\Twig\HsExtension
        public: false
        tags:
            - { name: twig.extension }

    hs.form.type.klant:
        class: HsBundle\Form\KlantType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type }
            
    hs.event_subscriber.klant:
        class: HsBundle\Event\KlantUpdater
        tags:
            - { name: doctrine.event_subscriber }
    
    hs.event_subscriber.factuur:
        class: HsBundle\Event\FactuurSubscriber
#        arguments:
#            - '@HsBundle\Service\FactuurDao'
        tags:
            - { name: doctrine.event_subscriber }

    hs.factory.factuur:
        class: HsBundle\Service\FactuurFactory
        arguments:
            - '@HsBundle\Service\FactuurDao'

    hs.form.rapportage:
        class: HsBundle\Form\RapportageType
        tags:
            - { name: form.type }

    hs.event.diensten_lookup_subscriber:
        class: HsBundle\Event\DienstenLookupSubscriber
        arguments:
            - '@HsBundle\Service\DienstverlenerDao'
            - '@router'
        tags:
            - { name: kernel.event_subscriber }
