services:
    hs.dao.activiteit:
        parent: app.dao.abstract
        class: HsBundle\Service\ActiviteitDao

    hs.dao.betaling:
        parent: app.dao.abstract
        class: HsBundle\Service\BetalingDao

    hs.dao.declaratiecategorie:
        parent: app.dao.abstract
        class: HsBundle\Service\DeclaratieCategorieDao

    hs.dao.declaratie:
        parent: app.dao.abstract
        class: HsBundle\Service\DeclaratieDao

    hs.dao.dienstverlener:
        parent: app.dao.abstract
        class: HsBundle\Service\DienstverlenerDao

    hs.dao.factuur:
        parent: app.dao.abstract
        class: HsBundle\Service\FactuurDao

    hs.dao.klant:
        parent: app.dao.abstract
        class: HsBundle\Service\KlantDao

    hs.dao.klus:
        parent: app.dao.abstract
        class: HsBundle\Service\KlusDao

    hs.dao.memo:
        parent: app.dao.abstract
        class: HsBundle\Service\MemoDao

    hs.dao.registratie:
        parent: app.dao.abstract
        class: HsBundle\Service\RegistratieDao

    hs.dao.vrijwilliger:
        parent: app.dao.abstract
        class: HsBundle\Service\VrijwilligerDao

    hs.form.type.klant:
        class: HsBundle\Form\KlantType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    hs.subscriber.klant:
        class: HsBundle\Event\KlantUpdater
        tags:
            - { name: doctrine.event_subscriber }

    hs.factory.factuur:
        class: HsBundle\Service\FactuurFactory

    hs.form.rapportage:
        class: HsBundle\Form\RapportageType
        tags:
            - { name: form.type }

    hs.report.klanten.per_stadsdeel:
        class: HsBundle\Report\KlantenPerStadsdeel
        arguments:
            - "@hs.dao.klant"
        tags:
            - { name: hs.rapportage, category: Klanten }

    hs.report.klanten.nieuw_per_stadsdeel:
        class: HsBundle\Report\NieuweKlantenPerStadsdeel
        arguments:
            - "@hs.dao.klant"
        tags:
            - { name: hs.rapportage, category: Klanten }

    hs.report.arbeiders.per_stadsdeel:
        class: HsBundle\Report\ArbeidersPerStadsdeel
        arguments:
            - "@hs.dao.dienstverlener"
            - "@hs.dao.vrijwilliger"
        tags:
            - { name: hs.rapportage, category: Dienstverleners en vrijwilligers }

    hs.report.arbeiders.nieuw_per_stadsdeel:
        class: HsBundle\Report\NieuweArbeidersPerStadsdeel
        arguments:
            - "@hs.dao.dienstverlener"
            - "@hs.dao.vrijwilliger"
        tags:
            - { name: hs.rapportage, category: Dienstverleners en vrijwilligers }

    hs.report.koppelingen.per_stadsdeel:
        class: HsBundle\Report\KoppelingenPerStadsdeel
        arguments:
            - "@hs.dao.klus"
        tags:
            - { name: hs.rapportage, category: Koppelingen }
