services:
    hs.data_fixtures.faker_provider:
        class: HsBundle\DataFixtures\HsFakerProvider
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@hs.factory.factuur'
        tags:
            - { name: nelmio_alice.faker.provider }

    hs.data_fixtures.processor:
        class: HsBundle\DataFixtures\HsProcessor
        tags:
            - { name: hautelook_alice.alice.processor }
