services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    IzBundle\Service\:
        resource: '%kernel.project_dir%/src/IzBundle/Service/'

    IzBundle\Service\HulpaanbodDao:
        calls:
            - method: setHulpsoortenZonderKoppelingen
              arguments:
                  - "%iz_hulpsoorten_zonder_koppelingen%"

    IzBundle\Service\HulpvraagDao:
        calls:
            - method: setHulpsoortenZonderKoppelingen
              arguments:
                  - "%iz_hulpsoorten_zonder_koppelingen%"

    IzBundle\Service\SuccesindicatorDao:
        arguments:
            $class: IzBundle\Entity\Succesindicator

    iz.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@IzBundle\Service\DeelnemerDao' }

    iz.hulpvraag.entities:
        class: ArrayObject
        arguments:
            -
              - { key: klant, dao: '@IzBundle\Service\KlantDao' }

    iz.hulpaanbod.entities:
        class: ArrayObject
        arguments:
            -
              - { key: vrijwilliger, dao: '@IzBundle\Service\VrijwilligerDao' }

    iz.intake.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@IzBundle\Service\DeelnemerDao' }

    iz.lidmaatschap.entities:
        class: ArrayObject
        arguments:
            -
              - { key: intervisiegroep, dao: '@IzBundle\Service\IntervisiegroepDao' }
              - { key: vrijwilliger, dao: '@IzBundle\Service\VrijwilligerDao' }
    
    iz.deelname.entities:
        class: ArrayObject
        arguments:
            -
                - { key: vrijwilliger, dao: '@IzBundle\Service\VrijwilligerDao' }

    iz.verslag.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@IzBundle\Service\DeelnemerDao' }
              - { key: hulpaanbod, dao: '@IzBundle\Service\HulpaanbodDao' }
              - { key: hulpvraag, dao: '@IzBundle\Service\HulpvraagDao' }
              - { key: koppeling, dao: '@IzBundle\Service\KoppelingDao' }
