imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    IzBundle\Command\:
        resource: '%kernel.project_dir%/src/IzBundle/Command'

    IzBundle\Controller\:
        resource: '%kernel.project_dir%/src/IzBundle/Controller'

    IzBundle\Controller\DashboardController:
        arguments:
            $hulpaanbiedingenExport: '@iz.export.hulpaanbiedingen'
            $hulpvragenExport: '@iz.export.hulpvragen'
            $koppelingenExport: '@iz.export.koppelingen'

    IzBundle\Controller\DocumentenController:
        arguments:
           $entities: '@iz.document.entities'

    IzBundle\Controller\EindevaluatiesController:
        arguments:
            $entities: '@iz.verslag.entities'

    IzBundle\Controller\HulpaanbiedingenController:
        arguments:
            $entities: '@iz.hulpaanbod.entities'
            $export: '@iz.export.hulpaanbiedingen'

    IzBundle\Controller\HulpvragenController:
        arguments:
            $entities: '@iz.hulpvraag.entities'
            $export: '@iz.export.hulpvragen'

    IzBundle\Controller\IntakesController:
        arguments:
            $entities: '@iz.intake.entities'
            $export: '@iz.export.klanten'

    IzBundle\Controller\IntervisiegroepenController:
        arguments:
            $export: '@iz.export.intervisiegroepen'
            $vrijwilligersExport: '@iz.export.vrijwilligers'

    IzBundle\Controller\KlantenController:
        arguments:
            $export: '@iz.export.klanten'

    IzBundle\Controller\KoppelingenController:
        arguments:
            $export: '@iz.export.koppelingen'

    IzBundle\Controller\LidmaatschappenController:
        arguments:
            $entities: '@iz.lidmaatschap.entities'

    IzBundle\Controller\RapportagesController:
        arguments:
            $export: '@iz.export.report'
            $reports: !tagged_iterator iz.rapportage

    IzBundle\Controller\TussenevaluatiesController:
        arguments:
            $entities: '@iz.verslag.entities'

    IzBundle\Controller\VerslagenController:
        arguments:
            $entities: '@iz.verslag.entities'

    IzBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@iz.export.vrijwilligers'

    IzBundle\Controller\DeelnamesController:
        arguments:
            $entities: '@iz.deelname.entities'

    IzBundle\Event\DienstenLookupSubscriber:

    IzBundle\Event\DienstenVrijwilligerLookupSubscriber:

    iz.repository.doelstelling:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - IzBundle\Entity\Doelstelling

    iz.repository.iz_hulpvraag:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - IzBundle\Entity\Hulpvraag

    iz.repository.iz_klant:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - IzBundle\Entity\IzKlant

    IzBundle\Repository\ProjectRepository:
        factory: ["@doctrine", getRepository]
        arguments:
            - IzBundle\Entity\Project
        tags:
            - app.doelstelling

    iz.repository.iz_vrijwilliger:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - IzBundle\Entity\IzVrijwilliger

    IzBundle\Form\IzRapportageType:

    IzBundle\Twig\IzExtension:

    IzBundle\Event\IntakeEventSubscriber:
        arguments:
            - '@event_dispatcher'

    koppeling_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
             - IzBundle\Entity\Koppeling

    IzBundle\Repository\KoppelingenRepository:
        arguments:
            $class: "@koppeling_metadata"
        calls:
            - method: setHulpvraagRepository
              arguments:
                - "@iz.repository.iz_hulpvraag"
            - method: setSpecifiekeProjecten
              arguments:
                  - "%iz_specifieke_projecten%"
        tags:
            - app.doelstelling

when@dev: &dev
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        IzBundle\DataFixtures\IzFakerProvider:

when@test: *dev
