services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    GaBundle\Service\:
        resource: '%kernel.project_dir%/src/GaBundle/Service/'

    GaBundle\Service\KlantLidmaatschapDao:
        arguments:
            $itemsPerPage: 100

    GaBundle\Service\VrijwilligerLidmaatschapDao:
        arguments:
            $itemsPerPage: 100

    ga.repository.groep_buurtmaatjes:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - GaBundle\Entity\GroepBuurtmaatjes
        tags:
            - {name: 'ga.groep_type', title: 'Buurtmaatjes'}

    ga.repository.groep_eropuit:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - GaBundle\Entity\GroepErOpUit
        tags:
            - {name: 'ga.groep_type', title: 'ErOpUit'}

    ga.repository.groep_kwartiermaken:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - GaBundle\Entity\GroepKwartiermaken
        tags:
            - {name: 'ga.groep_type', title: 'Kwartiermaken'}

    ga.repository.groep_openhuis:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - GaBundle\Entity\GroepOpenHuis
        tags:
            - {name: 'ga.groep_type', title: 'OpenHuis'}

    ga.repository.groep_organisatie:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - GaBundle\Entity\GroepOrganisatie
        tags:
            - {name: 'ga.groep_type', title: 'Organisatie'}

    ga.repository.groep_iz:
        class: Doctrine\ORM\EntityRepository
        factory: [ "@doctrine", getRepository ]
        arguments:
            - GaBundle\Entity\GroepIZ
        tags:
            - {name: 'ga.groep_type', title: 'IZ'}

    ga.activiteit.entities:
        class: ArrayObject
        arguments:
            -
              - { key: null }
              - { key: groep, dao: '@GaBundle\Service\GroepDao' }

    ga.deelname.entities:
        class: ArrayObject
        arguments:
            -
              - { key: activiteit, dao: '@GaBundle\Service\ActiviteitDao' }
              - { key: dossier, dao: '@GaBundle\Service\DossierDao' }

    ga.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: vrijwilliger, dao: '@AppBundle\Service\VrijwilligerDao' }

    ga.memo.entities:
        class: ArrayObject
        arguments:
            - - { key: vrijwilliger, dao: '@AppBundle\Service\VrijwilligerDao' }

    ga.intake.entities:
        class: ArrayObject
        arguments:
            -
              - { key: dossier, dao: '@GaBundle\Service\DossierDao' }

    ga.lidmaatschap.entities:
        class: ArrayObject
        arguments:
            -
              - { key: dossier, dao: '@GaBundle\Service\DossierDao' }
              - { key: groep, dao: '@GaBundle\Service\GroepDao' }

    ga.verslag.entities:
        class: ArrayObject
        arguments:
            -
              - { key: dossier, dao: '@GaBundle\Service\DossierDao' }
