imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    _defaults:
      autowire: true
      autoconfigure: true

    GaBundle\Command\:
      resource: '%kernel.project_dir%/src/GaBundle/Command'

    GaBundle\Controller\:
      resource: '%kernel.project_dir%/src/GaBundle/Controller'

    GaBundle\Controller\IntakesController:
      arguments:
        $entities: '@ga.intake.entities'

    GaBundle\Controller\RapportagesController:
      arguments:
        $export: '@ga.export.report'
        $reports: !tagged_iterator ga.rapportage

    GaBundle\Controller\DeelnamesController:
      arguments:
        $entities: '@ga.deelname.entities'

    GaBundle\Controller\DocumentenController:
      arguments:
        $entities: '@ga.document.entities'

    GaBundle\Controller\LidmaatschappenController:
      arguments:
        $entities: '@ga.lidmaatschap.entities'

    GaBundle\Controller\ActiviteitenController:
      arguments:
        $entities: '@ga.activiteit.entities'
        $export: '@ga.export.activiteiten'

    GaBundle\Controller\ActiviteitenreeksController:
      arguments:
        $entities: '@ga.activiteit.entities'

    GaBundle\Controller\GroepenController:
      arguments:
        $export: '@ga.export.groepen'

    GaBundle\Controller\MemosController:
      arguments:
        $entities: '@ga.memo.entities'

    GaBundle\Controller\VerslagenController:
      arguments:
        $entities: '@ga.verslag.entities'

    GaBundle\Controller\VrijwilligerdossiersController:
      arguments:
        $export: '@ga.export.vrijwilligerdossiers'

    GaBundle\Controller\KlantdossiersController:
      arguments:
        $export: '@ga.export.klantdossiers'

    GaBundle\Event\DienstenLookupSubscriber:

    GaBundle\Form\RapportageType:

    GaBundle\Report\DeelnemersTotaal:
        arguments:
            -
              Buurtmaatjes: "@ga.repository.groep_buurtmaatjes"
              ErOpUit: "@ga.repository.groep_eropuit"
              Kwartiermaken: "@ga.repository.groep_kwartiermaken"
              Open Huis: "@ga.repository.groep_openhuis"
              Organisatie: "@ga.repository.groep_organisatie"
        tags:
            - { name: ga.rapportage, title: Deelnemers totaal }

    GaBundle\Report\DeelnemersPerGroep:
        arguments:
            -
              Buurtmaatjes: "@ga.repository.groep_buurtmaatjes"
              ErOpUit: "@ga.repository.groep_eropuit"
              Kwartiermaken: "@ga.repository.groep_kwartiermaken"
              Open Huis: "@ga.repository.groep_openhuis"
              Organisatie: "@ga.repository.groep_organisatie"
        tags:
            - { name: ga.rapportage, title: Deelnemers per groep }

    GaBundle\Report\DeelnemersPerStadsdeel:
        arguments:
            -
              Buurtmaatjes: "@ga.repository.groep_buurtmaatjes"
              ErOpUit: "@ga.repository.groep_eropuit"
              Kwartiermaken: "@ga.repository.groep_kwartiermaken"
              Open Huis: "@ga.repository.groep_openhuis"
              Organisatie: "@ga.repository.groep_organisatie"
        tags:
            - { name: ga.rapportage, title: Deelnemers per stadsdeel }

    GaBundle\Report\DeelnemersPerGroepStadsdeel:
        arguments:
            -
              Buurtmaatjes: "@ga.repository.groep_buurtmaatjes"
              ErOpUit: "@ga.repository.groep_eropuit"
              Kwartiermaken: "@ga.repository.groep_kwartiermaken"
              Open Huis: "@ga.repository.groep_openhuis"
              Organisatie: "@ga.repository.groep_organisatie"
        tags:
            - { name: ga.rapportage, title: Deelnemers per groep en stadsdeel }

    GaBundle\Report\VrijwilligersTotaal:
        arguments:
            -
              Buurtmaatjes: "@ga.repository.groep_buurtmaatjes"
              ErOpUit: "@ga.repository.groep_eropuit"
              Kwartiermaken: "@ga.repository.groep_kwartiermaken"
              Open Huis: "@ga.repository.groep_openhuis"
              Organisatie: "@ga.repository.groep_organisatie"
        tags:
            - { name: ga.rapportage, title: Buurtmaatjes vrijwilligers totaal }

    GaBundle\Report\VrijwilligersPerGroep:
        arguments:
            -
              Buurtmaatjes: "@ga.repository.groep_buurtmaatjes"
              ErOpUit: "@ga.repository.groep_eropuit"
              Kwartiermaken: "@ga.repository.groep_kwartiermaken"
              Open Huis: "@ga.repository.groep_openhuis"
              Organisatie: "@ga.repository.groep_organisatie"
        tags:
            - { name: ga.rapportage, title: Buurtmaatjes vrijwilligers per groep }

    GaBundle\Report\VrijwilligersPerGroepStadsdeel:
        arguments:
            -
              Buurtmaatjes: "@ga.repository.groep_buurtmaatjes"
              ErOpUit: "@ga.repository.groep_eropuit"
              Kwartiermaken: "@ga.repository.groep_kwartiermaken"
              Open Huis: "@ga.repository.groep_openhuis"
              Organisatie: "@ga.repository.groep_organisatie"
        tags:
            - { name: ga.rapportage, title: Buurtmaatjes vrijwilligers per groep en stadsdeel }

    groep_metadata:
      class: Doctrine\ORM\Mapping\ClassMetadata
      arguments:
        - 'GaBundle\Entity\Groep'

    GaBundle\Repository\GroepRepository:
      arguments:
        $class: "@groep_metadata"
      tags:
        - app.doelstelling
