imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    _defaults:
      autowire: true
      autoconfigure: true

    GaBundle\Command\:
      resource: '%kernel.project_dir%/src/GaBundle/Command'

    GaBundle\Controller\:
      resource: '%kernel.project_dir%/src/GaBundle/Controller'

    GaBundle\Controller\IntakesController:
      arguments:
        $entities: '@ga.intake.entities'

    GaBundle\Controller\RapportagesController:
      arguments:
        $export: '@ga.export.report'
        $reports: !tagged_iterator ga.rapportage

    GaBundle\Controller\DeelnamesController:
      arguments:
        $entities: '@ga.deelname.entities'

    GaBundle\Controller\DocumentenController:
      arguments:
        $entities: '@ga.document.entities'

    GaBundle\Controller\LidmaatschappenController:
      arguments:
        $dao: '@GaBundle\Service\LidmaatschapDao'
        $entities: '@ga.lidmaatschap.entities'

    GaBundle\Controller\ActiviteitenController:
      arguments:
        $entities: '@ga.activiteit.entities'
        $export: '@ga.export.activiteiten'

    GaBundle\Controller\ActiviteitenreeksController:
      arguments:
        $entities: '@ga.activiteit.entities'

    GaBundle\Controller\GroepenController:
      arguments:
        $klantLidmaatschapDao: '@GaBundle\Service\KlantLidmaatschapDao'
        $vrijwilligerLidmaatschapDao: '@GaBundle\Service\VrijwilligerLidmaatschapDao'
        $export: '@ga.export.groepen'

    GaBundle\Controller\MemosController:
      arguments:
        $entities: '@ga.memo.entities'

    GaBundle\Controller\VerslagenController:
      arguments:
        $entities: '@ga.verslag.entities'

    GaBundle\Controller\VrijwilligerdossiersController:
      arguments:
        $export: '@ga.export.vrijwilligerdossiers'

    GaBundle\Controller\KlantdossiersController:
      arguments:
        $export: '@ga.export.klantdossiers'

    GaBundle\Event\DienstenLookupSubscriber:

    GaBundle\Event\DienstenVrijwilligerLookupSubscriber:

    GaBundle\Form\RapportageType:

    GaBundle\Report\DeelnemersTotaal:
        tags: ['ga.rapportage']

    GaBundle\Report\DeelnemersPerGroep:
        tags: ['ga.rapportage']

    GaBundle\Report\DeelnemersPerStadsdeel:
        tags: ['ga.rapportage']

    GaBundle\Report\DeelnemersPerGroepStadsdeel:
        tags: ['ga.rapportage']

    GaBundle\Report\VrijwilligersTotaal:
        tags: ['ga.rapportage']

    GaBundle\Report\VrijwilligersPerGroep:
        tags: ['ga.rapportage']

    GaBundle\Report\VrijwilligersPerGroepStadsdeel:
        tags: ['ga.rapportage']

    groep_metadata:
      class: Doctrine\ORM\Mapping\ClassMetadata
      arguments:
        - 'GaBundle\Entity\Groep'

    GaBundle\Repository\GroepRepository:
      arguments:
        $class: "@groep_metadata"
      tags:
        - app.doelstelling
