services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    ClipBundle\Service\:
        resource: '%kernel.project_dir%/src/ClipBundle/Service/'

    clip.memo.entities:
        class: ArrayObject
        arguments:
            - - { key: vrijwilliger, dao: '@ClipBundle\Service\VrijwilligerDao' }
              -
    clip.deelname.entities:
        class: ArrayObject
        arguments:
            - - { key: vrijwilliger, dao: '@ClipBundle\Service\VrijwilligerDao' }
