services:
    _defaults:
        autowire: true
        autoconfigure: true

    clip.export.vrijwilliger:
        class: AppBundle\Export\GenericExport
        arguments:
            - ClipBundle\Entity\Vrijwilliger
            - Nummer: { expression: 'entity.getVrijwilliger().getId()' }
              Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
              Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
              Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
              Geslacht: { expression: 'entity.getVrijwilliger().getGeslacht()' }
              Voornaam: { expression: 'entity.getVrijwilliger().getVoornaam()' }
              Tussenvoegsel: { expression: 'entity.getVrijwilliger().getTussenvoegsel()' }
              Achternaam: { expression: 'entity.getVrijwilliger().getAchternaam()' }
              Geboortedatum: { expression: 'entity.getVrijwilliger().getGeboortedatum()', type: 'date' }
              Adres: { expression: 'entity.getVrijwilliger().getAdres()' }
              Postcode: { expression: 'entity.getVrijwilliger().getPostcode()' }
              Woonplaats: { expression: 'entity.getVrijwilliger().getPlaats()' }
              E-mail: { expression: 'entity.getVrijwilliger().getEmail()' }
              Mobiel: { expression: 'entity.getVrijwilliger().getMobiel()' }
              Telefoon: { expression: 'entity.getVrijwilliger().getTelefoon()' }
              Werkgebied: { expression: 'entity.getVrijwilliger().getWerkgebied()' }
              GGW-gebied: { expression: 'entity.getVrijwilliger().getPostcodegebied()' }
              Stagiair: { expression: 'entity.isStagiair()' }
              Postvoorkeur: { expression: 'entity.getVrijwilliger().getGeenPost()==false?"Post":"Geen Post"' }
              Emailvoorkeur: { expression: 'entity.getVrijwilliger().getGeenEmail()==false?"Email":"Geen Email"' }
              Medewerker Intake: { expression: 'entity.getMedewerker()' }
              Medewerker Locatie: { expression: 'entity.getMedewerkerLocatie()' }
              Binnengekomen via: { expression: 'entity.getBinnenVia()' }
              Locaties: { expression: 'entity.getLocaties()' }
              VOG aangevraagd: { expression: 'entity.getVrijwilliger().getVogAangevraagd()' }
              VOG aanwezig: { expression: 'entity.getVrijwilliger().getVogAanwezig()' }
              Overeenkomst aanwezig: { expression: 'entity.getVrijwilliger().getOvereenkomstAanwezig()' }

    clip.export.clienten:
        class: AppBundle\Export\GenericExport
        arguments:
            - ClipBundle\Entity\Client
            -
                # client
                Nummer client: { expression: 'entity.getId()' }
                Geslacht client: { expression: 'entity.getGeslacht()' }
                Voornaam client: { expression: 'entity.getVoornaam()' }
                Tussenvoegsel client: { expression: 'entity.getTussenvoegsel()' }
                Achternaam client: { expression: 'entity.getAchternaam()' }
                Geboortedatum client: { expression: 'entity.getGeboortedatum()', type: 'date' }
                E-mail client: { expression: 'entity.getEmail()' }
                Adres client: { expression: 'entity.getAdres()' }
                Postcode client: { expression: 'entity.getPostcode()' }
                Woonplaats client: { expression: 'entity.getPlaats()' }
                Mobiel client: { expression: 'entity.getMobiel()' }
                Telefoon client: { expression: 'entity.getTelefoon()' }
                Werkgebied client: { expression: 'entity.getWerkgebied()' }
                Aanmelddatum client: { expression: 'entity.getAanmelddatum()', type: 'date' }

    clip.export.vragen:
        class: AppBundle\Export\GenericExport
        arguments:
            - ClipBundle\Entity\Vraag
            -
                # vraag
                Nummer vraag: { expression: 'entity.getId()' }
                Onderwerp vraag: { expression: 'entity.getSoort()' }
                Medewerker vraag: { expression: 'entity.getBehandelaar()' }
                Startdatum vraag: { expression: 'entity.getStartdatum()', type: 'date' }
                Afsluitdatum vraag: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                # client
                Nummer client: { expression: 'entity.getClient().getId()' }
                Geslacht client: { expression: 'entity.getClient().getGeslacht()' }
                Voornaam client: { expression: 'entity.getClient().getVoornaam()' }
                Tussenvoegsel client: { expression: 'entity.getClient().getTussenvoegsel()' }
                Achternaam client: { expression: 'entity.getClient().getAchternaam()' }
                Geboortedatum client: { expression: 'entity.getClient().getGeboortedatum()', type: 'date' }
                E-mail client: { expression: 'entity.getClient().getEmail()' }
                Adres client: { expression: 'entity.getClient().getAdres()' }
                Postcode client: { expression: 'entity.getClient().getPostcode()' }
                Woonplaats client: { expression: 'entity.getClient().getPlaats()' }
                Mobiel client: { expression: 'entity.getClient().getMobiel()' }
                Telefoon client: { expression: 'entity.getClient().getTelefoon()' }
                Werkgebied client: { expression: 'entity.getClient().getWerkgebied()' }
                Aanmelddatum client: { expression: 'entity.getClient().getAanmelddatum()', type: 'date' }

    clip.export.contactmomenten:
        class: AppBundle\Export\GenericExport
        arguments:
            - ClipBundle\Entity\Contactmoment
            -
                # contactmoment
                Medewerker contactmoment: { expression: 'entity.getBehandelaar()' }
                Datum contactmoment: { expression: 'entity.getDatum()', type: 'date' }
                Verslag contactmoment: { expression: 'entity.getOpmerking()' }
                # vraag
                Nummer vraag: { expression: 'entity.getVraag().getId()' }
                Onderwerp vraag: { expression: 'entity.getVraag().getSoort()' }
                Medewerker vraag: { expression: 'entity.getVraag().getBehandelaar()' }
                Startdatum vraag: { expression: 'entity.getVraag().getStartdatum()', type: 'date' }
                Afsluitdatum vraag: { expression: 'entity.getVraag().getAfsluitdatum()', type: 'date' }
                # client
                Nummer client: { expression: 'entity.getVraag().getClient().getId()' }
                Geslacht client: { expression: 'entity.getVraag().getClient().getGeslacht()' }
                Voornaam client: { expression: 'entity.getVraag().getClient().getVoornaam()' }
                Tussenvoegsel client: { expression: 'entity.getVraag().getClient().getTussenvoegsel()' }
                Achternaam client: { expression: 'entity.getVraag().getClient().getAchternaam()' }
                Geboortedatum client: { expression: 'entity.getVraag().getClient().getGeboortedatum()', type: 'date' }
                E-mail client: { expression: 'entity.getVraag().getClient().getEmail()' }
                Adres client: { expression: 'entity.getVraag().getClient().getAdres()' }
                Postcode client: { expression: 'entity.getVraag().getClient().getPostcode()' }
                Woonplaats client: { expression: 'entity.getVraag().getClient().getPlaats()' }
                Mobiel client: { expression: 'entity.getVraag().getClient().getMobiel()' }
                Telefoon client: { expression: 'entity.getVraag().getClient().getTelefoon()' }
                Werkgebied client: { expression: 'entity.getVraag().getClient().getWerkgebied()' }
                Aanmelddatum client: { expression: 'entity.getVraag().getClient().getAanmelddatum()', type: 'date' }

    clip.export.report:
        class: AppBundle\Export\ReportExport
