services:
    _defaults:
        autowire: true
        autoconfigure: true

    ClipBundle\Form\RapportageType:

    ClipBundle\Report\VragenPerCommunicatiekanaal:
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    ClipBundle\Report\VragenPerEtniciteit:
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    ClipBundle\Report\VragenPerGeslacht:
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    ClipBundle\Report\VragenPerViacategorie:
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    ClipBundle\Report\VragenPerHulpvrager:
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    ClipBundle\Report\VragenPerLeeftijdscategorie:
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    ClipBundle\Report\VragenPerMaand:
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    ClipBundle\Report\VragenPerStadsdeel:
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    ClipBundle\Report\VragenPerVraagsoort:
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    ClipBundle\Report\VragenPerWoonplaats:
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }
