imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ClipBundle\Controller\:
      resource: '%kernel.project_dir%/src/ClipBundle/Controller'

    ClipBundle\Controller\ClientenController:
      arguments:
        $export: '@clip.export.clienten'

    ClipBundle\Controller\OpenstaandeVragenController:
      arguments:
        $export: '@clip.export.vragen'

    ClipBundle\Controller\RapportagesController:
      arguments:
        $export: '@clip.export.report'
        $reports: !tagged_iterator clip.rapportage

    ClipBundle\Controller\MemosController:
      arguments:
        $entities: '@clip.memo.entities'

    ClipBundle\Controller\DeelnamesController:
      arguments:
        $entities: '@clip.deelname.entities'

    ClipBundle\Controller\DocumentenController:
      arguments:
        $entities: '@clip.document.entities'

    ClipBundle\Controller\ContactmomentenController:
      arguments:
        $export: '@clip.export.contactmomenten'
        $entities: '@clip.contactmoment.entities'

    ClipBundle\Controller\VrijwilligersController:
      arguments:
        $export: '@clip.export.vrijwilliger'

    ClipBundle\Controller\VragenController:
      arguments:
        $export: '@clip.export.vragen'
        $entities: '@clip.vraag.entities'

    clip.contactmoment.entities:
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@ClipBundle\Service\ClientDao' }
              - { key: vraag, dao: '@ClipBundle\Service\VraagDao' }

    clip.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@ClipBundle\Service\ClientDao' }
              - { key: vraag, dao: '@ClipBundle\Service\VraagDao' }
              - { key: vrijwilliger, dao: '@ClipBundle\Service\VrijwilligerDao' }

    clip.vraag.entities:
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@ClipBundle\Service\ClientDao' }

    clip.event_subscriber.postcode:
        class: ClipBundle\Event\PostcodeSubscriber
        tags:
          - doctrine.event_subscriber
