services:
    odp.export.huurders:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - OdpBundle\Entity\Huurder
            -
                Nummer: { expression: 'entity.getKlant().getId()' }
                Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Geslacht: { expression: 'entity.getKlant().getGeslacht()' }
                Voornaam: { expression: 'entity.getKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getKlant().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getKlant().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getKlant().getEmail()' }
                Adres: { expression: 'entity.getKlant().getAdres()' }
                Postcode: { expression: 'entity.getKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getKlant().getPlaats()' }
                Mobiel: { expression: 'entity.getKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getKlant().getWerkgebied()' }
                Project(en): { expression: 'entity.getProjecten()' }
                WPI: { expression: 'entity.isWpi() ? "ja" : "nee"' }
                Automatische incasso: { expression: 'entity.isAutomatischeIncasso() ? "ja" : "nee"' }
                Inschrijving Woningnet: { expression: 'entity.isInschrijvingWoningnet() ? "ja" : "nee"' }
                WA-polis: { expression: 'entity.isWaPolis() ? "ja" : "nee"' }
                Postvoorkeur: { expression: 'entity.getKlant().getGeenPost() ? "Geen post" : "Wel post"' }
                E-mailvoorkeur: { expression: 'entity.getKlant().getGeenEmail() ? "Geen e-mail" : "Wel e-mail"' }
                Is gekoppeld: { expression: 'entity.isGekoppeld() ? "Ja" : "Nee"' }

    odp.export.verhuurders:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - OdpBundle\Entity\Verhuurder
            -
                Nummer: { expression: 'entity.getKlant().getId()' }
                Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Geslacht: { expression: 'entity.getKlant().getGeslacht()' }
                Voornaam: { expression: 'entity.getKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getKlant().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getKlant().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getKlant().getEmail()' }
                Adres: { expression: 'entity.getKlant().getAdres()' }
                Postcode: { expression: 'entity.getKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getKlant().getPlaats()' }
                Mobiel: { expression: 'entity.getKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getKlant().getWerkgebied()' }
                Project: { expression: 'entity.getProject()' }
                WPI: { expression: 'entity.isWpi() ? "ja" : "nee"' }
                Postvoorkeur: { expression: 'entity.getKlant().getGeenPost() ? "Geen post" : "Wel post"' }
                E-mailvoorkeur: { expression: 'entity.getKlant().getGeenEmail() ? "Geen e-mail" : "Wel e-mail"' }
                Is gekoppeld: { expression: 'entity.isGekoppeld() ? "Ja" : "Nee"' }

    odp.export.huurverzoeken:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - OdpBundle\Entity\Huurverzoek
            -
                Nummer: { expression: 'entity.getId()' }
                Huurder: { expression: 'entity.getHuurder()' }
                Stadsdeel: { expression: 'entity.getHuurder().getKlant().getWerkgebied()' }
                Project(en): { expression: 'entity.getProjecten()' }
                Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }

    odp.export.huuraanbiedingen:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - OdpBundle\Entity\Huuraanbod
            -
                Nummer: { expression: 'entity.getId()' }
                Verhuurder: { expression: 'entity.getVerhuurder()' }
                Stadsdeel: { expression: 'entity.getVerhuurder().getKlant().getWerkgebied()' }
                Project: { expression: 'entity.getProject()' }
                Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }

    odp.export.koppelingen:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - OdpBundle\Entity\Huurovereenkomst
            -
                Nummer: { expression: 'entity.getId()' }
                Huurder: { expression: 'entity.getHuurder()' }
                Verhuurder: { expression: 'entity.getVerhuurder()' }
                Project: { expression: 'entity.getHuuraanbod().getProject()' }
                Medewerker: { expression: 'entity.getMedewerker()' }
                Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
                Opzegdatum: { expression: 'entity.getOpzegdatum()', type: 'date' }
                Einddatum: { expression: 'entity.getEinddatum()', type: 'date' }
                Plaats: { expression: 'entity.getVerhuurder().getKlant().getPlaats()' }
                Vorm: { expression: 'entity.getVorm()' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Automatische incasso: { expression: 'entity.getHuurder().isAutomatischeIncasso() ? "ja" : "nee"' }
                Inschrijving Woningnet: { expression: 'entity.getHuurder().isInschrijvingWoningnet() ? "ja" : "nee"' }
                WA-polis: { expression: 'entity.getHuurder().isWaPolis() ? "ja" : "nee"' }

    odp.export.vrijwilliger:
        public: true
        class: AppBundle\Export\GenericExport
        arguments:
            - OdpBundle\Entity\Vrijwilliger
            -
                Nummer: { expression: 'entity.getVrijwilliger().getId()' }
                Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
                Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Geslacht: { expression: 'entity.getVrijwilliger().getGeslacht()' }
                Voornaam: { expression: 'entity.getVrijwilliger().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getVrijwilliger().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getVrijwilliger().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getVrijwilliger().getGeboortedatum()', type: 'date' }
                Adres: { expression: 'entity.getVrijwilliger().getAdres()' }
                Postcode: { expression: 'entity.getVrijwilliger().getPostcode()' }
                Woonplaats: { expression: 'entity.getVrijwilliger().getPlaats()' }
                E-mail: { expression: 'entity.getVrijwilliger().getEmail()' }
                Mobiel: { expression: 'entity.getVrijwilliger().getMobiel()' }
                Telefoon: { expression: 'entity.getVrijwilliger().getTelefoon()' }
                Werkgebied: { expression: 'entity.getVrijwilliger().getWerkgebied()' }
                GGW-gebied: { expression: 'entity.getVrijwilliger().getPostcodegebied()' }
                Stagiair: { expression: 'entity.isStagiair()' }
                Postvoorkeur: { expression: 'entity.getVrijwilliger().getGeenPost()==false?"Post":"Geen Post"' }
                Emailvoorkeur: { expression: 'entity.getVrijwilliger().getGeenEmail()==false?"Email":"Geen Email"' }
                Medewerker Intake: { expression: 'entity.getMedewerker()' }
                Medewerker Locatie: { expression: 'entity.getMedewerkerLocatie()' }
                Binnengekomen via: { expression: 'entity.getBinnenVia()' }
                Locaties: { expression: 'entity.getLocaties()' }
                VOG aangevraagd: { expression: 'entity.getVrijwilliger().getVogAangevraagd()' }
                VOG aanwezig: { expression: 'entity.getVrijwilliger().getVogAanwezig()' }
                Overeenkomst aanwezig: { expression: 'entity.getVrijwilliger().getOvereenkomstAanwezig()' }


    odp.export.report:
        public: true
        class: AppBundle\Export\ReportExport
