services:
    odp.form.rapportage:
        class: OdpBundle\Form\RapportageType
        tags:
            - { name: form.type }

    OdpBundle\Report\Huurders:
        public: true
        arguments:
            - '@OdpBundle\Service\HuurderDao'
        tags:
            - { name: odp.rapportage }

    OdpBundle\Report\Koppelingen:
        public: true
        arguments:
            - '@OdpBundle\Service\HuurovereenkomstDao'
            - '@OdpBundle\Service\ProjectDao'
        tags:
            - { name: odp.rapportage }

    OdpBundle\Report\Verhuurders:
        public: true
        arguments:
            - '@OdpBundle\Service\VerhuurderDao'
        tags:
            - { name: odp.rapportage }

