services:
    odp.form.rapportage:
        class: OdpBundle\Form\RapportageType
        tags:
            - { name: form.type }

    OdpBundle\Report\Huurders:
        arguments:
            - '@OdpBundle\Service\HuurderDao'
        tags:
            - { name: odp.rapportage }

    OdpBundle\Report\KoppelingenPerWoningbouwcorporatie:
        arguments:
            - "@odp.dao.huurovereenkomst"
        tags:
            - { name: odp.rapportage }

    OdpBundle\Report\Verhuurders:
        arguments:
            - '@OdpBundle\Service\VerhuurderDao'
        tags:
            - { name: odp.rapportage }

