odp_annotations:
    resource: "@OdpBundle/Controller"
    type: annotation

odp_index:
    path: /odp
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: odp_huurders_index
