odp_annotations:
    resource: "@OdpBundle/Controller"
    type: annotation

odp_index:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: odp_huurders_index
