imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    OdpBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    odp.event.diensten_lookup_subscriber:
        class: OdpBundle\Event\DienstenLookupSubscriber
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }
