services:
    clip.export.clienten:
        class: AppBundle\Export\GenericExport
        arguments:
            - ClipBundle\Entity\Client
            -
                Nummer: { expression: 'entity.getId()' }
                Geslacht: { expression: 'entity.getGeslacht()' }
                Voornaam: { expression: 'entity.getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getAchternaam()' }
                Geboortedatum: { expression: 'entity.getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getEmail()' }
                Adres: { expression: 'entity.getAdres()' }
                Postcode: { expression: 'entity.getPostcode()' }
                Woonplaats: { expression: 'entity.getPlaats()' }
                Mobiel: { expression: 'entity.getMobiel()' }
                Telefoon: { expression: 'entity.getTelefoon()' }
                Werkgebied: { expression: 'entity.getWerkgebied()' }
                Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }

    clip.export.vragen:
        class: AppBundle\Export\GenericExport
        arguments:
            - ClipBundle\Entity\Vraag
            -
                Nummer: { expression: 'entity.getId()' }
                Onderwerp: { expression: 'entity.getSoort()' }
                Medewerker: { expression: 'entity.getBehandelaar()' }
                Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Geslacht: { expression: 'entity.getClient().getGeslacht()' }
                Voornaam: { expression: 'entity.getClient().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getClient().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getClient().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getClient().getGeboortedatum()', type: 'date' }
                E-mail: { expression: 'entity.getClient().getEmail()' }
                Adres: { expression: 'entity.getClient().getAdres()' }
                Postcode: { expression: 'entity.getClient().getPostcode()' }
                Woonplaats: { expression: 'entity.getClient().getPlaats()' }
                Mobiel: { expression: 'entity.getClient().getMobiel()' }
                Telefoon: { expression: 'entity.getClient().getTelefoon()' }
                Werkgebied: { expression: 'entity.getClient().getWerkgebied()' }
                Aanmelddatum: { expression: 'entity.getClient().getAanmelddatum()', type: 'date' }

    clip.export.contactmomenten:
        class: AppBundle\Export\GenericExport
        arguments:
            - ClipBundle\Entity\Contactmoment
            -
                Vraagnummer: { expression: 'entity.getVraag().getId()' }
                Onderwerp: { expression: 'entity.getVraag().getSoort()' }
                Medewerker: { expression: 'entity.getBehandelaar()' }
                Datum: { expression: 'entity.getDatum()', type: 'date' }
                Verslag: { expression: 'entity.getOpmerking()' }

    clip.export.report:
        class: AppBundle\Export\ReportExport
