services:
    clip.form.rapportage:
        class: ClipBundle\Form\RapportageType
        tags:
            - { name: form.type }

    clip.report.contactmomenten_per_geslacht:
        class: ClipBundle\Report\ContactmomentenPerGeslacht
        arguments:
            - "@clip.dao.contactmoment"
        tags:
            - { name: clip.rapportage, category: Contactmomenten }

    clip.report.contactmomenten_per_geboorteland:
        class: ClipBundle\Report\ContactmomentenPerGeboorteland
        arguments:
            - "@clip.dao.contactmoment"
        tags:
            - { name: clip.rapportage, category: Contactmomenten }

    clip.report.contactmomenten_per_viacategorie:
        class: ClipBundle\Report\ContactmomentenPerViacategorie
        arguments:
            - "@clip.dao.contactmoment"
        tags:
            - { name: clip.rapportage, category: Contactmomenten }

    clip.report.contactmomenten_per_hulpvrager:
        class: ClipBundle\Report\ContactmomentenPerHulpvrager
        arguments:
            - "@clip.dao.contactmoment"
        tags:
            - { name: clip.rapportage, category: Contactmomenten }

    clip.report.contactmomenten_per_leeftijdscategorie:
        class: ClipBundle\Report\ContactmomentenPerLeeftijdscategorie
        arguments:
            - "@clip.dao.contactmoment"
        tags:
            - { name: clip.rapportage, category: Contactmomenten }

    clip.report.contactmomenten_per_communicatiekanaal:
        class: ClipBundle\Report\ContactmomentenPerCommunicatiekanaal
        arguments:
            - "@clip.dao.contactmoment"
        tags:
            - { name: clip.rapportage, category: Contactmomenten }

    clip.report.contactmomenten_per_nationaliteit:
        class: ClipBundle\Report\ContactmomentenPerNationaliteit
        arguments:
            - "@clip.dao.contactmoment"
        tags:
            - { name: clip.rapportage, category: Contactmomenten }

    clip.report.contactmomenten_per_vraagsoort:
        class: ClipBundle\Report\ContactmomentenPerVraagsoort
        arguments:
            - "@clip.dao.contactmoment"
        tags:
            - { name: clip.rapportage, category: Contactmomenten }

    clip.report.contactmomenten_per_woonplaats:
        class: ClipBundle\Report\ContactmomentenPerWoonplaats
        arguments:
            - "@clip.dao.contactmoment"
        tags:
            - { name: clip.rapportage, category: Contactmomenten }

    clip.report.vragen_per_geslacht:
        class: ClipBundle\Report\VragenPerGeslacht
        arguments:
            - "@clip.dao.vraag"
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_geboorteland:
        class: ClipBundle\Report\VragenPerGeboorteland
        arguments:
            - "@clip.dao.vraag"
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_viacategorie:
        class: ClipBundle\Report\VragenPerViacategorie
        arguments:
            - "@clip.dao.vraag"
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_hulpvrager:
        class: ClipBundle\Report\VragenPerHulpvrager
        arguments:
            - "@clip.dao.vraag"
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_leeftijdscategorie:
        class: ClipBundle\Report\VragenPerLeeftijdscategorie
        arguments:
            - "@clip.dao.vraag"
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_communicatiekanaal:
        class: ClipBundle\Report\VragenPerCommunicatiekanaal
        arguments:
            - "@clip.dao.vraag"
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_nationaliteit:
        class: ClipBundle\Report\VragenPerNationaliteit
        arguments:
            - "@clip.dao.vraag"
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_vraagsoort:
        class: ClipBundle\Report\VragenPerVraagsoort
        arguments:
            - "@clip.dao.vraag"
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_woonplaats:
        class: ClipBundle\Report\VragenPerWoonplaats
        arguments:
            - "@clip.dao.vraag"
        tags:
            - { name: clip.rapportage, category: Vragen }
