services:
    clip.form.rapportage:
        class: ClipBundle\Form\RapportageType
        tags:
            - { name: form.type }

    clip.report.vragen_per_communicatiekanaal:
        class: ClipBundle\Report\VragenPerCommunicatiekanaal
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_etniciteit:
        class: ClipBundle\Report\VragenPerEtniciteit
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_geslacht:
        class: ClipBundle\Report\VragenPerGeslacht
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_viacategorie:
        class: ClipBundle\Report\VragenPerViacategorie
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_hulpvrager:
        class: ClipBundle\Report\VragenPerHulpvrager
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_leeftijdscategorie:
        class: ClipBundle\Report\VragenPerLeeftijdscategorie
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_maand:
        class: ClipBundle\Report\VragenPerMaand
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_stadsdeel:
        class: ClipBundle\Report\VragenPerStadsdeel
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_vraagsoort:
        class: ClipBundle\Report\VragenPerVraagsoort
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }

    clip.report.vragen_per_woonplaats:
        class: ClipBundle\Report\VragenPerWoonplaats
        arguments:
            - '@ClipBundle\Service\VraagDao'
            - '@ClipBundle\Service\ContactmomentDao'
        tags:
            - { name: clip.rapportage, category: Vragen }
