imports:
    - { resource: daos.yml }
    - { resource: exports.yml }
    - { resource: reports.yml }

services:
    clip.contactmoment.entities:
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@ClipBundle\Service\ClientDao' }
              - { key: vraag, dao: '@ClipBundle\Service\VraagDao' }

    clip.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@ClipBundle\Service\ClientDao' }
              - { key: vraag, dao: '@ClipBundle\Service\VraagDao' }

    clip.vraag.entities:
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@ClipBundle\Service\ClientDao' }

#    clip.event.diensten_lookup_subscriber:
#        class: ClipBundle\Event\DienstenLookupSubscriber
#        arguments:
#            - "@doctrine.orm.entity_manager"
#            - "@router"
#        tags:
#            - { name: kernel.event_subscriber }
#
#    clip.data_fixtures.faker_provider:
#        class: ClipBundle\DataFixtures\ClipFakerProvider
#        tags:
#            - { name: hautelook_alice.faker.provider }

    clip.event_subscriber.postcode:
        class: ClipBundle\Event\PostcodeSubscriber
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: doctrine.event_subscriber }
