imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    ClipBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    clip.contactmoment.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@ClipBundle\Service\ClientDao' }
              - { key: vraag, dao: '@ClipBundle\Service\VraagDao' }

    clip.document.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@ClipBundle\Service\ClientDao' }
              - { key: vraag, dao: '@ClipBundle\Service\VraagDao' }

    clip.vraag.entities:
        public: true
        class: ArrayObject
        arguments:
            -
              - { key: client, dao: '@ClipBundle\Service\ClientDao' }

    clip.event_subscriber.postcode:
        class: ClipBundle\Event\PostcodeSubscriber
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: doctrine.event_subscriber }
