services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    AppBundle\Service\:
        resource: '%kernel.project_dir%/src/AppBundle/Service/'

    AppBundle\Service\DoelstellingDao:
        arguments:
            $repositories: !tagged_iterator app.doelstelling

    app.incident.entities:
        class: ArrayObject
        arguments:
            - - { key: klant, dao: '@AppBundle\Service\KlantDao' }
