services:
    _defaults:
        autowire: true
        autoconfigure: true

    AppBundle\Form\RapportageType:

    AppBundle\Report\Activering:
        arguments:
            $sqlFile: "%kernel.project_dir%/config/sql_reports/activering_reports.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\GeenHulpverlenerscontact:
        arguments:
            $sqlFile: "%kernel.project_dir%/config/sql_reports/geen_hulpverlenerscontact.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\Ladis:
        arguments:
            $sqlFile: "%kernel.project_dir%/config/sql_reports/ladis_report.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\ManagementInloop:
        arguments:
            $sqlFile: "%kernel.project_dir%/config/sql_reports/management_reports_inloop.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\ManagementMW:
        arguments:
            $sqlFile: "%kernel.project_dir%/config/sql_reports/management_reports_mw.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\Veegploeg:
        arguments:
            $sqlFile: "%kernel.project_dir%/config/sql_reports/veegploeg_reports.sql"
        tags:
            - { name: app.rapportage }

    AppBundle\Report\ZrmScorePerPostcodegebied:
        tags:
            - { name: app.rapportage, category: ZRM }

    AppBundle\Report\ZrmV2ScorePerPostcodegebied:
        tags:
            - { name: app.rapportage, category: ZRM }
