imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $tbc_countries: '%tbc_countries%'

    # commands
    AppBundle\Command\:
        resource: '%kernel.project_dir%/src/AppBundle/Command'

    # makers
    AppBundle\Maker\:
        resource: '%kernel.project_dir%/src/AppBundle/Maker'

    AppBundle\Command\DatabaseBackupCommand:
        arguments:
            $dsn: '%env(resolve:DATABASE_URL)%'

    # controllers
    AppBundle\Controller\:
        resource: '%kernel.project_dir%/src/AppBundle/Controller'

    AppBundle\Controller\AbstractController:
        calls:
            - setEntityManager: ['@doctrine.orm.default_entity_manager']

    AppBundle\Controller\Admin\KlantenController:
        arguments:
            $logger: '@monolog.logger.merge'

    AppBundle\Controller\KlantenController:
        arguments:
             $export: '@app.export.klanten'

    AppBundle\Controller\RapportagesController:
        arguments:
            $export: '@AppBundle\Export\ReportExport'
            $reports: !tagged_iterator app.rapportage

    AppBundle\Controller\ZrmsController:
        arguments:
            $entities: '@app.zrm.entities'

    AppBundle\Controller\DocumentenController:
        arguments:
            $entities: '@app.document.entities'

    AppBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@app.export.vrijwilligers'

    AppBundle\Controller\MedewerkersController:
        arguments:
            $roleHierarchy: "%security.role_hierarchy.roles%"
            $export: '@app.export.medewerkers'

    AppBundle\Controller\DoelstellingenController:
        arguments:
            $export:  '@app.export.doelstellingen'

    AppBundle\Controller\DownloadController:
        arguments:
            - !tagged_iterator app.downloads

    AppBundle\Event\PreventSaveForDateRangeEventListener:
        arguments:
            - '%env(bool:PREVENT_SAVE_ENABLED)%'
            - '%prevent_save_modified_before%'
            - '%prevent_save_modified_after%'
            - '%prevent_save_exclude_entities%'
            - '%kernel.debug%'
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preRemove }

    AppBundle\Security\ControllerAccessVoter:

    AppBundle\Security\ControllerVoter:

    AppBundle\Event\LoginEventListener:
        arguments:
            $tokenStorage: '@security.untracked_token_storage'
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\LoginSuccessEvent, method: onLoginSuccess }

    AppBundle\Event\CheckLdapGroupsListener:
        arguments:
            - '@security.ldap_locator'
            - '%ldap_base_dn%'
            - '%env(LDAP_SEARCH_USER)%'
            - '%env(LDAP_SEARCH_PASSWORD)%'
            - '%roles_groups%'
        tags:
            - { name: kernel.event_listener, event: Symfony\Component\Security\Http\Event\CheckPassportEvent, method: onCheckPassport }

    twig.extension.routing: # override default routing extension
        class: AppBundle\Twig\EcdRoutingExtension
        arguments:
            - '@router'
            - '@request_stack'

    AppBundle\Doctrine\EcdNamingStrategy:

    AppBundle\Service\ECDHelper:

    AppBundle\Twig\AppExtension:
        arguments:
            - '@request_stack'
            - '%kernel.default_locale%'
            - '%administrator_name%'
            - '%administrator_email%'
            - '%tbc_months_period%'
            - '@AppBundle\Service\ECDHelper'

    AppBundle\Form\DoelstellingType:
        arguments:
            - '@security.authorization_checker'
            - '@AppBundle\Service\DoelstellingDao'

    AppBundle\Security\DoelstellingVoter:
        arguments:
            - '@security.access.decision_manager'

    AppBundle\Form\AddressType:

    AppBundle\Form\KlantType:
        arguments:
            $tbc_countries: '%tbc_countries%'

    AppBundle\Form\KlantMergeType:

    AppBundle\Form\MedewerkerFilterType:
        arguments: ["%security.role_hierarchy.roles%"]

    AppBundle\Form\VrijwilligerType:

    AppBundle\Form\MedewerkerType:
        arguments: ["@security.token_storage"]

    AppBundle\Event\KernelSubscriber:
        arguments:
            - '@twig'
            -
                App: null
                Clip: 'CLIP'
                ErOpUit: 'ErOpUit-kalender'
                Ga: 'Groepsactiviteiten'
                Inloop: 'Inloophuizen'
                Iz: 'Informele zorg'
                Mw: 'Maatschappelijk werk'
                Oek: 'Op eigen kracht'
                Oekraine: 'Oekraïne'
                Pfo: 'PFO'
                Tw: 'Tijdelijk wonen'
                Uhk: 'Uit het krijt'

    AppBundle\Event\DienstenLookupSubscriber:

    app.document.entities:
        class: ArrayObject
        arguments:
            -
                - { key: klant, dao: '@AppBundle\Service\KlantDao' }
                - { key: vrijwilliger, dao: '@AppBundle\Service\VrijwilligerDao' }

    app.zrm.entities:
        class: ArrayObject
        arguments:
            -
                - { key: klant, dao: '@AppBundle\Service\KlantDao' }

    AppBundle\Twig\FallbackLoader:
        arguments:
            - ['%kernel.project_dir%/templates']
        tags:
            - { name: twig.loader, priority: -1 }

    sensio_framework_extra.view.guesser: # overrides default template guesser
        class: AppBundle\Twig\TemplateGuesser

