services:
    GaBundle\Service\GroepDao:
        parent: app.dao.abstract

    GaBundle\Service\KlantIntakeDao:
        parent: app.dao.abstract

    GaBundle\Service\KlantLidmaatschapDao:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@knp_paginator'
            - 100
