groepsactiviteiten_klanten_index:
    path: groepsactiviteiten_klanten

groepsactiviteiten_vrijwilligers_index:
    path: groepsactiviteiten_vrijwilligers

ga_annotations:
    resource: "@GaBundle/Controller"
    type: annotation
    prefix: /ga

ga_index:
    path: /ga/
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: ga_klantdossiers_index
