groepsactiviteiten_klanten_index:
    path: groepsactiviteiten_klanten

groepsactiviteiten_vrijwilligers_index:
    path: groepsactiviteiten_vrijwilligers

groepsactiviteiten_intakes_view:
    path: /groepsactiviteiten/intakes/Klant/{klant_id}
