services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    ScipBundle\Service\:
        resource: '%kernel.project_dir%/src/ScipBundle/Service/'

    scip.deelname.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@ScipBundle\Service\DeelnemerDao' }
              - { key: project, dao: '@ScipBundle\Service\ProjectDao' }

    scip.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@ScipBundle\Service\DeelnemerDao' }

    scip.verslag.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@ScipBundle\Service\DeelnemerDao' }

    scip.werkdoel.entities:
        class: ArrayObject
        arguments:
            -
              - { key: deelnemer, dao: '@ScipBundle\Service\DeelnemerDao' }
