imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    ScipBundle\Event\DienstenLookupSubscriber:

    ScipBundle\Security\DeelnameVoter:
        arguments:
            - '@security.access.decision_manager'
            - '@ScipBundle\Service\ToegangsrechtDao'

    ScipBundle\Security\DeelnemerVoter:
        arguments:
            - '@security.access.decision_manager'
            - '@ScipBundle\Service\ToegangsrechtDao'

    ScipBundle\Security\DocumentVoter:
        arguments:
            - '@security.access.decision_manager'
            - '@ScipBundle\Service\ToegangsrechtDao'
            - '@ScipBundle\Service\DeelnemerDao'

    ScipBundle\Security\ProjectVoter:
        arguments:
            - '@security.access.decision_manager'
            - '@ScipBundle\Service\ToegangsrechtDao'

    ScipBundle\Event\DeelnemerEventSubscriber:
        arguments:
            - '@event_dispatcher'

    ScipBundle\Form\ProjectSelectType:
        arguments:
            - "@security.token_storage"
            - "@security.authorization_checker"
