services:
    IzBundle\Service\AfsluitingDao:
        parent: app.dao.abstract

    IzBundle\Service\BinnengekomenViaDao:
        parent: app.dao.abstract

    IzBundle\Service\ContactOntstaanDao:
        parent: app.dao.abstract

    IzBundle\Service\DoelgroepDao:
        parent: app.dao.abstract

    IzBundle\Service\DoelstellingDao:
        parent: app.dao.abstract

    IzBundle\Service\EindeVraagAanbodDao:
        parent: app.dao.abstract

    IzBundle\Service\EindeKoppelingDao:
        parent: app.dao.abstract

    IzBundle\Service\EindeVraagAanbodDao:
        parent: app.dao.abstract

    IzBundle\Service\HulpaanbodDao:
        parent: app.dao.abstract
    
    IzBundle\Service\HulpvraagDao:
        parent: app.dao.abstract

    IzBundle\Service\HulpvraagsoortDao:
        parent: app.dao.abstract

    IzBundle\Service\IntervisiegroepDao:
        parent: app.dao.abstract

    IzBundle\Service\KlantDao:
        parent: app.dao.abstract

    IzBundle\Service\KoppelingDao:
        parent: app.dao.abstract
    
    IzBundle\Service\ProjectDao:
        parent: app.dao.abstract

    IzBundle\Service\VrijwilligerDao:
        parent: app.dao.abstract
