services:
    iz.report.managementrapportage:
        class: IzBundle\Report\Managementrapportage
        arguments:
            - "@iz.repository.iz_hulpvraag"
            - "@iz.repository.doelstelling"
            - "@iz.repository.iz_project"
        tags:
            - { name: iz.rapportage, category: Management }

    iz.report.hulpvragen.per_project_stadsdeel:
        class: IzBundle\Report\HulpvragenPerProjectStadsdeel
        arguments:
            - "@iz.repository.iz_hulpvraag"
        tags:
            - { name: iz.rapportage, category: Hulpvragen }

    iz.report.koppelingen.totaal:
        class: IzBundle\Report\KoppelingenTotaal
        arguments:
            - "@iz.repository.iz_hulpvraag"
        tags:
            - { name: iz.rapportage, category: Koppelingen }

    iz.report.koppelingen.per_coordinator:
        class: IzBundle\Report\KoppelingenPerCoordinator
        arguments:
            - "@iz.repository.iz_hulpvraag"
        tags:
            - { name: iz.rapportage, category: Koppelingen }

    iz.report.koppelingen.per_project:
        class: IzBundle\Report\KoppelingenPerProject
        arguments:
            - "@iz.repository.iz_hulpvraag"
        tags:
            - { name: iz.rapportage, category: Koppelingen }

    iz.report.koppelingen.per_stadsdeel:
        class: IzBundle\Report\KoppelingenPerStadsdeel
        arguments:
            - "@iz.repository.iz_hulpvraag"
        tags:
            - { name: iz.rapportage, category: Koppelingen }

    iz.report.koppelingen.per_postcodegebied:
        class: IzBundle\Report\KoppelingenPerPostcodegebied
        arguments:
            - "@iz.repository.iz_hulpvraag"
        tags:
            - { name: iz.rapportage, category: Koppelingen }

    iz.report.koppelingen.per_project_stadsdeel:
        class: IzBundle\Report\KoppelingenPerProjectStadsdeel
        arguments:
            - "@iz.repository.iz_hulpvraag"
        tags:
            - { name: iz.rapportage, category: Koppelingen }

    iz.report.koppelingen.per_project_postcodegebied:
        class: IzBundle\Report\KoppelingenPerProjectPostcodegebied
        arguments:
            - "@iz.repository.iz_hulpvraag"
        tags:
            - { name: iz.rapportage, category: Koppelingen }

    iz.report.klanten.totaal:
        class: IzBundle\Report\KlantenTotaal
        arguments:
            - "@iz.repository.iz_klant"
        tags:
            - { name: iz.rapportage, category: Deelnemers }

    iz.report.klanten.per_project:
        class: IzBundle\Report\KlantenPerProject
        arguments:
            - "@iz.repository.iz_klant"
        tags:
            - { name: iz.rapportage, category: Deelnemers }

    iz.report.klanten.per_stadsdeel:
        class: IzBundle\Report\KlantenPerStadsdeel
        arguments:
            - "@iz.repository.iz_klant"
        tags:
            - { name: iz.rapportage, category: Deelnemers }

    iz.report.klanten.per_project_stadsdeel:
        class: IzBundle\Report\KlantenPerProjectStadsdeel
        arguments:
            - "@iz.repository.iz_klant"
        tags:
            - { name: iz.rapportage, category: Deelnemers }

    iz.report.vrijwilligers.totaal:
        class: IzBundle\Report\VrijwilligersTotaal
        arguments:
            - "@iz.repository.iz_vrijwilliger"
        tags:
            - { name: iz.rapportage, category: Vrijwilligers }

    iz.report.vrijwilligers.totaal_namenlijst:
        class: IzBundle\Report\VrijwilligersTotaalNamenlijst
        arguments:
            - "@iz.repository.iz_vrijwilliger"
        tags:
            - { name: iz.rapportage, category: Vrijwilligers }

    iz.report.vrijwilligers.per_project:
        class: IzBundle\Report\VrijwilligersPerProject
        arguments:
            - "@iz.repository.iz_vrijwilliger"
        tags:
            - { name: iz.rapportage, category: Vrijwilligers }

    iz.report.vrijwilligers.per_project_namenlijst:
        class: IzBundle\Report\VrijwilligersPerProjectNamenlijst
        arguments:
            - "@iz.repository.iz_vrijwilliger"
        tags:
            - { name: iz.rapportage, category: Vrijwilligers }

    iz.report.vrijwilligers.per_stadsdeel_klant:
        class: IzBundle\Report\VrijwilligersPerStadsdeelKlant
        arguments:
            - "@iz.repository.iz_vrijwilliger"
        tags:
            - { name: iz.rapportage, category: Vrijwilligers }

    iz.report.vrijwilligers.per_stadsdeel_vrijwilliger:
        class: IzBundle\Report\VrijwilligersPerStadsdeelVrijwilliger
        arguments:
            - "@iz.repository.iz_vrijwilliger"
        tags:
            - { name: iz.rapportage, category: Vrijwilligers }

    iz.report.vrijwilligers.per_project_stadsdeel_klant:
        class: IzBundle\Report\VrijwilligersPerProjectStadsdeelKlant
        arguments:
            - "@iz.repository.iz_vrijwilliger"
        tags:
            - { name: iz.rapportage, category: Vrijwilligers }

    iz.report.vrijwilligers.per_project_stadsdeel_vrijwilliger:
        class: IzBundle\Report\VrijwilligersPerProjectStadsdeelVrijwilliger
        arguments:
            - "@iz.repository.iz_vrijwilliger"
        tags:
            - { name: iz.rapportage, category: Vrijwilligers }
