iz_annotations:
    resource: "@IzBundle/Controller"
    type: annotation
    prefix: /iz

iz_index:
    path: /iz/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: iz_dashboard_index

iz_klanten_add:
    path: /iz_klanten/add

cake_iz_klanten_toon_aanmelding:
    path: /iz_deelnemers/toon_aanmelding/Klant/{klant_id}/{id}

iz_vrijwilligers_add:
    path: /iz_vrijwilligers/add

cake_iz_hulpvragen_view:
    path: /iz_deelnemers/koppelingen/{iz_klant_id}

cake_iz_hulpaanbiedingen_view:
    path: /iz_deelnemers/koppelingen/{iz_vrijwilliger_id}

cake_iz_vrijwilligers_toon_aanmelding:
    path: /iz_deelnemers/toon_aanmelding/Vrijwilliger/{vrijwilliger_id}/{id}

cake_iz_intervisiegroepen_index:
    path: /iz_deelnemers/intervisiegroepen
