iz_deelnemers_index:
    path: /iz_deelnemers

iz_klanten_index:
    path: /iz_klanten

iz_vrijwilligers_index:
    path: /iz_vrijwilligers

iz_hulpvragen_index:
    path: /iz_hulpvragen

iz_hulpaanbiedingen_index:
    path: /iz_hulpaanbiedingen

iz_koppelingen_index:
    path: /iz_koppelingen

iz_rapportages_index:
    path: /iz_rapportages

iz_selecties_index:
    path: /iz_deelnemers/selecties

iz_intervisiegroepen_index:
    path: /iz_intervisiegroepen

iz_beheer_index:
    path: /iz_deelnemers/beheer

iz_klanten_toon_aanmelding:
    path: /iz_deelnemers/toon_aanmelding/Klant/{klantId}/{izKlantId}

iz_annotations:
    resource: "@IzBundle/Controller"
    type: annotation
    prefix: /iz

iz_index:
    path: /iz/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: iz_dashboard_index
