iz_annotations:
    resource: "@IzBundle/Controller"
    type: annotation

iz_index:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: iz_dashboard_index
