iz_annotations:
    resource: "@IzBundle/Controller"
    type: annotation

iz_index:
    path: /
    defaults:
        _controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
        route: iz_dashboard_index
