imports:
    - { resource: daos.yml }
    - { resource: exports.yml }

services:
    IzBundle\Form\RapportageType:
        tags:
            - { name: form.type }

    IzBundle\Form\IzKlantFilterType:
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    IzBundle\Form\IzVrijwilligerFilterType:
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }

    iz.event.diensten_lookup_subscriber:
        class: IzBundle\Event\DienstenLookupSubscriber
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@router"
        tags:
            - { name: kernel.event_subscriber }

    iz.repository.doelstelling:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - IzBundle\Entity\Doelstelling

    iz.repository.iz_hulpvraag:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - IzBundle\Entity\Hulpvraag

    iz.repository.iz_klant:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - IzBundle\Entity\IzKlant

    iz.repository.project:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - IzBundle\Entity\Project

    iz.repository.iz_vrijwilliger:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - IzBundle\Entity\IzVrijwilliger
