services:
    _defaults:
        autowire: true
        autoconfigure: true

    iz.data_fixtures.faker_provider:
        class: IzBundle\DataFixtures\IzFakerProvider
        tags:
            - { name: nelmio_alice.faker.provider }
