imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }

services:
    BuurtboerderijBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
