services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $itemsPerPage: '%pagination.items_per_page%'

    InloopBundle\Service\:
        resource: '%kernel.project_dir%/src/InloopBundle/Service/'

    InloopBundle\Service\LocatieDaoInterface: '@InloopBundle\Service\LocatieDao'

    inloop.document.entities:
        class: ArrayObject
        arguments:
            -
              - { key: vrijwilliger, dao: '@InloopBundle\Service\VrijwilligerDao' }

    inloop.locatietijd.entities:
        class: ArrayObject
        arguments:
            -
              - { key: locatie, dao: '@InloopBundle\Service\LocatieDao' }

    inloop.memo.entities:
        class: ArrayObject
        arguments:
            -
              - { key: vrijwilliger, dao: '@InloopBundle\Service\VrijwilligerDao' }
              -
    inloop.deelname.entities:
        class: ArrayObject
        arguments:
            -
                - { key: vrijwilliger, dao: '@InloopBundle\Service\VrijwilligerDao' }

    inloop.incident.entities:
        class: ArrayObject
        arguments:
            - - { key: klant, dao: '@InloopBundle\Service\KlantDao' }
