services:
    _defaults:
        autowire: true
        autoconfigure: true

    inloop.export.vrijwilliger:
        class: AppBundle\Export\GenericExport
        arguments:
            - InloopBundle\Entity\Vrijwilliger
            -
                Nummer: { expression: 'entity.getVrijwilliger().getId()' }
                Aanmelddatum: { expression: 'entity.getAanmelddatum()', type: 'date' }
                Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
                Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
                Geslacht: { expression: 'entity.getVrijwilliger().getGeslacht()' }
                Voornaam: { expression: 'entity.getVrijwilliger().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getVrijwilliger().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getVrijwilliger().getAchternaam()' }
                Geboortedatum: { expression: 'entity.getVrijwilliger().getGeboortedatum()', type: 'date' }
                Adres: { expression: 'entity.getVrijwilliger().getAdres()' }
                Postcode: { expression: 'entity.getVrijwilliger().getPostcode()' }
                Woonplaats: { expression: 'entity.getVrijwilliger().getPlaats()' }
                E-mail: { expression: 'entity.getVrijwilliger().getEmail()' }
                Mobiel: { expression: 'entity.getVrijwilliger().getMobiel()' }
                Telefoon: { expression: 'entity.getVrijwilliger().getTelefoon()' }
                Werkgebied: { expression: 'entity.getVrijwilliger().getWerkgebied()' }
                GGW-gebied: { expression: 'entity.getVrijwilliger().getPostcodegebied()' }
                Stagiair: { expression: 'entity.isStagiair()' }
                Postvoorkeur: { expression: 'entity.getVrijwilliger().getGeenPost()==false?"Post":"Geen Post"' }
                Emailvoorkeur: { expression: 'entity.getVrijwilliger().getGeenEmail()==false?"Email":"Geen Email"' }
                Medewerker Intake: { expression: 'entity.getMedewerker()' }
                Medewerker Locatie: { expression: 'entity.getMedewerkerLocatie()' }
                Binnengekomen via: { expression: 'entity.getBinnenVia()' }
                Locaties: { expression: 'entity.getLocaties()' }
                VOG aangevraagd: { expression: 'entity.getVrijwilliger().getVogAangevraagd()' }
                VOG aanwezig: { expression: 'entity.getVrijwilliger().getVogAanwezig()' }
                Overeenkomst aanwezig: { expression: 'entity.getVrijwilliger().getOvereenkomstAanwezig()' }

    inloop.export.vrijwilligerdownload:
        class: AppBundle\Export\GenericExport
        arguments:
            - InloopBundle\Entity\Vrijwilliger
            - Rubriek: { expression: '"InloopVrijwilliger"' }
              Nummer: { expression: 'entity.getVrijwilliger().getId()' }
              Startdatum: { expression: 'entity.getStartdatum()', type: 'date' }
              Afsluitdatum: { expression: 'entity.getAfsluitdatum()', type: 'date' }
              Geslacht: { expression: 'entity.getVrijwilliger().getGeslacht()' }
              Voornaam: { expression: 'entity.getVrijwilliger().getVoornaam()' }
              Tussenvoegsel: { expression: 'entity.getVrijwilliger().getTussenvoegsel()' }
              Achternaam: { expression: 'entity.getVrijwilliger().getAchternaam()' }
              Geboortedatum: { expression: 'entity.getVrijwilliger().getGeboortedatum()', type: 'date' }
              E-mail: { expression: 'entity.getVrijwilliger().getEmail()' }
              Adres: { expression: 'entity.getVrijwilliger().getAdres()' }
              Postcode: { expression: 'entity.getVrijwilliger().getPostcode()' }
              Woonplaats: { expression: 'entity.getVrijwilliger().getPlaats()' }
              Werkgebied: { expression: 'entity.getVrijwilliger().getWerkgebied()' }
              Postvoorkeur: { expression: 'entity.getVrijwilliger().getGeenPost() ? "Geen post" : "Wel post"' }
              E-mailvoorkeur: { expression: 'entity.getVrijwilliger().getGeenEmail() ? "Geen e-mail" : "Wel e-mail"' }
            - 'Vrijwilligers Inloop'
            - '@InloopBundle\Service\VrijwilligerDao'
        tags:
            - { name: app.downloads }

    inloop.export.registraties:
        class: InloopBundle\Export\RegistratiesExport
        arguments:
            - InloopBundle\Entity\Registratie
            -
                Nummer: { expression: 'entity.getKlant().getId()' }
                Voornaam: { expression: 'entity.getKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getKlant().getAchternaam()' }
                Geslacht: { expression: 'entity.getKlant().getGeslacht()' }
                Adres: { expression: 'entity.getKlant().getAdres()' }
                Postcode: { expression: 'entity.getKlant().getPostcode()' }
                Woonplaats: { expression: 'entity.getKlant().getPlaats()' }
                E-mail: { expression: 'entity.getKlant().getEmail()' }
                Mobiel: { expression: 'entity.getKlant().getMobiel()' }
                Telefoon: { expression: 'entity.getKlant().getTelefoon()' }
                Werkgebied: { expression: 'entity.getKlant().getWerkgebied()' }
                GGW-gebied: { expression: 'entity.getKlant().getPostcodegebied()' }
                Geboorteland: { expression: 'entity.getKlant().getGeboorteland()' }
                Nationaliteit: { expression: 'entity.getKlant().getNationaliteit()' }
                Locatie: { expression: 'entity.getLocatie()' }
                Binnen: { expression: 'entity.getBinnen()', type: 'datetime' }
                Buiten: { expression: 'entity.getBuiten()', type: 'datetime' }
                Maaltijd: { expression: 'entity.isMaaltijd()' }
                Activering: { expression: 'entity.isActivering()' }
                Kleding: { expression: 'entity.isKleding()' }
                Veegploeg: { expression: 'entity.isVeegploeg()' }
                Inkomens: { expression: 'export.getInkomens(entity.getKlant())' }
                Verblijf in Nederland sinds: { expression: 'entity.getKlant().getLaatsteIntake().getVerblijfInNederlandSinds()', condition: 'entity.getKlant().getLaatsteIntake()', type: 'date' }
                Verblijf in Amsterdam sinds: { expression: 'entity.getKlant().getLaatsteIntake().getVerblijfInAmsterdamSinds()', condition: 'entity.getKlant().getLaatsteIntake()', type: 'date' }
                Verblijfsstatus: { expression: 'entity.getKlant().getLaatsteIntake().getVerblijfsstatus()', condition: 'entity.getKlant().getLaatsteIntake()' }
                Woonsituatie: { expression: 'entity.getKlant().getLaatsteIntake().getWoonsituatie()', condition: 'entity.getKlant().getLaatsteIntake()' }

    inloop.export.schorsing:
        class: AppBundle\Export\GenericExport
        arguments:
            - InloopBundle\Entity\Schorsing
            -
                Nummer: { expression: 'entity.getKlant().getId()' }
                Voornaam: { expression: 'entity.getKlant().getVoornaam()' }
                Tussenvoegsel: { expression: 'entity.getKlant().getTussenvoegsel()' }
                Achternaam: { expression: 'entity.getKlant().getAchternaam()' }
                Geslacht: { expression: 'entity.getKlant().getGeslacht()' }
                Begindatum: { expression: 'entity.getDatumVan()', type: 'date' }
                Einddatum: { expression: 'entity.getDatumTot()', type: 'date' }
                Locaties: { expression: 'entity.getLocaties()' }
                Redenen: { expression: 'entity.getRedenen()' }

    inloop.export.report:
        class: AppBundle\Export\ReportExport
