services:
    _defaults:
        autowire: true
        autoconfigure: true

    InloopBundle\Form\RapportageType:

    InloopBundle\Report\EUBurgers:
        tags:
            - { name: inloop.rapportage }

    InloopBundle\Report\Klantenoverzicht:
        tags:
            - { name: inloop.rapportage }

    InloopBundle\Report\Locatie:
        tags:
            - { name: inloop.rapportage }

    InloopBundle\Report\Incidenten:
        tags:
            - { name: inloop.rapportage }

    InloopBundle\Report\KlantenoverzichtNachtopvang:
        tags:
            - { name: inloop.rapportage }

    InloopBundle\Report\RepatrieringenPerInloopKlant:
        arguments:
            $sqlFile: "%kernel.project_dir%/config/sql_reports/repatrieringen_per_inloopklant.sql"
        tags:
            - { name: inloop.rapportage, category: Repatriëring }

    InloopBundle\Report\RepatrieringenPerLand:
        tags:
            - { name: inloop.rapportage, category: Repatriëring }
