imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

parameters:
    inloop.vrijwilligers_locaties:
        vrijwilliger_oud_west: 14
        vrijwilliger_eik: 9
        vrijwilliger_de_kloof: 10
        vrijwilliger_macom: 11
        vrijwilliger_macom_nacht: 12
        vwspreekbuis: 15

services:
    _defaults:
        autowire: true
        autoconfigure: true

    InloopBundle\Command\:
        resource: '%kernel.project_dir%/src/InloopBundle/Command'

    InloopBundle\Form\:
        resource: '%kernel.project_dir%/src/InloopBundle/Form'

    InloopBundle\Controller\:
        resource: '%kernel.project_dir%/src/InloopBundle/Controller'

    InloopBundle\Controller\KlantenController:
        arguments:
            $tbc_countries: '%tbc_countries%'

    InloopBundle\Controller\LocatiesController:
        arguments:
            $accessStrategies: '%access_strategies%'

    InloopBundle\Controller\IntakesController:
        arguments:
            $dao: '@InloopBundle\Service\IntakeDao'
            $tbc_countries: '%tbc_countries%'
            $accessStrategies: '%access_strategies%'
            $amocVerblijfsstatus: '%amocverblijfsstatus%'

    InloopBundle\Controller\DeelnamesController:
        arguments:
            $entities: '@inloop.deelname.entities'

    InloopBundle\Controller\DocumentenController:
        arguments:
            $entities: '@inloop.document.entities'

    InloopBundle\Controller\IncidentenController:
        arguments:
            $entities: '@inloop.incident.entities'

    InloopBundle\Controller\LocatietijdenController:
        arguments:
            $entities: '@inloop.locatietijd.entities'

    InloopBundle\Controller\MemosController:
        arguments:
            $entities: '@inloop.memo.entities'

    InloopBundle\Controller\RapportagesController:
        arguments:
            $export: '@inloop.export.report'
            $reports: !tagged_iterator inloop.rapportage

    InloopBundle\Controller\RegistratiesController:
        arguments:
            $export: '@inloop.export.registraties'
            $tbc_countries: '%tbc_countries%'
            $tbc_months_period: '%tbc_months_period%'

    InloopBundle\Controller\SchorsingenController:
        arguments:
            $export: '@inloop.export.schorsing'

    InloopBundle\Controller\VerslagenController:
        arguments:
            $export: '@mw.export.klanten'

    InloopBundle\Controller\VrijwilligersController:
        arguments:
            $export: '@inloop.export.vrijwilliger'

    InloopBundle\Service\AccessUpdater:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@InloopBundle\Service\KlantDao'
            - '@InloopBundle\Service\LocatieDao'
            - "%access_strategies%"
            - "%amocverblijfsstatus%"

    InloopBundle\Event\IntakeSubscriber:
        arguments:
            - '@InloopBundle\Service\KlantDao'
            - "@logger"
            - "@twig"
            - "@mailer"
            - '@InloopBundle\Service\AccessUpdater'
            - "%env(INFORMELE_ZORG_MAIL)%"
            - "%env(DAGBESTEDING_MAIL)%"
            - "%env(HULPVERLENING_MAIL)%"

    InloopBundle\Event\DossierSubscriber:
        arguments:
            - '@InloopBundle\Service\KlantDao'
            - '@InloopBundle\Service\AccessUpdater'

    InloopBundle\Event\LocatieSubscriber:
        arguments:
            - '@InloopBundle\Service\AccessUpdater'

    InloopBundle\Event\DienstenLookupSubscriber:

    InloopBundle\Event\RegistratieSubscriber:

    InloopBundle\Security\IntakeVoter:
        arguments:
            - "@security.access.decision_manager"

    InloopBundle\Security\RegistratieVoter:
        arguments:
            - "%inloop.vrijwilligers_locaties%"


    registratie_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - InloopBundle\Entity\Registratie

    InloopBundle\Repository\RegistratieRepository:
        arguments:
            $class: "@registratie_metadata"
        calls:
            - method: setSpuitomruilLocaties
              arguments:
                  - '%spuitomruil_locaties%'
        tags:
            - app.doelstelling

    InloopBundle\Form\LocatieTypeSelectType:
