imports:
    - { resource: daos.yaml }
    - { resource: exports.yaml }
    - { resource: reports.yaml }

parameters:
    inloop.vrijwilligers_locaties:
        vrijwilliger_oud_west: 14
        vrijwilliger_eik: 9
        vrijwilliger_de_kloof: 10
        vrijwilliger_macom: 11
        vrijwilliger_macom_nacht: 12
        vwspreekbuis: 15

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $tbc_countries: '%tbc_countries%'
            $accessStrategies: '%access_strategies%'
            $amocVerblijfsstatus: '%amoc_verblijfsstatus%'

    InloopBundle\Command\:
        resource: '%kernel.project_dir%/src/InloopBundle/Command'

    InloopBundle\Form\:
        resource: '%kernel.project_dir%/src/InloopBundle/Form'

    InloopBundle\Controller\:
        resource: '%kernel.project_dir%/src/InloopBundle/Controller'

    InloopBundle\Controller\DeelnamesController:
        arguments:
            $entities: '@inloop.deelname.entities'

    InloopBundle\Controller\DocumentenController:
        arguments:
            $entities: '@inloop.document.entities'

    InloopBundle\Controller\IncidentenController:
        arguments:
            $entities: '@inloop.incident.entities'

    InloopBundle\Controller\LocatietijdenController:
        arguments:
            $entities: '@inloop.locatietijd.entities'

    InloopBundle\Controller\MemosController:
        arguments:
            $entities: '@inloop.memo.entities'

    InloopBundle\Controller\RapportagesController:
        arguments:
            $export: '@inloop.export.report'
            $reports: !tagged_iterator inloop.rapportage

    InloopBundle\Controller\RegistratiesController:
        arguments:
            $export: '@inloop.export.registraties'
            $tbc_countries: '%tbc_countries%'
            $tbc_months_period: '%tbc_months_period%'

    InloopBundle\Controller\SchorsingenController:
        arguments:
            $export: '@inloop.export.schorsing'

    InloopBundle\Controller\VerslagenController:
        arguments:
            $export: '@mw.export.klanten'

    InloopBundle\Controller\VrijwilligersController:
        arguments:
            $dao: '@InloopBundle\Service\VrijwilligerDao'
            $export: '@inloop.export.vrijwilliger'

    InloopBundle\Service\AccessUpdater:
        arguments:
            $strategies: !tagged_iterator 'inloop.access_strategy'

    # Implementations of InloopBundle\Strategy\StrategyInterface should be tagged
    # with 'inloop.access_strategy' in order to be used by service
    # InloopBundle\Service\AccessUpdater. Note that these strategies are
    # "Tagged Services with Priority" as described in the documentation:
    # https://symfony.com/doc/5.x/service_container/tags.html#tagged-services-with-priority.
    # The higher the number, the earlier the tagged service will be located in the collection.

    InloopBundle\Strategy\SpecificLocationStrategy:
        tags:
            - {'name': 'inloop.access_strategy', priority: 100}

    InloopBundle\Strategy\AmocWestStrategy:
        tags: [{'name': 'inloop.access_strategy', priority: 90}]

    InloopBundle\Strategy\VillaWesterweideStrategy:
        tags:
            - {'name': 'inloop.access_strategy', priority: 80}

    InloopBundle\Strategy\AmocStrategy:
        tags:
            - {'name': 'inloop.access_strategy', priority: 70}

    InloopBundle\Strategy\WinteropvangEUBurgersStrategy:
        tags:
            - {'name': 'inloop.access_strategy', priority: 60}

    InloopBundle\Strategy\GebruikersruimteStrategy:
        tags:
            - {'name': 'inloop.access_strategy', priority: 50}

    InloopBundle\Strategy\ToegangOverigStrategy:
        tags:
            - {'name': 'inloop.access_strategy', priority: 40}

    InloopBundle\Event\IntakeSubscriber:
        arguments:
            - '@InloopBundle\Service\KlantDao'
            - "@logger"
            - "@twig"
            - "@mailer"
            - '@InloopBundle\Service\AccessUpdater'
            - "%env(INFORMELE_ZORG_MAIL)%"
            - "%env(DAGBESTEDING_MAIL)%"
            - "%env(HULPVERLENING_MAIL)%"

    InloopBundle\Event\DossierSubscriber:
        arguments:
            - '@InloopBundle\Service\KlantDao'
            - '@InloopBundle\Service\AccessUpdater'

    InloopBundle\Event\LocatieSubscriber:
        arguments:
            - '@InloopBundle\Service\AccessUpdater'

    InloopBundle\Event\DienstenLookupSubscriber:

    InloopBundle\Event\RegistratieSubscriber:

    InloopBundle\Security\IntakeVoter:
        arguments:
            - "@security.access.decision_manager"

    InloopBundle\Security\RegistratieVoter:
        arguments:
            - "%inloop.vrijwilligers_locaties%"


    registratie_metadata:
        class: Doctrine\ORM\Mapping\ClassMetadata
        arguments:
            - InloopBundle\Entity\Registratie

    InloopBundle\Repository\RegistratieRepository:
        arguments:
            $class: "@registratie_metadata"
        calls:
            - method: setSpuitomruilLocaties
              arguments:
                  - '%spuitomruil_locaties%'
        tags:
            - app.doelstelling

    InloopBundle\Form\LocatieTypeSelectType:

when@test:
    services:
        # For testing the AccessUpdater, we need the configured Tagged Services with Priority.
        Tests\InloopBundle\Service\StrategyContainer:
            public: true
            arguments:
                $strategies: !tagged_iterator 'inloop.access_strategy'
